### ISSUE TITLE
Variables bdd url_accueil_conges non prise en charge

### ISSUE THREAD

**Issue by cyberesprit** [Libertempo/Libertempo-web#101]
Bonjour,
1. À la mire de connexion, la variable de bdd url_accueil_conges n'est pas prise en compte dans le formulaire et donc on est redirigé vers /index.php (le / en trop aussi)
2. Pareil pour la même variable bdd url_accueil_conges non prise en compte par exemple avec les onglets (comme Demande en cours, Historique des congés, ...) et le bouton Valider dans Nouvelle absence (et sûrement ailleurs)

C'est problématique derrière un proxy web.

Librement

**Comment by Prytoegrian** [comment]
Tu peux me dire ce que tu as dans `$_SESSION['config']` dans chacun de tes cas ?
Autrement, donnes moi ton procédé pour en arriver là, que je puisse le reproduire.

**Comment by wouldsmina** [comment]
Bonjour,

Question bête, dans le configuration as tu bien renseigné url_accueil_conges avec une url complète (https://Libertempo.mondmaine.fr)?

**Comment by cyberesprit** [comment]
@Prytoegrian : À chaque fois j'ai NULL

@wouldsmina : Non, j'ai mis /leave, il y avait quelque chose de similaire provenant de l'installation avant. Je vais essayer.

**Comment by cyberesprit** [comment]
@wouldsmina Mettre l'url en entier ne change rien, par exemple pour l'onglet « Demandes en cours » au lieu d'avoir https://mydomain.net/leave/utilisateur/user_index.php j'ai directement https://mydomain.net/utilisateur/user_index.php, que ce soit en url complète ou non.

**Comment by wouldsmina** [comment]
C'est parce que tu n'as pas saisie toute l'url.
Ajoute leave tout ira mieux...

**Comment by cyberesprit** [comment]
@wouldsmina : Si j'ai testé avec l'url complète (ou « toute l'url » si tu préfères) ...

J'ai testé avec le contenu /leave et https://mydomain.net/leave mais dans tous les cas ça ne change rien.

**Comment by Prytoegrian** [comment]
Si tu as `null` à chaque fois dans la dimension `$_SESSION['config']`, c'est plus dans cette direction qu'il faut creuser. Tu es toujours sur docker ? Ton container apache peut-il communiquer avec ta base ?

**Comment by cyberesprit** [comment]
Oui toujours sur Docker.
Oui mon conteneur web communique bien avec le conteneur mariadb sinon il me semble que Libertempo ne fonctionnerait pas, si ?

Maintenant je peux faire d'autres tests si tu veux.

**Comment by cyberesprit** [comment]
Je vais tester la variable sur mon installation de base non docker pour voir.

**Comment by wouldsmina** [comment]
oui, c'est une bonne idée!

**Comment by cyberesprit** [comment]
Bon alors, sur une version non docker, le comportement est le même :

- NULL pour la variable $_SESSION["config"]
- url_accueil_conges non pris en compte SAUF pour la déconnexion (l'url qui apparait quand on met le curseur dessus n'est pas celle de cette variable, mais une fois qu'on clic dessus c'est bon)

Dans tous les cas c'est la version 1.7.1, je ne sais pas si ça gêne ?
Mais j'ai une 1.7.0 aussi si il faut ...

**Comment by Prytoegrian** [comment]
Tu peux déboguer le comportement de `fonction_conges::init_config_tab()` (1983) ?

Non ça gêne pas, j'ai pas le souvenir qu'on ai modifié le comportement dans cette version.

**Comment by cyberesprit** [comment]
C'est de ma faute, trop habitué à Symfony2, j'ai mal placé mon var_dump().
La variable $_SESSION et plus particulièrement $_SESSION["config"] n'est pas NULL.

Milles excuses ;-/

Il y a bien la variable et son contenu correct.

J'ai fait une petite recherche avec la commande « grep -r "URL_ACCUEIL_CONGES" * | grep "php:" » et voilà le résultat :

```
deconnexion.php:$URL_ACCUEIL_CONGES=$_SESSION['config']['URL_ACCUEIL_CONGES'];
deconnexion.php:    deconnexion_CAS($URL_ACCUEIL_CONGES);
deconnexion.php:redirect( $URL_ACCUEIL_CONGES );
export/Fonctions.php:           echo " <a href='".ROOT_PATH."export/ics_export.php?usr=".$huser."'>".$_SESSION['config']['URL_ACCUEIL_CONGES']."/export/ics_export.php?usr=".$huser."<a>";
fonctions_conges.php:    $contenu = str_replace("__URL_ACCUEIL_CONGES__", $_SESSION['config']['URL_ACCUEIL_CONGES'], $contenu);
fonctions_conges.php:        $url_accueil_conges = $_SESSION['config']['URL_ACCUEIL_CONGES'] ;
includes/plugins/cet/plugin_active.php:    ('mail_cet_demande', 'APPLI CONGES - Demande stockage pour CET', ' __SENDER_NAME__ a solicité une demande d\'alimentation de son CET dans l\'application de gestion des congés.\r\n\r\nMerci de consulter votre application php_conges : __URL_ACCUEIL_CONGES__/\r\n\r\n-------------------------------------------------------------------------------------------------------\r\nCeci est un message automatique.');";
index.php:                      echo "<p>" . _('divers_veuillez') ." <a href='" .$_SESSION['config']['URL_ACCUEIL_CONGES'] . "/index.php' target='_top'><strong>" . _('divers_vous_authentifier') . "</strong></a></p>\n";
index.php:                      $URL_ACCUEIL_CONGES=$_SESSION['config']['URL_ACCUEIL_CONGES'];
index.php:                      deconnexion_CAS($URL_ACCUEIL_CONGES);
install/Fonctions.php:            $sql_update_lang="UPDATE conges_config SET conf_valeur = '$url_accueil' WHERE conf_nom='URL_ACCUEIL_CONGES' ";
install/upgrade_from_v1.7.0.php:$ajout_mail="INSERT IGNORE INTO `conges_mail` (`mail_nom`, `mail_subject`, `mail_body`) VALUES ('mail_new_absence_conges', 'APPLI CONGES - Nouvelle absence', ' __SENDER_NAME__ vous informe qu\'il sera absent. Ce type de congés ne necéssite pas de validation. Vous pouvez consulter votre application Libertempo : __URL_ACCUEIL_CONGES__/\r\n\r\n-------------------------------------------------------------------------------------------------------\r\nCeci est un message automatique. ');";
install/upgrade_from_v1.7.0.php:$ajout_mail="INSERT IGNORE INTO `conges_mail` (`mail_nom`, `mail_subject`, `mail_body`) VALUES ('mail_modif_demande_conges', 'APPLI CONGES - Modification demande', ' __SENDER_NAME__ à modifié une demande non traité. Vous pouvez consulter votre application Libertempo : __URL_ACCUEIL_CONGES__/\r\n\r\n-------------------------------------------------------------------------------------------------------\r\nCeci est un message automatique. ');";
install/upgrade_from_v1.7.0.php:$ajout_mail="INSERT IGNORE INTO `conges_mail` (`mail_nom`, `mail_subject`, `mail_body`) VALUES ('mail_supp_demande_conges', 'APPLI CONGES - Suppression demande', ' __SENDER_NAME__ à supprimé une demande non traité. Vous pouvez consulter votre application Libertempo : __URL_ACCUEIL_CONGES__/\r\n\r\n-------------------------------------------------------------------------------------------------------\r\nCeci est un message automatique. ');";
```

En fait je viens de me dire que cette variable ne sert pas à ça et que dans les endroits où ça coince c'est parce-que les url commencent par un / alors qu'ils ne le faudrait pas.

C'est certain pour la mire de connexion, je vais vérifier les autres.

**Comment by cyberesprit** [comment]
Je confirme, les liens problématiques sont ceux commençant par un / (slash).
Sans ce slash, pas de souci, et pas besoin d'une variable quelconque pour le proxy web.

**Comment by cyberesprit** [comment]
C'est à priori à cause de $PHP_SELF qui contient l'url de base commençant par un slash.
Pour faciliter les choses, on peut peut-être juste placé un peu de code qui supprime le slash de début de la variable $PHP_SELF à un endroit le plus haut et appelé partout (si ça existe ici).

**Comment by cyberesprit** [comment]
Je teste en ajoutant :

`$PHP_SELF = ltrim($PHP_SELF, "/");`

à la fin du fichier define.php

**Comment by Prytoegrian** [comment]
Il pourrait y avoir la balise `base` html qui pourrait éviter de reprendre tous les liens de l'appli mais : 
* je sais pas si ça fonctionne avec le préfixe « / »
* comme c'est une balise html5, il faudrait voir la compat' du site avec cette version

Tu as quoi comme arborescence dans ton URL pour que ça se vautre comme ça ?

**Comment by cyberesprit** [comment]
Commençons depuis le début ;-)

J'ai un conteneur docker qui sert de proxy web et il redirige selon ce qui est demandé (apache) :

```
        # Libertempo -> leave (congés)
        RewriteRule ^/leave$ /leave/ [R]
        ProxyPass /leave/ http://leave:80/
        ProxyPassReverse /leave/ http://leave:80/

        # Default -> cloud
        ProxyPass / http://127.0.0.1/cloud/
        ProxyPassReverse / http://127.0.0.1/cloud/
```

Quand je tape l'url https://mydomain.net/leave il m'affiche en toute transparence Libertempo se trouvant sur un autre conteneur docker qui a son propre apache et une configuration classique.

Je suis donc à la mire de connexion. Identifiants indiqués, on valide et on se trouve dans Libertempo. Ici, certains liens comme les onglets me redirige sur le cloud /cloud (qui est l'application web à afficher par défaut si rien n'est mentionné) car au lieu d'avoir une url comme :

`https://mydomain.net/leave/utilisateur/user_index.php?session=phpcongesxxx&onglet=demandes_en_cours`

J'ai celle ci :

`https://mydomain.net/utilisateur/user_index.php?session=phpcongesxxx&onglet=demandes_en_cours`

Sans /leave donc.
Et si je modifie $PHP_SELF (et/ou $_SERVER["PHP_SELF"]), j'ai ceci :

`https://mydomain.net/leave/utilisateur/utilisateur/user_index.php?session=phpcongesxxx&onglet=demandes_en_cours`

Avec 2x utilisateur.

En fait, php reconnaît le PHP_SELF du serveur sur celui où il est, pas l'url du proxy.
Pour info je n'ai pas de souci avec Owncloud, et je n'ai ce souci qu'à la connexion avec phpmyadmin, ce qui se corrige en revenant à la page précédente).

**Comment by cyberesprit** [comment]
Pour le moment j'ai apparemment résolu le problème en ajoutant à la fin du fichier « include/session.php » le code suivant :

`$_SERVER['PHP_SELF'] = $_SESSION['config']['URL_ACCUEIL_CONGES']."/".$_SERVER['PHP_SELF'];`

**Comment by Prytoegrian** [comment]
En premier lieu, je déconseille fortement de faire une affectation sur la superglobale. Ensuite, tu nous fais pas du bien avec ta configuration bizarroïde ^^. Je plaisante, ça nous met le nez dans nos erreurs et c'est salutaire. Le fond du problème à mon avis est que l'on utilise des liens relatifs (via `PHP_SELF`) alors qu'il faudrait utiliser de l'absolu de manière à toujours passer par url_accueil_congés : 

```php
function buildUrl($goto, $moduleId = null)
{
    return $_SESSION['config']['URL_ACCUEIL_CONGES'] . getModuleById($moduleId) . $goto;
}
```
C'est un premier jet d'idée pour un correctif.

Je m'interroge sur ta configuration... pas banale ; as-tu un besoin plus précis que ce que tu nous montres là pour utiliser un proxy / deux dockers ? (parce qu'en soit, libertempo n'a pas besoin d'un container pour tourner, tu peux juste lier le volume).

**Comment by cyberesprit** [comment]
Tu veux dire lier le volume au conteneur proxy ? mmh ..

Le conteneur proxy est indépendant, et chaque application/service à son conteneur et si besoin son conteneur de base de donnée à lui tout seul (je t'avouerais que je n'ai pas réussi à séparer les services postfix, dovecot, opendkim etc etc et qu'ils sont donc tous dans le même conteneur, mais c'est une autre histoire ^^).

Donc ici Libertempo est dans son propre conteneur, tout seul, et est lié à un autre conteneur qui lui est exclusivement réservé avec une seul base de donnée.

Dans un sens, si j'avais plusieurs machines ce serait le même problème ;-)

**Comment by cyberesprit** [comment]
Sinon oui, la modification de la superglobale n'est qu'un mauvais patch temporaire.

**Comment by Prytoegrian** [comment]
Ok, pourquoi pas.

Dans ce cas je m'avoue vaincu. En dehors de la proposition que j'ai faite de réécrire tous les liens, je n'ai pas d'autres solutions à proposer, je ne connais pas assez docker pour comprendre le mécanisme de rebond, désolé. (Tu as essayé d'associer des ports différents à tes services dans ton proxy sinon ?)

**Comment by cyberesprit** [comment]
En fait ce n'est pas lié à docker. L'utilisation qui en est faite ici est similaire (pour ne pas dire la même) que si j'avais autant de serveur que de conteneur. Ça se fait souvent en entreprise.

Un serveur proxy web qui est le point d'entrée de l'extérieur, et selon le service ou l'application/site demandé, il renvoi les données en toute transparence provenant d'un des serveurs.

En toute transparence car ce n'est pas une redirection, c'est bien une réécriture d'url, c'est juste qu'au lieu d'avoir client -> serveur, on a client -> proxy -> serveur, et le proxy fait comme un client tout en renvoyant ce qu'il reçoit au "vrai" client.

Bref, en fait oui, ton code est probablement la solution, il faut juste utiliser cette fonction partout où il y a une url à générer ...

**Comment by wouldsmina** [comment]
c'est ce qu'on appel un [reverse proxy](https://fr.wikipedia.org/wiki/Proxy_inverse). je l'utilise aussi dans ma boite, mais j'ai pas ce problème...

**Comment by cyberesprit** [comment]
Je n'ai ce problème qu'avec Libertempo ;-)

Non mais c'est possible que ma conf ne soit pas au top non plus ...

**Comment by cyberesprit** [comment]
@wouldsmina : Il est possible aussi que dans ta boite ce soit par exemple mail.mydomain.net plutôt que comme moi mydomain.net/mail, ce qui est plus simple dans ton cas.

Je préfère cette seconde solution car elle ne pose pas de problème avec https ;-)

**Comment by wouldsmina** [comment]
> Il est possible aussi que dans ta boite ce soit par exemple mail.mydomain.net

c'est tout a fait ça! 

>Je préfère cette seconde solution car elle ne pose pas de problème avec https ;-)

oui, je comprends la problématique du certificat...

**Comment by wouldsmina** [comment]
pas de solution pour ce cas en particulier hormis de forcer $PHP_SELF. Si le problème se représente, on envisagera d'autre solution. :kissing:
