### ISSUE TITLE
Centraliser l'accès à la session en supprimant les passages par get / post

### ISSUE THREAD

**Issue by Prytoegrian** [Libertempo/Libertempo-web#108]
Ref #103

Le fait de passer l'id de session manuellement au sein de l'appli est un frein à l'évolution du code. En effet : 
- on subit de plein fouet des problématiques d'usurpation de session, a contrario de la gestion automatique (ou en tout cas c'est plus facile),
- on peut oublier de transmettre la session
- ça rend les URL illisibles
- ouvrir un onglet de toute pièce ne récupère pas la session courante

La gestion automatique des sessions supporte nativement l'activation des cookies ou non (je crois savoir qu'il y avait une mention de ce type dans `docs/TODO`).

Je propose donc de laisser PHP faire son travail et supprimer les passages à la main. En plus de ça, on pourrait en profiter pour dédier un objet à la session en général, autrement dit un objet qui serait en charge des interactions avec la superglobale `$_SESSION`, sa création et son (éventuelle) destruction.
En plus de centraliser la totalité de la session (en terme de code et de système), ça permettra de refaire proprement le fix minimal apporté suite à #94 et ça nous facilitera aussi la sortie de la config dès qu'on le voudra pour mieux isoler les responsabilités.

La seule solution en l'état actuel du code est de passer par un singleton. On reviendra dessus par la suite.

**Comment by Prytoegrian** [comment]
Histoire de rajouter de l'eau à mon moulin, chromium (mais pas seulement je suppose) a une limite de 99 cookies par domaine et ensuite empêche la connexion pour cause de mauvais en-tête de requête. Je pense que c'est la conséquence du passage en paramètre de la session. 

Ou alors j'ai vraiment fait le bourrin.

**Comment by wouldsmina** [comment]
ah, Est il possible de voir ce compteur pour tester? (je pense que non, mais au cas ou...)

Avec ce que j'ai débuté à faire [ici](https://github.com/wouldsmina/Libertempo/tree/topic/session), tu as le même problème? ( pour tester tu va devoir en faire des manips, c'est un bon moyen de tester :p )

**Comment by Prytoegrian** [comment]
Oui, dans chromium quand tu cliques à gauche du site dans la barre d'adresse. Sous firefox tu cliques au même endroit mais tu n'as pas le nombre, seulement la liste des cookies.

J'ai pas encore testé je t'avouerais, je vais attendre que tu termines.
