### ISSUE TITLE
SUGGESTION: Transformer la pop-up d'export ical en modale

### ISSUE THREAD

**Issue by bbalet** [Libertempo/Libertempo-web#121]
La popup d'export ical est très grande et, selon le navigateur:
- Aussi grande que l'opener.
- Parfois décalée et en dehors de l'écran.
- Elle peut être bloquée par certains plugins, jusqu'à ce que l'utilisateur l'autorise à nouveau.

Alors qu'elle ne contient que très peu d'éléments. 

Mon opinion est que les pop-up sont à proscrire et à remplacer par des modales (c.-à-d. grosso-modo une div dans la fenêtre). Cela évite d'avoir plusieurs fenêtres.

**Comment by Prytoegrian** [comment]
Oui, ou alors supprimer complètement la popup pour que le lien dans la fenêtre principale permette le téléchargement.

**Comment by Prytoegrian** [comment]
Il n'y a pas eu d'avancement sur le sujet depuis plus d'un an, je ferme. S'il y a un vrai besoin, ça reviendra sur le tapis.
