### ISSUE TITLE
Suggestion : compatibilité Internet Explorer

### ISSUE THREAD

**Issue by ooBeNoo** [Libertempo/Libertempo-web#125]
Bonjour,
Pour utiliser Libertempo sur IE9, j'ai apporté certaines modifications :

**1. Forcer le mode EDGE**
Ajout de 
`header('X-UA-Compatible: IE=edge');`

Fichiers impactés :

```
\template\reboot\login_header.php
\template\reboot\popup_header.php
\template\reboot\menu_header.php
\template\reboot\error_header.php
```

on pourrait également mettre une balise meta (elle doit être insérée en premier (juste apres le `<head>`)
`<meta http-equiv="X-UA-Compatible" content="IE=edge" />`

Il est aussi possible de le faire dans un fichier .htaccess
`header set X-UA-Compatible "IE=Edge"`

**2. Fonts**
Création d'un répertoire "fonts" (et dépot des fichiers correspondants, à récupérer sur le net)
`\template\fonts`

Créer les fichiers : 

```
template\reboot\font-awesome.css
template\reboot\googlefonts.css
```

Modifier les fichiers :

```
\template\reboot\login_header.php
\template\reboot\popup_header.php
\template\reboot\menu_header.php
\template\reboot\error_header.php
```

```
<!-- fonts -->
<!--<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,700" type="text/css" />-->
<link rel="stylesheet" href="<?php  echo TEMPLATE_PATH;  ?>googlefonts.css" type="text/css" />

<!-- Font Awesome -->
<!--<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet">-->
<link rel="stylesheet" href="<?php  echo TEMPLATE_PATH;  ?>font-awesome.css" type="text/css" />

```

**3. CSS, coloration des cellules du calendrier**
`\template\reboot\css\reboot.css`

pour chaque coloration particulière, ajouter (en adaptant les couleurs bien entendu) : 

```

background-image: -ms-linear-gradient(right top,#F0F0CC 50%,#FFF 0%);
filter: progid:DXImageTransform.Microsoft.gradient(startColorStr=#00FFFFFF, endColorStr=#FFF0F0CC, GradientType=0);
-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#00FFFFFF, endColorstr=#FFF0F0CC, GradientType=0)"; 
```

**4. Correction de la fonction compter_jours() : fonctions_javascript.php**

```
function compter_jours()
{
    var login = document.forms["dem_conges"].user_login.value;
    var session = document.forms["dem_conges"].session.value;
    var d_debut = document.forms["dem_conges"].new_debut.value;
    var d_fin = document.forms["dem_conges"].new_fin.value;
    var opt_deb = document.forms["dem_conges"].new_demi_jour_deb.value;
    var opt_fin = document.forms["dem_conges"].new_demi_jour_fin.value;
    var p_num = "";

    if( ! opt_deb )
    {
        if( document.forms["dem_conges"].elements["new_demi_jour_deb"][0].checked )
        {
            opt_deb = document.forms["dem_conges"].elements["new_demi_jour_deb"][0].value;
        }
        if( document.forms["dem_conges"].elements["new_demi_jour_deb"][1].checked )
        {
            opt_deb = document.forms["dem_conges"].elements["new_demi_jour_deb"][1].value;
        }
    }

    if( ! opt_fin )
    {
        if( document.forms["dem_conges"].elements["new_demi_jour_fin"][0].checked )
        {
            opt_fin = document.forms["dem_conges"].elements["new_demi_jour_fin"][0].value;
        }
        if( document.forms["dem_conges"].elements["new_demi_jour_fin"][1].checked )
        {
            opt_fin = document.forms["dem_conges"].elements["new_demi_jour_fin"][1].value;
        }
    }   


    if( document.forms["dem_conges"].p_num_to_update ) 
    {
        var p_num = document.forms["dem_conges"].p_num_to_update.value;
    }

    if( (d_debut) && (d_fin))
    {
        var page ='../calcul_nb_jours_pris.php?session='+session+'&date_debut='+d_debut+'&date_fin='+d_fin+'&user='+login+'&opt_debut='+opt_deb+'&opt_fin='+opt_fin+'&p_num='+p_num;

    $.ajax(
    {
        type : 'GET',
        url : page,
        dataType : 'text', // expected returned data format.
        success : function(data)
        {
        var arr = new Array();
    arr = JSON.parse(data);
    document.forms["dem_conges"].new_nb_jours.value=arr["nb"];
    document.getElementById('comment_nbj').innerHTML = arr["comm"];

        },
    });

    }

}

```

Eventuellement, modifier le formulaire de login (non support de "placeholder")
`\template\reboot\login_form.php`

Bien à vous

**Comment by ooBeNoo** [comment]
En pj les fichiers modifiés.

Bien à vous
[files.zip](https://github.com/wouldsmina/Libertempo/files/139313/files.zip)

**Comment by wouldsmina** [comment]
Excellent travail. Merci.

**Comment by Prytoegrian** [comment]
Pour ma part, avant de pouvoir bien cerner le problème qui t'as poussé à proposer ces modifications, je voudrais comprendre ce qui t'oblige à utiliser IE9, qui est démodé depuis 5 ans. Du côté de Libertempo, on ne peut pas supporter toutes les versions de tous les navigateurs et ça me pose un petit souci d'où ma question.

**Comment by ooBeNoo** [comment]
Bonsoir, il n'y a, à mon sens, pas de problème.
Mon employeur utilise IE9 sur les postes de travail (W7). Le déploiement de IE11 ou de FF/GC ne peut pas être envisagé pour différentes raisons. Il m'a été demandé de rendre Libertempo compatible IE9.
Je me suis rapproché de vous pour vous communiquer et vous proposer les modifications faites pour que vous puissiez (si vous le souhaitez) les intégrer dans vos futures releases.

Bien à vous

**Comment by wouldsmina** [comment]
la compatibilité avec ie a été partiellement amélioré sur Ceres. N'ayant pas eu l'occasion de tester correctement ces propositions, je reportes à la version suivante. 
L'idéal serait de proposer une PR...

**Comment by Prytoegrian** [comment]
Au vu de la nature du changement et de l'intérêt pour les autres utilisateurs, je pense qu'il est préférable que tu fasses un fork pour gérer tes particularités de ton côté.

Ce genre de code n'enlève aucun comportement aux autres utilisateurs je suis d'accord, mais : 
* ça officialise le support d'IE9 de notre part, chose que nous devrons maintenir dans le temps pour ne pas être injuste et faire ça selon nos envies,
* une partie du code de Libertempo est dédiée à de la compat' d'un logiciel obsolète, ça oblige tous les mainteneurs à se dire « ah oui, ce code ne doit pas être touché, c'est pour de la compat' » ; on ne saura jamais quand l'enlever.

J'aurais pas de souci à gérer des spécificités de certains navigateurs, si c'était voué à entrer dans un tronc commun, j'ai plus de mal pour la compatibilité descendante.
