### ISSUE TITLE
changement droit responsable : prise en compte partielle

### ISSUE THREAD

**Issue by VV666** [Libertempo/Libertempo-web#129]
Donner des droits RH et Grand Responsable à un utilisateur OK, mais lui enlever les droits ne fonctionne pas : dans Libertempo les droits ne sont plus présent, mais dans la base les droits sont toujours là.

**Comment by VV666** [comment]
Proposition de correction par Vincent : 
dans la base, 
DELETE FROM `conges_groupe_grd_resp`
WHERE CONVERT(`ggr_login`,CHAR(100))='USER_INCRIMINÉ')

**Comment by wouldsmina** [comment]
avant de retirer les droits responsable à l'utilisateur, est ce que tu lui retire ses groupes dans l'onglet "Gestion Responsables / Groupes"? 

Les droits RH n'agissent pas sur conges_groupe_grd_resp.

**Comment by wouldsmina** [comment]
ping @VV666.

**Comment by VV666** [comment]
Non, on ne l'a pas fait. Ça doit venir de ça je suppose. Donc pas un bug.

Par contre, il manque soit une doc, soit une alerte pour prévenir qu'il faut modifier les groupes avant, non ?
