### ISSUE TITLE
Passer sur un framework ?

### ISSUE THREAD

**Issue by pmietlicki** [Libertempo/Libertempo-web#134]
Bonjour,
A l'usage, j'avais trouvé php congés plein de bugs et le code assez `<mode diplomate>` illisible `</mode diplomate>` mais la critique est toujours facile.
Faudrait passer sur du MVC et je pense que de basculer le code dans un framework comme Laravel aiderait sur pas mal de choses (dont la sécurité avec les failles CSRF ou autres), ça serait un sacré plus.
C'est juste une suggestion car ça demanderait beaucoup de travail mais comme je vois qu'il y a une véritable initiative dans ce sens là, je soumets l'idée.
Bonne journée

**Comment by Prytoegrian** [comment]
Salut @pmietlicki,

tu as le droit de dire ce que tu penses, toutes les critiques (du moment qu'elles sont constructives et détaillées) sont bonnes à prendre.
Nous cherchons effectivement à faire améliorer la plateforme (nombre de tickets / PR présente ce fait) mais comme tu t'en doutes, ça demande du temps. Dans un monde idéal, on pourrait faire table rase et reprendre le code from scratch  mais ça ne fonctionne pas comme ça, nous avons des utilisateurs à satisfaire à chaque version. Donc on va devoir y aller petit à petit, entre les corrections de bugs et les fonctionnalités deci-delà.

À titre personnel, je ne suis pas fan des frameworks parce qu'ils t'enferment dans la manière de penser des devs dudit framework et c'est pas souvent des bons choix (le SOLID est souvent passé aux oubliettes, et la gestion des modèles est pas à mon goût).
Alors oui, tu ne réinventes pas la roue et va plus vite dans la migration, mais tu n'apprends rien, ne comprends pas profondément le code et ça devient vite un handicap. Mais ça reste mon avis, je suis ouvert à la discussion.
On s'est plus ou moins arrêté sur le framework [Slim](http://www.slimframework.com/) qui gère peu de choses mais le fait bien : 
- le routage
- l'objet de requête
- l'objet de réponse

Charge à nous d'implémenter à notre convenance l'archi MVC REST et d'y appliquer le métier aux petits oignons.

Je vais finir par radoter (^^) mais toutes les contributions sont bonnes à prendre, ne fusse qu'à rapporter / corriger des bugs, donner son avis lors des conversations ou tester les versions. À deux ça va forcément pas vite :s

**Comment by pmietlicki** [comment]
Salut @Prytoegrian,

Merci pour la réponse. 
Je comprends vos contraintes et je partage ton point de vue concernant les frameworks mais, sans faire de placement de produit, Laravel m'a agréablement surpris. Je salue donc votre initiative de partir sur un micro framework, celui de Laravel s'appelle Lumen, il parait qu'il est très bien. Mais Slim semble [s'y intéresser](http://www.slimframework.com/2015/04/14/lumen.html). Personnellement, je serais pus parti sur Lumen qui me semble plus fiable sur le long terme mais je deviens peut être groupie de Laravel, je ne veux donc pas rentrer dans des débats techniques qui seraient stériles, l'important étant l'initiative d'aller dans le sens de quelque chose de moderne, standardisé et ouvrant d'autres perspectives d'évolution.

Bonne continuation et merci pour cette initiative

**Comment by Prytoegrian** [comment]
Bien entendu on est assez loin de pouvoir utiliser un framework (cf #103), mais je vais voir si Lumen peut satisfaire nos besoins sans être trop contraignant et faire le comparo avec Slim.

Si t'as des arguments pour l'un ou l'autre, fais-toi plaisir, on en tiendra compte (les débats techniques sont rarement stériles ;-))

**Comment by pmietlicki** [comment]
Non pas d'arguments spécifiques, si ce n'est la pérennité du produit Lumen adossé à un framework en vogue (à priori pour longtemps) qu'est Laravel. La vitesse d'exécution plaide pour Lumen mais c'est sujet à caution. A priori, à l'usage, slim semble plus ergonomique mais, si vous envisagez, à terme, de passer sur un framework complet, Lumen offre une solution idéale et qui pourrait évoluer naturellement et plus facilement vers Laravel. Je ne connais pas suffisamment les deux pour faire une analyse comparative éclairée, je reste donc en surface par rapport à ce que j'ai vu par ci par là. 
Bonne journée et merci encore

**Comment by Prytoegrian** [comment]
La question est toute réglée (et ça fait plus d'un an sans échange), je ferme.
