### ISSUE TITLE
SUGGESTION sur les utilisateurs importés de  LDAP, sensibilité à la casse de u_login

### ISSUE THREAD

**Issue by SARTECHRUN** [Libertempo/Libertempo-web#195]
Bonjour, 

Lorsqu'on créé un utilisateur LDAP, le "login" (dans mon cas le SAMACCOUNT) est sensible à la CASSE.
J'ai modifié les tables  u_login   en varchar(99) afin que ce ne soit plus le cas ce qui génère d'autres problèmes que j'ai pu modifier. 
Ne pourrait-on pas créer une référence numérique par  USER qui serait récupérée par les tables conges_periodes et conges_soldes?

Merci d'avance pour votre réponse.

Cordialement,

**Comment by wouldsmina** [comment]
Re,
Pour les clés primaires en int, c'est dans la Roadmap #103 on fera le changement pour u_login  dans le même temps.
Cdlt.

**Comment by Prytoegrian** [comment]
Doublon #259 (je ferme ce dernier, il y a eu plus d'interactivité dans l'autre)
