### ISSUE TITLE
SUGGESTION: retrait de l'onglet "backup" pour un compte admin simple

### ISSUE THREAD

**Issue by benjoo** [Libertempo/Libertempo-web#198]
Bonjour,

Comme suggérer, j'ouvre un nouveau ticket.

Celui-ci est juste simple, l'option de pouvoir retirer l'onglet backup pour un compte admin simple (compte créer avec les droits admin) pour des questions de sécurité.

--------- bla bla qui replace juste dans le contexte ----------
La où j'effectue mon stage, je vais donner les droits admin à la RH pour qu'elle puisse ajouter les utilisateurs à partir de l'AD mais pour des questions de sécurité, laisser les droits du backup au compte Super Admin (ici pour le service informatique) seulement.

Voilà, si je trouve autre chose, je vous dis ça !

**Comment by Prytoegrian** [comment]
Très bonne idée. Nous (j'ai ?) pour projet de refondre le système de droits, il y a certaines choses que les  utilisateurs de l'appli ne devrait pas pouvoir voir / faire, ça donne de l'eau à mon moulin.

**Comment by wouldsmina** [comment]
je confirme le "Nous"; en effet, la gestion des droits est aussi à revoir...

**Comment by wouldsmina** [comment]
corrigé par #542
