### ISSUE TITLE
Reponsable et déconnexion sur certains comptes

### ISSUE THREAD

**Issue by Shadok** [Libertempo/Libertempo-web#218]
J'ai un compte qui est "responsable, RH, voit tout".

Sur la page responsable, il voit des utilisateurs dont il n'est pas responsable (mais il est responsable du groupe auquel appartient le responsable de ces utilisateurs).
Par contre, il ne voit pas tous les utilisateurs dont il n'est pas responsable, mais seulement ceux liés à des responsables dont il est responsable.

Quand je clique sur l'icône d’œil, pour visualiser ces utilisateurs, je me retrouve sur la page de login.
Sauf que ce n'est pas une vrai déconnexion, juste une redirection, car si je reviens en arrière, je peux encore naviguer.

Vous suivez toujours ?
Voici un schéma.

Je suis connecté sous "Utilisateur 1".
Sur la page responsable, je vois les utilisateurs 2 à 10. Mais pas les utilisateurs 11 à 13.

Je ne suis pas responsable des utilisateurs 8 à 10, donc je ne devrais pas les voir dans ce mode.
Utilisateur 5, est responsable du groupe contenant les utilisateurs 8 à 10.
Je suis responsable du groupe auquel appartient l'utilisateur 5.

Je ne suis ni responsable des utilisateurs 11 à 13, ni responsable de leur responsable, dont je ne les vois pas.

Si je cherche à visualiser les utilisateurs 8 à 10, je me retrouve sur la page de login.
Par contre, si je passe sur la page RH, je vois bien tout le monde, et je n'ai pas de problème de visualisation.

**Comment by wouldsmina** [comment]
Salut,

On est conscient de ces problèmes, ce sera revu dans une futur version...

Tu te fais déconnecté parce que tu n'es pas responsable direct de l'utilisateur (ça aussi ce sera revu)...

A+

**Comment by Shadok** [comment]
C'est bien ce qu'il me semblait.
Mais normalement, on ne devrait pas voir, sur la page responsable, ceux dont on est pas directement responsable.
Et ce n'est pas le critère "voit tout" qui est en cause, vu qu'il ne voit justement pas tous les utilisateurs.

**Comment by wouldsmina** [comment]
à terme, seul la gestion des groupes permettra de paramétrer les responsables. Il n'y aura plus de paramétrage du responsable dans la création/modif de l'utilisateur...

**Comment by Prytoegrian** [comment]
Un petit ticket pour ce sujet ?

Histoire de : 
* battre le fer tant qu'il est chaud
* récolter des idées d'utilisateur de l'appli
* ne pas laisser ce début de conversation pourrir dans les limbes de github

**Comment by wouldsmina** [comment]
c'est fait.

**Comment by Shadok** [comment]
J'y vais de ce pas.

**Comment by wouldsmina** [comment]
la correction de ce bug est prévu dans #219.
