### ISSUE TITLE
Fixer le sql mode des connexions SQL

### ISSUE THREAD

**Issue by Prytoegrian** [Libertempo/Libertempo-web#235]
Suite au bug #186 et la tentative de résolution #209 et sur les conseils avisés d'un sempai, je propose que nous forcions le sql-mode de mysql lors de l'installation et de l'utilisation de tous les jours.
La diversité des configurations des différents serveurs associés à l'application nous met face à des possibles embûches et des bugs sournois.

Cela ne doit pas nous permettre d'avoir des configurations laxistes ; mais au moins on aura une configuration fixée au sein du parc client.

**Comment by wouldsmina** [comment]
Peux t on forcer le mode sql depuis php? sinon, ça se passe dans le fichier de configuration de mysql, on ne pourra que le spécifier dans les pré-requis...

**Comment by Prytoegrian** [comment]
> Peux t on forcer le mode sql depuis php

Oui, tu peux changer le sql mode au runtime via : 
```sh
SET GLOBAL sql_mode = 'modes';
SET SESSION sql_mode = 'modes';
```
Dans notre cas on doit se limiter à `session`
