### ISSUE TITLE
Calendrier vue annuelle

### ISSUE THREAD

**Issue by stillcut** [Libertempo/Libertempo-web#240]
[Amelioration]
Bonjour,
Serait il possible d'intégrer une vue annuelle, en plus de la vue mensuelle, pour le calendrier ?
Ce serait pratique. En particulier pour visualiser les congés pris sur deux mois contigus.

**Comment by Prytoegrian** [comment]
Salut !

Que voudrais-tu voir exactement, peux-tu me donner un cas précis ?

Une vue annuelle serait trop illisible à mon sens mais ça ne remet pas en cause le besoin, il faut juste trouver une meilleur approche. Une PR est en cours afin de donner au calendrier une meilleure ergonomie. Selon ta réponse, ça pourrait déjà être dans les cartons :smile:

**Comment by stillcut** [comment]
Bonjour,

Effectivement, une vue annuelle pourrait etre illisible.
L'inconvénient d'une vue mensuelle est que dans le cas ou un utilisateurs pose par exemple la semaine 48, celle-ci est à cheval sur novembre et décembre.
Auquel cas le responsable ne dispose pas d"une visualisation idéale de la présence de son équipesur la semaine 48, il est obligé d'aller chercher le mois suivant.

**Comment by wouldsmina** [comment]
Salut,
La prochaine version intégrera un nouveau calendrier avec une vue mensuelle et une autre hebdomadaire. Je pense que ça devra te convenir...

**Comment by Prytoegrian** [comment]
Je te mets des screens dès que j'ai un moment, pour que tu te fasses un avis (mais pour te donner une idée, ça ressemble à Google calendar).

**Comment by wouldsmina** [comment]
corrigé par #562
