### ISSUE TITLE
[DA] Intégration des congés dans calendrier

### ISSUE THREAD

**Issue by lordystyle** [Libertempo/Libertempo-web#246]
[Demande d'amélioration] Bonjour,

Serait il possible dans les prochaines moutures de prévoir la génération d'un fichier .ics d'import du congés dans nos agendas ?

Soit à travers le mail de validation 
"Vos congés ont été validés ...
....
Vous trouverez le fichier joint vous permettant de les importer dans votre base courrier"

Soit via l'historique des congés avec un petit bouton calendrier qui générerait un fichier .ics pour import dans calendrier.

Poser des congés c'est bien mais l'avoir dans l'agenda partagé de la société c'est encore mieux ^^

Merci

**Comment by lordystyle** [comment]
Merci Wouldsmina, 
Le format ical n'est malheureusement pas compatible avec notre système lotus note IBM.
Sinon je n'avais pas vu l'option mais c'est très bien. Cela dit ce bouton récupère tous les jours de congés/absence de l'utilisateur ? Si certains sont déjà intégrés dans l'agenda que se passe t'il (écrasement ? en double) ?
Si il les met en double il faudrait plutôt prévoir un export par congés?

**Comment by wouldsmina** [comment]
> Si certains sont déjà intégrés dans l'agenda que se passe t'il (écrasement ? en double) ?

Justement, l'idée c'est de ne pas intégrer manuellement des congés dans un agenda, mais les avoirs en temps réel par l'intermédiaire d'un lien...

> Le format ical n'est malheureusement pas compatible avec notre système lotus note IBM.

Quel format te faut il?

**Comment by wouldsmina** [comment]
ping @lordystyle

**Comment by wouldsmina** [comment]
pas de news...

**Comment by lordystyle** [comment]
Je suis absent(e) du bureau jusqu'au 26/03/2018

Je répondrai à votre message dès mon retour.


Remarque : ceci est une réponse automatique à votre message  "Re:
[Libertempo/Libertempo-web] [DA] Intégration des congés dans calendrier
(#246)" envoyé le 24/03/2018 00:53:04.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.
