### ISSUE TITLE
changer le pas de 0.5 à 0.25

### ISSUE THREAD

**Issue by lacausse** [Libertempo/Libertempo-web#260]
Bonjour,

J'aimerais savoir si il y a possibilité d'avoir un pas de 0.25 au lieu de 0.5 pour l'ajout de congés ?

Merci

**Comment by Prytoegrian** [comment]
Hello,

que cherches-tu à faire  ?

**Comment by lacausse** [comment]
Dans notre entreprise, on a des astreintes correspondant à des 1/4 de jours, j'aimerais donc pouvoir rajouter des récups par 0.25 jour. 
Par contre, cela ne change rien au niveau de la prise de ces récups qui ne peuvent se faire que par 1/2 journée.

**Comment by Prytoegrian** [comment]
Ok. Les CP et RTT (et sûrement le reste, je n'ai pas vérifié) ne peuvent pas être pris sous une granularité inférieure à la demi-journée, c'est la loi française. C'est pour cette raison que nous avons lancé le chantier des heures additionnelles et de repos, précisément pour faire ce que tu demandes. Nous avons eu énormément de nouvelles choses à coder pour y arriver, donc ça prend du retard, mais c'est la fonctionnalité phare de la version 1.9.

**Comment by wouldsmina** [comment]
@lacausse est ce que la gestion des heures additionnelles/repos conviendrait à tes besoins?

**Comment by lacausse** [comment]
Je confirme que l'on ne peut prendre que par granularité de 0.5 jours. Par contre l'accumulation de ce temps peut se faire par une granularité différente. Par exemple 0.25 jours.
Si il reste 0.25 jour, on ne peut pas l'utiliser. Il faut attendre d'avoir un autre 0.25 pour pouvoir l'utiliser.

En ce qui concerne la gestion des heures additionnelles/repos, il faut que je teste afin de voir si c'est ok pour nous. 

Avez vous une estimation pour une sortie de la 1.9 ?

**Comment by Prytoegrian** [comment]
C'est toujours difficile de donner un délai en dev, mais vu ce qu'il nous reste tu peux tabler sur janvier 2017.

À partir de la 1.10 nous allons mettre en place des cycles différents, plus fréquents et plus atomiques.

**Comment by augras** [comment]
Je viens de prendre connaissance de ce fil que je n'avais pas consulté compte-tenu de son intitulé mais le contenu est très intéressant.
J'ai posté sur l'adresse  libertempo@lists.tuxfamily.org à propos des heures supp/récup et là j'apprends que cela sera géré dans la prochaine version : SUPER ! Cela sera géré jusqu'à quel point ? Je poste ici mon message ou j'ouvre un nouveau fil ?
Et j'apprends ici que la version 1.10 gèrera différents cycles : c'est une fonctionnalité vraiment intéressante que j'avais vu dans une autre appli qui gérait différents "contrats" ; en fonction du cycle rtt par exemple  l'agent se voit créditer le nombre de jours de congés et de rtt correspondants. Est-ce que c'est bien de cela qu'il s'agit ?
Merci,
Philippe

**Comment by Prytoegrian** [comment]
Bonjour Philippe, 

d'après ce que je comprends de tes mots, on dirait que tu n'as pas reçu ma réponse suite à ton mail sur la mailing-list. Après vérification, mon mail a bien été envoyé et reçu par certains autres abonnés à la liste, donc je t'invite à vérifier que tu n'aies pas la réponse dans tes spams. Je ne vais faire que paraphraser mon mail donc je te laisse le lire et me dire s'il y a un point où je n'ai pas été clair.

Pour ce qui est des cycles, il ne faut pas le voir comme des périodes de temps formelles qui donnerait la validité des sorties : de mai à mai pour les CP / de janvier à janvier pour les RTT ; ça c'est le ticket https://github.com/wouldsmina/Libertempo/issues/66 qui en parle. Si le sujet t'intéresse, je te laisse intervenir.

Non, ce que je voulais vraiment dire par « cycles », c'est le rythme de sortie des versions du logiciel. Nous avons un cycle de sortie trop lent pour être efficace et réactif et dès la prochaine version nous livrerons plus souvent de plus petites choses :-)

**Comment by augras** [comment]
Bonjour Prytoegrian,
Effectivement, rien reçu ! Je viens de vérifier les spams, la corbeille et ma boite de réception... et rien ! Tu peux me le renvoyer ?
Ce que j'évoquais en terme de contrat/cycle ne recouvre pas le ticket 66 : je n'ai pas pensé à ce que recouvre le ticket 66 car contractuel dans la fonction publique tout est géré sur l'année civile. Mais dans le privé le ticket 66 a effectivement une grande importance. Par contre privé comme publique les RTT ne se reporte pas d'une année sur l'autre. Ce que j'évoque correspond plus a une sorte de profil type : autant de profil que de cas de figure et quand on enregistre un utilisateur on lui attribue un profil qui lui applique automatiquement le nombre de CP/RTT, les jours de fermeture.... (par défaut ces jours de fermeture seraient ceux définis globalement) : ça évite de saisir tout ça manuellement et si modification et bien il y a juste à modifier le profil.
Donc pour les cycles à partir de la 1.10 effectivement confusion complète !
Philippe

**Comment by Prytoegrian** [comment]
Exceptionnellement, je me permets de te l'envoyer sur ton mail perso pour ne pas imposer le même mail aux autres abonnés de la Mailing List. Hésite pas à répondre, mais sur les échanges de la mailing list pour ne pas faire de trucs en sous-marin.

**Comment by wouldsmina** [comment]
pareil que #289. J'espère que les heures conviennent
