### ISSUE TITLE
Générer via script des données de test 

### ISSUE THREAD

**Issue by Prytoegrian** [Libertempo/Libertempo-web#280]
Comme #264 le montre, nous avons besoin de données de test régulièrement. 
En effet, je m'aperçois lorsque je teste / dev que je fais toujours les mêmes manipulations pour monter une instance de travail. 

En conséquence, je propose la création de données de test, a minima d'utilisateurs et quelques congés. Il n'y a pas besoin d'être exhaustif sur tous les plans de l'application, on fera au besoin.

**Comment by wouldsmina** [comment]
on a docs/jeutest.sql. Par contre il faut integrer les modifications qu'a subi la bdd...

**Comment by Prytoegrian** [comment]
OK donc on aura besoin de deux scripts :
- Le premier pour monter les données en base
- le second pour les exporter, avec un nouveau schema

Je pense qu'il serait opportun de les stocker dans le code pour avoir le même jeu de test partout. Vu la nature, certainement dans Tests\Fixtures. 

Histoire d'organiser tout ça simplement, un petit makefile peut faire le job. Ça pourrait peut être même nous entraîner pour #205.

**Comment by Prytoegrian** [comment]
* Il nous faut aussi la possibilité d'avoir des DB de toutes les versions que nous supportons, afin de pouvoir tester la montée en version. Dans l'idéal, ces schémas devraient être remplis de données, évidemment.

Après, il est possible que #174 permette de décorréler les montées en version de la DB et du code, donc que peu de DB soient nécessaires, finalement.

**Comment by tneullas** [comment]
Je fais remonter ce thread car je pense que ça serait important d'avoir un jeu de test dans le même genre que doc/jeutest.sql mais avec beaucoup + d'utilisateurs, de congés et de traitement de congés.
Le but est d'avoir une vision de comment LT réagi dans une situation réelle de grande entreprise.
Le but est de mettre en avant les éventuelles problèmes d'ergonomie et de performance.

Ce jeu de test pourrait être actualisé a chaque version de LT afin de pouvoir tester les différentes versions et upgrade.

**Comment by Prytoegrian** [comment]
Bien vu. Mon besoin initial est d'avoir une base minimale d'utilisateur pour bosser, et charge au dev ensuite de faire interagir ces utilisateurs. Le besoin (et l'idée !) dont tu parles est intéressant, et du coup je verrais bien un script paramétrable qui permettrait de choisir le nombre d'éléments dans chacune des dimensions : 
* utilisateurs,
* sorties (congés, rtt, …) à différents statuts,
* …

**Comment by wouldsmina** [comment]
- l'année. Pour avoir des congés toujours frais :p

**Comment by Prytoegrian** [comment]
Ça je pense c'est à la charge du script d'avoir des données de simulation qui se décalent automagiquement

**Comment by tneullas** [comment]
Pour le dernier point on peut faire en SQL des INSERT en utilisant la fonction NOW() plutôt qu'en donnant une date précise (qui sera vite dépassé)
Avec cette fonction on devrait arriver à faire des NOW()-7jours et NOW+1 mois par exemple pour des congès passés ou des demandes de congés.
