### ISSUE TITLE
Compatibilité Libertempo avec IE 11

### ISSUE THREAD

**Issue by Skyzeun** [Libertempo/Libertempo-web#298]
Bonjour,

Je voulais savoir si Libertempo peut être compatible avec IE 11. En effet lorsque je me connecte sur Mozilla je n'ai aucun problèmes en revanche sur IE 11 je constate que certaines cases ne sont pas présentes.. Faut t'il modifié certains fichiers comme ce que j'ai pu voir pour IE 9 ou cela reste encore impossible pour le moment?

**Comment by wouldsmina** [comment]
Non, pour le moment, il n'est pas compatible avec IE.

**Comment by Prytoegrian** [comment]
Salut,

explique-nous plus en détail ce que tu es censé voir, et si tu as des erreurs particulières dans la console du navigateur.

**Comment by Prytoegrian** [comment]
En attente depuis 1 an.
