### ISSUE TITLE
Répartir les dépots dans les bons projets

### ISSUE THREAD

**Issue by Prytoegrian** [Libertempo/Libertempo-web#304]
Nous travaillons en permanence et en parallèle sur de multiples logiciels pour que l'application Libertempo tourne. Le problème pour le moment est que chacun de ces logiciels ne sont pas officiellement regroupés sous une bannière unique et cela rend difficile la visibilité et le travail synchrone, en plus d'être peu pratique pour les utilisateurs. 
Je propose donc que nous regroupions tous les logiciels sous une organisation. Il s'agit des logiciels : 
* [x] libertempo-docker
* [x] libertempo api
* [x] libertempo (ou libertempo-web)

**Comment by wouldsmina** [comment]
+1 pour libertempo-web
