### ISSUE TITLE
Liste des congés de l'utilisateur

### ISSUE THREAD

**Issue by tneullas** [Libertempo/Libertempo-web#322]
Testé sur LT 1.9 Ceres

Par défaut l'interface propose de lister ses congés en recherchant parmis les statuts et le type de congés et l'année ce qui n'est vraiment pas intuitif.
Par exemple j'avais pris un CP et je ne le voyais pas. Après avoir cru à un bug j'ai compris qu'il fallait que je cherche son état mais j'avais aucune idée donc je les ai tous parcouru un par un puis en recliquant sur la petite loupe pour que la recherche se relance.
Ca fait beaucoup de clic pour avoir une information très simple.

Je propose d'ajouter un champ "Tous les status" et un champ "Tous les types de congés" en haut.
Ces champs seront activés par défaut.
Avec cela l'utilisateur voit directement tous ses congés (triès dans l'ordre de la nouvelle à la plus ancienne pour + de lisibilité)
Il peut aussi avec ce système faire des recherches comme "Je veux voir toutes les demandes en attente peut importe le type de congés"

Vis à vis de l'année je ne sais pas si c'est utile d'avoir un champ "Toutes les années". Je pense que par défaut cela doit rester comme c'est actuellement c'est à dire sur l'année en cours.

**Comment by Prytoegrian** [comment]
En effet tu as raison. Les heures ont aussi cette apparence là. Coté code ça peut se traduire simplement par une option virtuelle comme on l'a déjà fait ailleurs.
