### ISSUE TITLE
Mettre la page liste des congés par défaut pour l'utilisateur

### ISSUE THREAD

**Issue by tneullas** [Libertempo/Libertempo-web#323]
Suggestion pour la 1.9 Ceres

Je pense qu'il faudrait mettre par défaut la page liste des congés en index de la page utilisateur, et la page demande de congés en second onglet.
1) On va plus souvent venir voir nos congés plutôt qu'en prendre, ça permet aussi de vérifier qu'on les as pas déjà pris
2) C'est plus cohérent avec les interfaces de responsable et de RH ou c'est déjà dans cet ordre là

C'est bien en terme d'ergonomie de voir puis d'agir d'où cette suggestion.

Wouldsmina dit que ça pourrait rentrer dans le cadre du Dashboard ce qui ne me parait pas être une mauvaise idée.

**Comment by wouldsmina** [comment]
ouaip! dans ce cas je propose de changer le titre de ce ticket pour : Mettre un Dashboard en page principale de l'utilisateur.
Maintenant, il faut définir ce que va contenir ce dashboard...

**Comment by Prytoegrian** [comment]
Je lis plusieurs choses en même temps là : 
- dashboard
- ergonomie fonctionnelle
- workflow

À mon sens, le futur dashboard servira à regrouper toutes les infos utiles du moment pour l'employé, quelques soit son rôle. En gros toutes les notifs du cycle de vie d'une appli de gestion de congés, à voir en un coup d'œil. Si le besoin est de suivre un workflow particulier, je ne suis pas sûr qu'on soit sur la solution.

Par contre, il y a quelques mois j'avais commencé des essais de templates pour qu'on ai une vue en silo des contextes de l'appli : on cherche à regarder les congés, donc on va consulter la liste. Cette liste nous amène vers un détail pour avoir plus d'infos. Toujours partant de la liste, on peut « Effectuer une demande », etc. L'essentiel étant de suivre le principe de moindre surprise ergonomique en évitant l'éparpillement.

Ce genre de proposition irait ?

**Comment by tneullas** [comment]
Je suis d'accord que le dashboard doit servir à afficher toutes les infos utiles.
Je ne suis pas sûr qu'on aurait beaucoup de choses à afficher cela dit.

Moi je pense que le système actuel suffit et pourrait être couplé à un système de notification pour indiquer ce qui s'est passé depuis la dernière connexion.

Pryto, actuellement la liste est l'élement d'accueil de l'admin, du responsable, du rh mais pas de l'utilisateur d'où l'issue.
Le dashboard n'était qu'une piste qui je pense devrait être étudié pour une prochaine version.

**Comment by wouldsmina** [comment]
ok, je vous suis...

> Toujours partant de la liste, on peut « Effectuer une demande »,

+1
