### ISSUE TITLE
Utilisateur inactif

### ISSUE THREAD

**Issue by tneullas** [Libertempo/Libertempo-web#347]
## Ce topic a pour but de rassembler les cas d'utilisation d'un utilisateur inactif.
_Un utilisateur inactif a pour but d'être désactivé tout en étant gardé dans la base._

Il y a pas mal de travail qui a déjà été fait, les comptes inactifs sont déjà gérés dans la BDD et dans pas mal de pages.

### "Que peut faire un utilisateur inactif ?"
1) Soit il ne peut pas se login, on lui indique que son compte est inactivé
2) Soit il peut se login, on lui indique que son compte est inactivé et on lui permet d'envoyer un message à son RH pour demander une réactivation
3) Soit il peut se login entant que simple utilisateur, on lui indique que son compte est inactivé mais il peut continuer de faire quelques actions:
- consulter la liste de ses congés
- consulter l'agenda
- impression de ses congés au format papier
- exporter son cal

Personnellement j'hésiterais entre 1. et 3.

### "Qui peut mettre un utilisateur comme inactif ?"
- admin
- RH (seulement si il en est responsable)

### "Comment affiche t'on les utilisateurs inactif ?"
Pour les pages gestion des groupes utilisateurs
Je pense qu'il faut grisé les utilisateurs inactif ou les afficher comme ça "prenom nom (inactif)"

Pour la page d'accueil de l'admin et du RH on peut ajouter une deuxième liste des utilisateurs inactifs et ajouter un signe distinctifs (grisé ou (inactif))

N'hésitez pas à faire des retours.

**Comment by wouldsmina** [comment]
> Que peut faire un utilisateur inactif ?

il ne peut pas se login, on lui indique que son compte est inactivé 

> Qui peut mettre un utilisateur comme inactif ?

L'admin a déjà cette possibilité, on laisse comme ça pour le moment

> Comment affiche t'on les utilisateurs inactif ?

Grisé a l'air intéressant mais on risquerait de s'y perdre si il y avait plus de désactivé que d'activé. Permettre de les afficher ou non directement depuis la liste serait pas mal mais cela nécessitera de reprendre tout le code...

au passage assure toi qu'un utilisateur désactivé n'est pas soumis : 
- au décompte lors d'une fermeture
-  au changement d'année
- à l'ajout de jour de congés pour tous ou par groupe par le responsable (je sais plus si le RH peut le faire)

en clair il faut faire en sorte que les comptes désactivés soient complètement figés.

**Comment by Prytoegrian** [comment]
Mergé.
