### ISSUE TITLE
Les groupes vides renvoient une erreur lors d'ajout de congés

### ISSUE THREAD

**Issue by tneullas** [Libertempo/Libertempo-web#352]
[Bug] lorsqu'un RH ajoute des congés à un groupe vide une erreur apparait

### Système et application

* Version de l'application : Ceres Beta
    
### Reproduction du bug

* Prérequis : Avoir un groupe vide et se logger en tant que RH
* Action de déclenchement : dans ajout de congés par groupe, choisir le groupe vide
* Résultat attendu : on s'attend à ce que ça nous indique que ça a fonctionné ou que le groupe soit vide
* Résultat constaté : une erreur sql 
SELECT u_login, u_quotite FROM conges_users WHERE u_login IN () ORDER BY u_login 

La correction de ce bug serait dans un premier temps de tester si la variable $list_users n'est pas vide.
Dans un second temps on peux réfléchir si on veut vraiment afficher un groupe d'utilisateur si il est vide. Car ça n'a pas de sens de prendre des congés pour aucun utilisateur.

**Comment by Prytoegrian** [comment]
Cf. #219
