### ISSUE TITLE
Badge - mise à jour du nombre de demandes à traiter

### ISSUE THREAD

**Issue by tneullas** [Libertempo/Libertempo-web#357]
[Bug] Pour nous aider à corriger le bug dans les meilleures conditions, merci de prendre le temps de détailler ces quelques points

* Version de l'application : 1.9 Ceres
    
### Reproduction du bug

* Prérequis : Avoir créer une demande chez un utilisateur puis se connecter en tant que responsable
* Action de déclenchement : traiter une demande
* Résultat attendu : On s'attend à ce que le nombre de badge soit recalculé
* Résultat constaté : Il ne l'est pas (mais seulement après avoir rafraichi une nouvelle fois la page)

Le bug vient du fait de l'ordre d'exécution
1) Actualisation de la page 
2) Calcul du nombre de demande
3) Affichage du formulaire ou Traitement du formulaire (donc diminution du nombre de demande)

Pour résoudre ce bug on peut envisage plusieurs solutions.
a. la fainéante : on attend la v2 où la requête sur le model sera faite avant d'envoyer les paramètres à la vue.
b. l'audacieuse : on crée une page invisible appeler après validation du formulaire.
Cette page traite le formulaire et actualise la bdd puis redirige vers la première page où tout sera affiché correctement.

**Comment by wouldsmina** [comment]
On est conscient du problème et on avait déjà fait le choix 'a', non pas par fainéantise mais pour ne pas se lancer dans une usine à gaz (b) qui au final compliquerait encore un peu plus le code actuel (déjà bien alambiqué).

**Comment by Prytoegrian** [comment]
Que fait-on de ce ticket ?

**Comment by tneullas** [comment]
Vu qu'on part du principe que ça sera corriger avec le front en JS je peux le fermer où on peut lui mettre la milestone de la version 2

**Comment by wouldsmina** [comment]
ce sera corrigé naturellement par la conception même de l'API, on peut donc fermer...
