### ISSUE TITLE
Responsables croisés / boucle infinie

### ISSUE THREAD

**Issue by lchanouha** [Libertempo/Libertempo-web#367]
Bonjour,

Lorsque la chaîne de responsable contient une boucle (A est responsable de B et B est responsable de A), il y a (au moins) une boucle infinie, rendant (au moins) la demande de congés impossible pour les utilisateurs dans la chaîne de responsabilité de A ou B.
Il faudrait empêcher de faire ce type d'affectation, ou bien protéger le code de la fonction get_tab_respo_du_user dans fonctions_conges.php:

```
$new_tab_resp=array();
foreach ($tab_resp as $current_resp => $presence)
{
     // attention ,on evite le cas ou le user est son propre resp (sinon on boucle infiniment)
     if($current_resp != $user_login)
         $new_tab_resp = array_merge  ( $new_tab_resp , get_tab_resp_du_user($current_resp));
     }
}
``

**Comment by wouldsmina** [comment]
Bonjour,

Cette règle est en cours de développement avec la refonte de la gestion des groupes (#219).

Merci.
