### ISSUE TITLE
Supprimer les choix de langue

### ISSUE THREAD

**Issue by Prytoegrian** [Libertempo/Libertempo-web#371]
Puisqu'on a acté depuis 1.9 Ceres le fait qu'on ne pourra pas supporter toutes les règles de tous les pays, je propose qu'on supprime tout bonnement l'option de choix de langue.
Il y a plusieurs manières de faire les choses, de la plus facile / rapide à la plus complète ; je n'ai pas de préférence.

RFC donc !

**Comment by wouldsmina** [comment]
Je propose, dans un premier temps, de garder gettext et de simplement supprimer les autres langues et forcer systématiquement `FR_fr`. Dans un second temps, nous nous débarrasserons de toutes les références gettext...

**Comment by tneullas** [comment]
C'est une bonne idée, a termes se débarasser des fichiers .mo binaire sera une bonne chose pour la résolution de conflit git.
En essayant de résumer les tâches :
- Forcer la langue FR lors de l'installation
- Forcer la langue FR lors de la connexion
- Supprimer l'option de langue dans la BDD
- Remplacez les gettext par les textes correspondant
- Configurez les librairies JS et PHP en français (calendar, datepicker, mailer...)

J'oublie des choses ?

**Comment by Prytoegrian** [comment]
J'ai du temps, je me mets là dessus entre deux trucs. Je suis d'accord avec tout ce qui a été dit,  par contre, j'ai besoin d'une stratégie pour les instances existantes. Est-ce-que je fixe la langue pour tous les clients pour migrer en une version ou fais-je les choses pas à pas, à verrouiller le choix de langue **puis** forcer la langue à FR le moment venu ?
Je pense notamment à tous nos clients qui n'utilisent pas LT en FR, je voudrais faire la migration la plus douce possible.

**Comment by Prytoegrian** [comment]
## Plan de bataille 

Je pars là dessus : 
1. Nous fixons la langue à sa valeur actuelle, quelle qu'elle soit
2. Forcer la langue « FR » en (re)communicant bien sur l'orientation du logiciel
3. [Profit](https://www.youtube.com/watch?v=tO5sxLapAts)


Oui / Non / Zbradaradjan ?

**Comment by wouldsmina** [comment]
ok, alors où se trouve l'oiseau ? :smile: 

ça me va, c'est comme ça que je le voyais
