### ISSUE TITLE
Apparence du Calendrier

### ISSUE THREAD

**Issue by aradrim49** [Libertempo/Libertempo-web#374]
Bonjour, 

Nous avons mis en place Libertempo dans notre entreprise d'Horticulture depuis quelques semaines. A notre grande surprise, il a été très bien accueillit par l'ensemble du personnel et nous tenons à vous féliciter et remercier pour tout votre travail. 

Actuellement en version Quinnis en prod et Ceres en pré-prod, nous regrettons l'apparence et la praticité de l'ancien calendrier qui permettait une visu simple, concentrée et efficace de l'ancien calendrier. 
En effet, nous fonctionnons par groupe/secteur. Un responsable pouvant voir rapidement les demandes de ses différents ouvriers et adapter les confirmations de congés suivant ses besoins pour une période.  
Serait-il possible d'avoir un visuel de calendrier se rapprochant de l'ancien ?

Merci et à très vite.

**Comment by wouldsmina** [comment]
Bonjour @aradrim49,

Heureux que notre produit vous plaise :)

Nous allons intégrer dans Kantra (1.10) une fonctionnalité permettant de voir rapidement les absents du jour #369 . Est ce que cela pourrait convenir à votre besoin?

**Comment by aradrim49** [comment]
Cette fonctionnalité est très intéressante mais nous avons besoin de voir :
en tant que RH : un calendrier avec l'ensemble du personnel et les disponibilités. 
en tant que responsable : un calendrier avec le personnel du groupe et les disponibilités.

La présentation de l'ancien calendrier répondait exactement à ce besoin. Nous avions, avant de passer sur Libertempo, une édition papier qui se présentait exactement comme l'ancien calendrier. 

Pensez-vous que c'est réalisable ? à vrai dire, notre service RH pourrait refuser de passer sur une nouvelle version à cause de cette nouvelle présentation. 

Allez, bon Dimanche en attendant :)

**Comment by wouldsmina** [comment]
Nous avons fait le choix de changer de format de calendrier afin de permettre la visualisation des heures.

> en tant que RH : un calendrier avec l'ensemble du personnel et les disponibilités.
> en tant que responsable : un calendrier avec le personnel du groupe et les disponibilités.

je ne suis pas sur de comprendre, il est toujours possible de consulter chaque groupe ou tout le monde
depuis le calendrier. Le responsable et le RH voient aussi les demandes en cours.
Peut être est ce le fait de ne plus avoir la liste de tout le personnel? ou alors que le calendrier ne soit plus imprimable?

**Comment by aradrim49** [comment]
Effectivement je comprends cette problématique avec l'ancien calendrier pour la visualisation des heures.

Le coté pratique était effectivement d'avoir une visu sur la liste de l'ensemble du personnel. 
Le responsable pouvant se dire que pour la semaine X, a assez de personnel et pouvant accorder une semaine de congés pour son employé en attente de validation.

Dans notre cas, un employé peut changer de groupe d'une semaine à l'autre et l'ancienne vue permettait aussi de voir qui est affecté au groupe.

Le coté imprimable avec tout le personnel était aussi un point très intéressant pour nous.

**Comment by Prytoegrian** [comment]
Salut @aradrim49,

je vois ton besoin comme un requête sur l'aide à la décision d'acception / refus de congés, je me trompe ?
Si c'est bien ça, je vais avoir besoin d'info complémentaires. Le responsable a-t-il besoin de savoir : 
* sur mon groupe, j'ai 4/10 de d'employés présents sur la période ?
* sur mon groupe, je n'ai que Tartampion, Michu et Bombur de sont présents sur la période ?

**Comment by lolito34** [comment]
Bonjour,

Même remarque concernant l'apparence du calendrier (même si l'idée du nouveau est excellente).

J'aurai personnellement une autre proposition: serait-il possible dans la config de permettre le choix d'affichage du calendrier ? à savoir entre l'ancien (quinnis) et le nouveau (ceres) ?

Merci

**Comment by aradrim49** [comment]
Hello,

En effet, c'est bien ça. Le responsable a besoin de savoir cette deuxieme option. 

> sur mon groupe, je n'ai que Tartampion, Michu et Bombur de présents sur la période ?

**Comment by Prytoegrian** [comment]
Ok. Pourquoi particulièrement cette option, les personnalités sont importantes ? Tu vas me trouver chiant, mais plus on a d'infos, plus notre prise de décision sera fiable et précise. J'ai quelques petites idées derrière la tête et j'ai besoin de les confronter.

---
@lolito34 Pas vraiment. Techniquement, le code de l'ancien calendrier n'existe plus, il faudra donc le refaire. Cela pose aussi un problème de maintenir deux fonctionnalités de front. Mais ce qui me concerne davantage, c'est le côté métier. À mon sens, vous proposer ça serait une démission de notre rôle d'éditeur de logiciel. En effet, ça signifierait que nous ne sommes pas capable de comprendre suffisamment vos besoins pour vous proposer une fonctionnalité (unique) qui correspond vraiment à vos attentes et les satisfait totalement

À la place, je vous propose que nous cernions ensemble vos besoins pour adapter la fonctionnalité existante, nous devrions pouvoir trouver le format parfait pour soutenir vos attentes.

**Comment by lolito34** [comment]
@Prytoegrian Merci pour le retour. Il n'y a pas de soucis, ce n'était qu'une suggestion. Sachant que le calendrier n'est pas notre priorité ce n'est pas trop grave, mais je rejoins aradrim49 sur l'avantage que l'on peut avoir avec une vue plus globale pour un responsable.

**Comment by aradrim49** [comment]
ça ne mange pas de pain d'avoir les 2 informations mais dans notre cas, connaitre les noms des présents est quelque chose d'important, ils n'ont pas forcement les mêmes qualifications et le responsable pourra alors avoir une meilleur visu de son équipe. 
J’espère que ça s’éclaircit pour toi :)

**Comment by Prytoegrian** [comment]
Ok, je saisis. J'ai plusieurs propositions : 
* la méthode simple et rapide : dans le calendrier, on représente pour chaque jour le « taux de présence ». Le but du calendrier est de notifier ce qu'il se passe sur le jour J, donc augmente l'information, potentiellement via une pastille de couleur,
* la méthode plus complète : lors du traitement des demandes, la page apporte davantage d'info pour aider à la décision. Un bloc présenterait la période demandée ainsi que les employés dont les congés ont déjà été acceptés sur celle-ci.

Elle ne sont pas mutuellement exclusive vu qu'elles ne portent pas la même info. À vous de me dire.
Ceci dit, il me semble avoir codé un outil dans les demandes qui permettrait de voir les absents sur la période demandée par l'employé ; je me trompe @wouldsmina ?

**Comment by aradrim49** [comment]
La deuxième méthode répond bien à notre problématique, bien vu ! 
Et je dois dire que la première serait un + quand même pour un aperçu rapide du taux de présence mais non obligatoire dans notre cas.

**Comment by wouldsmina** [comment]
Je confirme, il est possible depuis la page de traitement des demandes d'accéder au calendrier sur la bonne période...

**Comment by wouldsmina** [comment]
Donc, si je comprend bien l'idée. On aurai accès à l'information sans devoir passer par le calendrier. c'est ça? l'idée est intéressante, mais je me demande sous quel forme cela se pourrait présenter sans que ça ne prenne trop de place et que ce soit facile et rapide a lire...

**Comment by clad63** [comment]
Une fonctionnalité que j'appréciais fortement sur la 1.8.1 était de pouvoir visualiser le calendrier sans authentification, j'ai intégré le lien dans notre intranet et mes collègues/dirigeants n'ont qu'à cliquer dessus pour ouvrir le calendrier du mois. Hors je ne trouve plus cette fonction avec la 1.9.
J'ai aussi un peu de mal avec le calendrier en hebdomadaire, qui me décale toutes les informations sur plusieurs lignes. Je vais refaire une install au cas ou un css aurait sauté.

**Comment by Prytoegrian** [comment]
@clad63 N'hésite pas à ouvrir un autre ticket la prochaine fois. Il s'agit d'un autre « problème » et on va se retrouver à ~~croiser les effluves~~ avoir deux conversations dans le même sujet. L'accès au calendrier sans authentification n'est plus possible. En plus des raisons évidentes de vie privée, nous avons mis en place des vues différentes pour les différents rôles de l'application ; s'il n'y a pas d'employé, nous ne savons pas quelle vue afficher.
S'il y a un bug d'affichage, créé-nous un rapport de bug, nous sommes encore en beta.

**Comment by lolito34** [comment]
@Prytoegrian Parmi tes propositions, la deuxième me parait la meilleure, mais la première est aussi intéressante.

**Comment by Prytoegrian** [comment]
@aradrim49 @lolito34 Ok. Après vérif, la deuxième proposition existe déjà sous la forme du petit calendrier dans la page de traitement. Je vous laisse regarder, tester la fonctionnalité et on fait un point dans quelques jours / semaines pour voir si ça vous va comme ça.

**Comment by LRCorwin** [comment]
Je m'inscrit dans la liste des sceptiques concernant ce nouvel affichage.
1/ Beaucoup de groupes impriment actuellement le calendrier mensuel pour affichage dans les couloirs et/ou pour diffusion pour que les utilisateurs sachent quand trouver untel ou untel,
2/ Si je suis ok pour dire que cette représentation améliore le côté "gestion des absences", elle ne rend plus le service "gestion des présences" qu'on avait en un coup d'oeil sur le précédent calendrier,
3/ pour les "gros" groupes (environ une vingtaine de personnes pour l'un des miens), si je regarde juillet/août, je suis obligé de scroller dans les fenêtres de chaque jour pour voir qui est absent, ce qui est gênant (comme le disait déjà quelqu'un plus haut) dans le cas de la gestion des compétences (bidule1 et bidule12 ne peuvent pas être absents en même temps, par exemple, alors que bidule3 et bidule18 le peuvent). En qualité de responsable, j'ai l'impression de perdre en clarté et en temps de décision.

Dans ce dernier cadre, une pastille donnant le taux (%) de présents/absents ne me dira pas si deux agents avec les mêmes compétences sollicitent un congé en même temps....

Je continue à regarder ça.

**Comment by Prytoegrian** [comment]
Je vois. Comment verriez-vous (tous) le calendrier des heures additionnelles et de repos ?

**Comment by clad63** [comment]
perso, mais je comprends bien que vue les modif de la base ce ne soit plus possible, j'aurais aimé un choix entre plusieurs calendriers, genre un hérité de la 1.8 avec utilisateurs en ligne et jours en colonne, et un autre basé sur celui de la 1.9 plus moderne mais paramétrable pour les couleurs et infos. 
et un mars et 15 euros avec ^^

**Comment by Prytoegrian** [comment]
J'entends bien @clad63, mais plus on fait de code et plus il faut le maintenir, en conséquence une petite idée comme la notre doit faire des choix. On essaie de trouver une apparence commune pour tous les types d'affichage ; elle n'existe pas forcément mais on creuse le sujet. C'est pour ça qu'on a besoin de savoir ce dont vous avez besoin pour l'affichage des heures add / repos :shipit:

**Comment by LRCorwin** [comment]
Hello

je vais avoir du mal à être objectif sur ce sujet car on utilise PhpCongés depuis la 1.5 en raison principalement de l'existence de ce fameux calendrier. Surtout, comme je le disais, dans l'approche "gestion des présences et des compétences".
Mon avis sera donc celui de @clad63 , dans l'expression du besoin.

Ensuite, si je comprends bien, tu souhaiterais qu'on se base sur le calendrierV1.9 et qu'on cherche à en améliorer le visuel ?
Est-ce que cela englobe l'attente d'une impression du calendrier ?

**Comment by Prytoegrian** [comment]
> Ensuite, si je comprends bien, tu souhaiterais qu'on se base sur le calendrierV1.9 et qu'on cherche à en améliorer le visuel ?

Pas forcément. On a entendu vos critiques, mais la solution technique de 1.9 est toujours valide compte tenu du fait qu'on ne sait pas comment afficher les heures. L'idée est de vous apporter une solution harmonieuse, visuellement et ergonomiquement. Tant qu'on a pas cerné vos besoins et vos idées sur ce sujet, on ne pourra rien trouver de mieux que ce que nous vous avons proposé.

> Est-ce que cela englobe l'attente d'une impression du calendrier ?

Ça pourrait oui.

**Comment by cezaropa** [comment]
Comme l'indique (LRCorwin commented on 6 Apr) dans son post, l'affichage actuel ne rend plus le même service que l'ancien. En ce qui nous concerne on ne passera pas à la v1.9 de ce seul fait là.
Dommage !
Je rejoins ceux qui proposent le choix d'un affichage au grès des besoins des utilisateurs. Plus de code certes, mais plus de personnes satisfaites dans les nombreux usages qui peuvent en être faits.
Cordialement

**Comment by Prytoegrian** [comment]
@cezaropa Nous avons repris le calendrier (https://github.com/Libertempo/Libertempo-web/pull/416) et sommes quasiment à la fin, pour une mise en beta de la `1.10 Kantra` avant la fin du mois si tout se passe bien.
Nous avons cherché à soutenir le besoin initial pour que vous ne perdiez rien et nous attendrons vos besoins au niveau des heures pour cerner l'apparence qui la satisferait au mieux.

**Comment by thibaudbillet** [comment]
Bonjour,
J'ai installé Libertempo aussi au boulot, et concernant le calendrier, même remarque! On m'a demandé si on pouvait avoir l'ancienne version! Je me demande si on ne pourrais pas prévoir une option dans la config qui permette de basculer sur l'ancienne ou la nouvelle version?
Les vacances approchant on me demande si j'aurai a dispo le calendrier, est ce que vous pensez livrer à temps ou faut il que je me penche sur une autre solution?
Les anciennes versions sont elles disponibles?
Merci en tout cas pour le boulot fait sur cette appli

**Comment by wouldsmina** [comment]
Bonjour,
La livraison de la prochaine version (avec le nouvel ancien calendrier #416 ) ne devrait pas tarder, si tu le souhaite, tu peux utiliser la version 1.8.1 qui intègre toujours l'ancien calendrier mais il n'est pas possible de rétrograder, donc si c'est déjà en prod, ça va pas être possible...

En ce qui concerne une option... non! il y a déjà trop d'option dans LT, certaines entre même en collisions avec d'autres, nous prévoyons plutôt d'en retirer à vrai dire.
