### ISSUE TITLE
[Question] : affectation de plannings

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#387]
Bonjour,

j'ai une poignée d'utilisateurs dont la case à cocher n'est pas active : je ne peux pas leur affecter un planning.
Quelqu'un a déjà eu/vu cela ?
Une raison, explication ?
Merci

**Comment by wouldsmina** [comment]
salut,

C'est soit parce qu'il a déja un planning d'affecté, soit parce qu'il y a des demandes non traités...

**Comment by LRCorwin** [comment]
bien vu !
J'ai validé les congés et effectivement on peut affecter les plannings.
Il faudra garder ça en tête au moment de la migration : pour bien, il faudrait même annuler les congés des utilisateurs pour ne pas avoir à les valider trop tôt...

**Comment by wouldsmina** [comment]
ouaip, mais ça c'est au responsable d'en décider ou alors il faut prévenir l'utilisateur de la raison de cette annulation. Je note ça dans un coin ;)
