### ISSUE TITLE
[Question] : congés sur samedi/dimanche alors que non travaillés

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#388]
Bonjour,

pour les utilisateurs ayant posés des congés cet été sur deux ou trois semaines, je vois leurs noms sur les samedi et dimanche alors que ce sont des jours non travaillés.

Est-ce voulu ?

Cela jette un certain trouble à l'affichage du calendrier mensuel...

Merci

**Comment by wouldsmina** [comment]
oui, c'est voulu pour mettre en avant la continuité...

**Comment by LRCorwin** [comment]
ok, mais c'est assez troublant : je crains que les utilisateurs ne posent pas mal de question, au moins au début, sur le "bon" décompte de jours.
Et à mon sens, le gros chambard sur le calendrier amène ( une fois encore, ce n'est qu'AMHA) une perte en lisibilité.
Les continuités sont déjà indiquées par des formes de flèches en marge droite.... A-t-on besoin d'avoir des noms dans les cases des journées non travaillées (we et jours fériés) ?

**Comment by Prytoegrian** [comment]
En effet, ça peut poser des questions. Je comprends l'idée mais je sais pas si on corrigera sous ce format, car on a entendu vos retours et on cherche la bonne solution pour l'affichage du calendrier, que ce soit pour les congés comme pour les heures.
