### ISSUE TITLE
Connexion Oauth

### ISSUE THREAD

**Issue by pdefert** [Libertempo/Libertempo-web#39]
Permettre l'authentification Oauth2 sur l'application
Avec des providers differents.

**Comment by wouldsmina** [comment]
Je suis pas contre, mais cette technologie ne permet pas d'importer des utilisateurs. Si?

**Comment by Prytoegrian** [comment]
Pour ma part, je cherche surtout à comprendre le besoin derrière. Comme @wouldsmina, fondamentalement je ne suis pas contre l'idée, mais ajouter une fonctionnalité n'est pas une chose anodine ; il faut la développer et la maintenir dans le temps. Il faut donc qu'elle soutienne un besoin précis pour pas qu'on se perde à vouloir tout faire. Je te laisse donc détailler ce que tu cherches à faire :-)

**Comment by pdefert** [comment]
l'idée est de permettre de se connecter avec un système SSO.  Oauth2  est le protocole choisit par les GAFAM . ce qui permettrai a de petite structure de gérer plus facilement les utilisateurs . j'entends, gestion du profil,  mots de passe, email,... .

l'objectif serait d’éviter d'avoir une n-eme base d'utilisateur avec d'autre mots de passe

**Comment by Prytoegrian** [comment]
Ok je saisis mieux. Par contre, étant une application… j'ai pas d'autres mots que « pro » – dans le sens où c'est pas des pseudos donc – comment se comporte ce système vis à vis des données personnelles ? Libertempo n'est pas juste un site où tu te connectes pour déposer un commentaire, j'ai quelques frilosités sans plus de données.
Je ne connais pas du tout ce système je t'avoue donc je préférerais avoir toutes les infos en poche avant d'avoir un avis tranché.

**Comment by pdefert** [comment]
je te rassure les données reste chez toi. C'est juste un système qui se charge de valider une authentification.Tu gardes ta table user.  le protocole te permet de récupérer quelques infos (mail , nom, prénom, photos, age,... enfin ce qu'il mets a disposition) de chez le provider. Mais le provider n'a pas accès a tes données.
Pour l'utilisateur il n'a qu'un password à retenir celui de son provider.

**Comment by wouldsmina** [comment]
Oui, ça fonctionne comme un CAS finalement. Mais je reste bloqué sur l'import des utilisateurs. 

Le CAS se base sur un annuaire LDAP, cela permet d'importer les utilisateurs avec LDAP sans risque de se tromper. Il est toujours possible de saisir le login à la main, mais le risque d'erreur de saisie est grand.

**Comment by bbalet** [comment]
Pourquoi cette insistance sur l'import des utilisateurs? Je crois que vous mélangez deux notions distinctes :
1. Fournisseur d'identité.
2. Référentiel des utilisateurs.

OAuth, SAML, etc. sont des protocoles pour vérifier l'identité d'un utilisateur cherchant à se connecter. En gros on délègue à un tiers la vérification du mot de passe (même s'il ne le ressaisit pas). En retour, le fournisseur renvoie une information propre à l'utilisateur. Par exemple, son adresse e-mail. Comme il est sensé être validé on vérifie que l'e-mail (ou un autre attribut unique) est dans la base de données de l'application. Certains voient la chose comme un *Password anti-pattern*, donc il faut vraiment avoir confiance dans ce tiers.

Si vous visez les ONG et les écoles, sachez que beaucoup d'entre elles utilisent Google for Schools, Google for Business, etc. Donc très intéressés par une authentification transparente par Google+. Facebook va lancer en 2016 un concurrent du RSE de Microsoft (Yammer).

**Comment by Prytoegrian** [comment]
Il n'y a pas eu d'avancement sur le sujet depuis plus d'un an, je ferme. S'il y a un vrai besoin, ça reviendra sur le tapis.
