### ISSUE TITLE
Enlever l' Affichage des groupes dans les calendriers des Utilisateurs (1.9Ceres) 

### ISSUE THREAD

**Issue by Pompelup** [Libertempo/Libertempo-web#391]
Bonjour,
J'aimerais savoir si l'affichage des groupes dans le calendrier pour les utilisateurs simple peut etre enlevé sur la version 1.9 Ceres.(BETA)
Cordialement

**Comment by wouldsmina** [comment]
Bonjour,

Non, cette option a été retiré, tout comme la possibilité ou non d'afficher le calendrier. Si il y a un besoin, n'hésite pas a nous en faire part...

**Comment by Lolaru84** [comment]
Idem comme Pompelup,
Le fait que les utilisateurs de groupes différents puissent visualiser quels sont les autres agents dans d'autres groupes en congés est gênant. de plus ayant un nombre assez élevé d'agent celà va polluer considérablement l'affichage sur certaines partie du planning.
Merci des possibilités trouvées

**Comment by Prytoegrian** [comment]
@Pompelup  Que cherches-tu à faire ? *Pourquoi* est toujours une question plus intéressante que *comment*.

Nous allons avoir besoin de plus de détails. Tels qu'ils ont été conçus, les groupes sont des *tribus* de gens qui travaillent dans un même domaine organisationnel. C'est pour cette raison que nous faisons en sorte que les personnes dans un groupe puissent voir les autres éléments de ce groupe. Après, il est possible de dire que personne ne voit les mouvements des voisins, ça ça pourrait avoir du sens.

Par contre, je tiens à souligner que nous avons entendu vos remarques et, compte tenu de votre utilisation du calendrier, le nouveau format n'est pas adapté. Nous allons revoir notre copie, en tendant vers l'apparence de 1.8-. Cela conviendrait-il à votre besoin ?

**Comment by Pompelup** [comment]
@Prytoegrian Bonjour,
Le but de cette démarche est à titre hiérarchique. L' utilisateur "simple" ne devrait pas voir les congés de leurs supérieurs et des autres services "groupe".
La fonction d'agenda pour les congés utilisateur doit rester visible aux yeux de sa hiérarchie: " droit RH , administrateur et  responsable.
Dans un but d'utiliser libertempo dans les administrations et entreprises n’oubliai pas que l'employé n'a pas de "droit" sur ses supérieurs.
Les fonctionnalités du 1.8 "visibilité calendrier utilisateur false ou true" était bien.
Cordialement

**Comment by Lolaru84** [comment]
Bonjour à tous,
 
Afin de contribuer dans l’avancée, je reformule ma remarque et explicite au mieux notre organisation.
 
J’espère ne pas être trop fouillis dans ma description.
 
Notre collectivité compte plusieurs services (33 actuellement mais ça bouge aussi).
Les agents ont des jours de congés payés CP pas de RTT
Les agents bénéficie de jours de fractionnement à la condition de poser un certain nombre de jours en dehors de la période estivale.
Les agents ont aussi des heures de récupération en fonction des heures supplémentaires effectuées
Plusieurs plannings différents en fonction du temps de travail (complet, partiel) mais aussi des horaires parfois atypiques
Le responsable valide les congés pour son groupe, peut-être y aura-t-il une double validation (à voir avec la DG)
 
Concernant les groupes, et le « pourquoi », tel que je vois la chose (mais je me trompe peut être) ils correspondent pour nos aux services. Ce qui est intéressant c’est que les mêmes membres d’un groupe puissent visualiser les absences des personnes de ce même groupe afin d’assurer la continuité de service (50% d’effectifs présent demandé dans notre cas mais cela reste à l’appréciation du responsable de service).
Ce qui est par contre gênant c’est que les membres d’un groupe puissent visualiser les absences des agents d’autres groupes.
De plus dans notre cas (450 agents) en période de fin d’année par exemple, nous sommes vraiment à 50% d’effectifs, je n’imagine pas ce que cela donne visuellement sur le planning si chaque agent voit les absences des autres.
 
Plusieurs possibilités se présentent donc :
1.       L’agent ne visualise que son planning
2.       L’agent ne visualise que le planning de son groupe (et le top serait de pouvoir avoir le choix entre son planning et celui du groupe)
3.       Pas de planning du tout (pour éviter les débats)
 
Avec des points particuliers tout de même concernant les responsables qui doivent eux pouvoir visualiser leur planning mais aussi le planning des groupes ou agents qu’ils managent.
Pour les doubles validations, eh ben là je ne sais pas…. J’ai peur que l’on retombe sur le scénario du « bordel » d’affichage, encore que non on peut filtrer au groupe donc pas de soucis je pense.
 
Espérant avoir été clair dans cette description.
 
Concernant la 1.8, je n’ai pas pratiqué, ce qui me gênerait ce serait de perdre en fonctionnalités, notamment dans la gestion des heures (ikl me semble que cela est introduit avec la 1.9)
 
Bien à vous
 
 
 
De : Prytoegrian [mailto:notifications@github.com] 
Envoyé : mardi 11 avril 2017 20:47
À : Libertempo/Libertempo-web
Cc : Lolaru84; Comment
Objet : Re: [Libertempo/Libertempo-web] Enlever l' Affichage des groupes dans les calendriers des Utilisateurs (1.9Ceres) (#391)
 
@Pompelup Que cherches-tu à faire ? Pourquoi est toujours une question plus intéressante que comment.
Nous allons avoir besoin de plus de détails. Tels qu'ils ont été conçus, les groupes sont des tribus de gens qui travaillent dans un même domaine organisationnel. C'est pour cette raison que nous faisons en sorte que les personnes dans un groupe puissent voir les autres éléments de ce groupe. Après, il est possible de dire que personne ne voit les mouvements des voisins, ça ça pourrait avoir du sens.
Par contre, je tiens à souligner que nous avons entendu vos remarques et, compte tenu de votre utilisation du calendrier, le nouveau format n'est pas adapté. Nous allons revoir notre copie, en tendant vers l'apparence de 1.8-. Cela conviendrait-il à votre besoin ?

**Comment by wouldsmina** [comment]
> L' utilisateur "simple" ne devrait pas voir les congés de leurs supérieurs et des autres services "groupe".

@Pompelup, d'après mon expérience il est important que l'employé puisse voir le planning de ses collègues et de son responsable afin d'une part d’être informé des absences des autres pour mieux s'organiser et d'autres part pour se décider à poser un congés (si tout le monde est déjà en congés un jour, il décidera peut être de reporter...). En ce qui concerne la visibilité des autres groupes, je ne suis pas contre l'idée de l'interdire tout simplement, sauf si certains y voit un intérêt, dans ce cas, qu'ils se manifestent :smile: 

Pour ce qui est de la consultation du planning individuel, il est possible : 
 - de consulter la liste des différents congés depuis les onglets
 - d'exporter le planning au format ics pour l’intégrer à un agenda 

Est ce que ces fonctionnalité ne suffisent pas?

@Lolaru84 nous sommes entrain de revoir le nouveau calendrier, beaucoup ont signifié le sentiment de perdre de l'information malgré qu'il soit plus aéré qu'avant. Nous prévoyons de revenir à un format sensiblement identique au précédent avec, en prime, la possibilité de consulter les heures de repos et additionnelles

**Comment by Prytoegrian** [comment]
Après réflexion, ça a sans doute du sens de ne pas autoriser un simple **employé** de voir les groupes auxquels il n'a pas accès.

Cf. #374

**Comment by LRCorwin** [comment]
Hello,

il semble que j'avais loupé ce fil.
En fait, j'appuie cette demande et je suis d'accord avec l'analyse en une ligne de @Prytoegrian ;)
Un employé ne doit voir que le-s groupe-s dans le-s-quel-s il apparait.

**Comment by Prytoegrian** [comment]
Corrigé par https://github.com/Libertempo/Libertempo-web/releases/tag/v1.9.3
