### ISSUE TITLE
Erreur : Mise à jour 1.9

### ISSUE THREAD

**Issue by exyl** [Libertempo/Libertempo-web#399]
Bonjour,

Impossible de mettre à jour depuis 1.8.1

http://intranet/libertempo/install/upgrade_from_v1.8.1.php?etape=2&version=1.9&lang=fr_FR

Cette page ne fonctionne pas

Impossible de traiter cette demande via intranet à l’heure actuelle.
HTTP ERROR 500

### Système et application

* Version de l'application : 1.8.1
* Avez-vous des notifications dans la console du navigateur : 
_"Failed to load resource: the server responded with a status of 500 (Internal Server Error)  upgrade_from_v1.8.1.php"_
* Avez-vous des erreurs dans le log du serveur http (ex : /var/log/apache2) :
_"[Tue May 02 17:31:49.597062 2017] [:error] [pid 5245] [client 192.168.2.1:51436] PHP Fatal error:  Call to undefined method includes\\Database::begin_transaction() in /var/www/html/intranet/libertempo/install/upgrade_from_v1.8.1.php on line 23, referer: http://intranet/libertempo/install/mise_a_jour.php?etape=2&version=1.8.1&lang=fr_FR"_

### Reproduction du bug

* Prérequis :
* Action de déclenchement :
* Résultat attendu :
* Résultat constaté :

**Comment by wouldsmina** [comment]
Bonjour,

Quel version de PHP utilise tu? Nous conseillons PHP5.6 et je crois que `begin_transaction` n'existe qu'à partir de 5.5.

**Comment by wouldsmina** [comment]
ping @exyl

**Comment by exyl** [comment]
Bonjour,

Apache Version	Apache/2.4.6 (CentOS) PHP/5.4.16
PHP Version 5.4.16

**Comment by wouldsmina** [comment]
ok! met à jour ton PHP :)

**Comment by exyl** [comment]
Quand je fais un yum update php sur mon Centos 7, je n'ai pas de nouveau package.
Je vais regarder sur le net

**Comment by wouldsmina** [comment]
PHP5.4 n'est plus maintenu (depuis mi 2015) tout comme Centos 7. Par sécurité, je te conseil de passer à une version plus récente...

**Comment by wouldsmina** [comment]
non, je dis une bétise, Centos 7 est toujours maintenu...

**Comment by exyl** [comment]
Je viens de passer en PHP Version 5.6.30

Une erreur est survenue ...

Pour aider la résolution de ce problème, veuillez fournir les informations suivantes :
login : 
uri   : /libertempo/install/upgrade_from_v1.8.1.php?etape=2&version=1.9&lang=fr_FR
dump  : ../dump/sql_2017-05-03T16:48:17+00:00.dump

file  : /var/www/html/intranet/libertempo/includes/SQL.php
line  : 90
fx    : $SQL->query
error : Table 'planning' already exists
sql   : CREATE TABLE `planning` (
  `planning_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(50) NOT NULL DEFAULT "",
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by Prytoegrian** [comment]
Reliquat de la précédente install ?

**Comment by exyl** [comment]
Comment je vérifie ca ?

**Comment by wouldsmina** [comment]
le plus simple reste de restaurer ta base de donnée et de refaire l'update

**Comment by exyl** [comment]
de toute façon la mise à jour en 5.6 a tout planté.
Apache ne gère plus mes connexions ldap, etc.
Je dois revenir en arrière.

Ca serait bien de préciser qu'il faut être en PHP 5.6

**Comment by wouldsmina** [comment]
c'est dans les prérequis sur la [doc](http://libertempo.tuxfamily.org/documentation/install_update/) :smile:

**Comment by exyl** [comment]
Bonjour,
Je viens de mettre à jour en 5.6 en suivant ceci :
`1. CentOS/RHEL 7.x:
rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
2.
yum install yum-plugin-replace
yum replace php-common --replace-with=php56w-common
3. 
yum install php56w-opcache`
Source : http://forums.sentora.org/showthread.php?tid=780&pid=8339

J'ai restauré ma base de données et relancer le process de mise à jour : 
_http://intranet/libertempo/install/upgrade_from_v1.8.1.php?etape=2&version=1.9&lang=fr_FR
Une erreur est survenue ...

Pour aider la résolution de ce problème, veuillez fournir les informations suivantes :
login : 
uri   : /libertempo/install/upgrade_from_v1.8.1.php?etape=2&version=1.9&lang=fr_FR
dump  : ../dump/sql_2017-05-10T17:46:11+02:00.dump

file  : /var/www/html/intranet/libertempo/includes/SQL.php
line  : 90
fx    : $SQL->query
error : Table 'planning' already exists
sql   : CREATE TABLE `planning` (
  `planning_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(50) NOT NULL DEFAULT "",
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;_

**Comment by Prytoegrian** [comment]
Tu peux essayer de 
* aller dans `cfg/dbconnect.php` et de changer le nom de ta DB, 
* créer une DB dans mysql
* retenter l'install de la version 1.9 ?

Là, ta DB est entre deux versions, je ne sais pas pourquoi.

**Comment by exyl** [comment]
Nouveau message :
login :
uri   : /libertempo/install/upgrade_from_v1.8.1.php?etape=2&version=1.9&lang=fr_FR
dump  : ../dump/sql_2017-05-11T21:16:58+02:00.dump

file  : /var/www/html/intranet/libertempo/includes/SQL.php
line  : 90
fx    : $SQL->query
error : Table 'db_conges.conges_config' doesn't exist
sql   : UPDATE conges_config SET conf_type = 'enum=dbconges/ldap/CAS/SSO' WHERE conf_nom = 'how_to_connect_user';

De : Prytoegrian [mailto:notifications@github.com]
Envoyé : jeudi 11 mai 2017 17:04
À : Libertempo/Libertempo-web <Libertempo-web@noreply.github.com>
Cc : Guillaume HERVE <exyl@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [Libertempo/Libertempo-web] Erreur : Mise à jour 1.9 (#399)


Tu peux essayer de

  *   aller dans cfg/dbconnect.php et de changer le nom de ta DB,
  *   créer une DB dans mysql
  *   retenter l'install de la version 1.9 ?

Là, ta DB est entre deux versions, je ne sais pas pourquoi.

**Comment by exyl** [comment]
Je viens d'essayer autre chose :
J'ai effacer la table planning qui était vide et relancer l'upgrade.
Nouveau message : 
login : 
uri   : /libertempo/install/upgrade_from_v1.8.1.php?etape=2&version=1.9&lang=fr_FR
dump  : ../dump/sql_2017-05-11T21:19:10+02:00.dump

file  : /var/www/html/intranet/libertempo/includes/SQL.php
line  : 90
fx    : $SQL->query
error : Can't DROP 'u_login'; check that column/key exists
sql   : ALTER TABLE conges_users DROP INDEX u_login;

Ma table conges_users est pleine et le champ u_login est rempli.

**Comment by wouldsmina** [comment]
en faitpour rétablir ta base de donnée, tu dois défaire ce qui a été fait par ce script : https://github.com/Libertempo/Libertempo-web/blob/1.9/install/upgrade_from_v1.8.1.php

Tu dois donc supprimer la table planning comme tu l'a fait, mais aussi : 
- remettre l'index sur le champ u_login
- retirer le champ planning_id de la table conges_users

Sinon, tu peux aussi le faire dans l'autre sens (exécuter les requêtes qui ne l'ont pas été) et vérifier que ta base de donnée dispose bien des modifications apportées par upgrade_from_v1.8.1.php...

**Comment by exyl** [comment]
J'ai essayé, ca tourne en rond.
Je supprime la table Planning -> error : Can't DROP 'u_login'; check that column/key exists
Je remets l'index u_login et je supprime le champ planning_id (et l'index) -> error : Table 'planning_creneau' already exists

Je supprime les tables planning_creneau et planning, je remets l'index u_login et je supprime le champ planning_id (et l'index) -> error : Unknown table 'db_conges.conges_artt'

Du coup, je suis reparti de 0.
Mais ca bug avec mes importations d'utilisateurs via LDAP qui ont des accents. L'affichage met des ?, mais surtout ils ne peuvent pas se connecter.

**Comment by wouldsmina** [comment]
tu y es presque. pour finir l'update, supprime [ces lignes](https://github.com/Libertempo/Libertempo-web/blob/1.9/install/upgrade_from_v1.8.1.php#L25L59)  (de 25 à 59) et relance une dernière fois l'update.
Je t'invite a nous joindre par [irc](https://client02.chat.mibbit.com/?url=irc%3A%2F%2Firc.tuxfamily.org%2FLibertempo), ce sera plus simple et plus rapide pour réparer ta base de donnée...

Pour ton problème d'import des utilisateurs LDAP, il y a un début de solution #368 mais pas encore assez testé pour être intégré dans le projet.

**Comment by exyl** [comment]
J'ai fini par refaire un install de base, et réimporter mes données de sauvegarde.

**Comment by Michaellabarre** [comment]
Bonjour j'utilise une vieille version de Libertempo et j'ai des messages d'erreurs qui s'affichent comme les suivantes :
![libertempo errors](https://user-images.githubusercontent.com/36041514/99351852-968c5100-28b2-11eb-841b-15200ac09b00.PNG)
