### ISSUE TITLE
Calcul des congés

### ISSUE THREAD

**Issue by mathieullis** [Libertempo/Libertempo-web#402]
Bonjour,

Je débute sur libertempo et j'ai quelques questions:
- Pour nous un congé pris = 1,2 congés. Où est il possible de paramétrer cela ?
- Je remarque que les congés sont affectés par le responsable. Est-il possible de les incrémenter automatiquement? (par exemple +2,5 jours tous les mois)

Merci pour vos réponses et votre travail.

**Comment by wouldsmina** [comment]
Bonjour,

>Pour nous un congé pris = 1,2 congés. Où est il possible de paramétrer cela ?

les congés ne peuvent etre pondéré.

> Je remarque que les congés sont affectés par le responsable. Est-il possible de les incrémenter automatiquement? (par exemple +2,5 jours tous les mois)

Non, les congés sont définit par l'admin et c'est le RH qui effectue le changement d'exercice. Mais c'est vrai que le responsable à la possibilité d'ajouter des jours de congés.
Il n'y a pas de tache planifié pour le moment, tout doit être fait à la main.

Si tu souhaites que l'on ajoute ces fonctionnalités, je t'invite à détailler ton besoin...

**Comment by mathieullis** [comment]
Merci pour votre réponse 

Je vais poser peut être la autrement. 
Comment libertempo gère les différences entre journées ouvrables et ouvrées ?

Je vois bien comment le RH peut ajouter des jours à l'ensemble des utilisateurs. Une tache planifiée qui ajoute les jours tous les 1er du mois ferait gagner du temps je pense

**Comment by wouldsmina** [comment]
ah! c'est pas pareil... le calcul sur jours ouvrable implique que les jours non travaillé (mais ouvrable) sont décompté sous certaines conditions (par exemple : un congés est déposé la veille d'un jours ouvrable, moins de 5 jours lui ont été décompté sur l'année...) tout les détails sont [ici](http://droit-finances.commentcamarche.net/faq/966-jours-ouvrables-et-jours-ouvres-conges-payes)

Pour répondre à ta question, non pour le moment, il ne le gère pas. Il y a #14 à ce sujet, donc je t'invite, si tu as des idées pour l'implémenter dans LT, à en discuter sur ce ticket...
