### ISSUE TITLE
Spécifier un remplaçant

### ISSUE THREAD

**Issue by droide02** [Libertempo/Libertempo-web#404]
Dans le formulaire de "Nouvelle Absence", il serait intéressant d'avoir un second champ en supplément du commentaire pour spécifier le remplaçant.

Remplacé par :   |___________________|

**Comment by wouldsmina** [comment]
le remplaçant? c'est a dire? désigner une personne pour remplacer l'employé qui demande le congés? si c'est ça, il n'y a aucune obligation à être remplacé durant un congés donc on n'acceptera pas cette demande, mais j'attends que tu me donne plus de détail des fois que je n'aurai pas bien compris.

**Comment by droide02** [comment]
Oui c'est exactement ça, dans notre société nous devons spécifier qui nous remplace pendant notre période de congés.

**Comment by wouldsmina** [comment]
En général c'est au responsable de décider cela... En tout cas je pense que ton besoin est loin d’être "universel". Désolé on ne va pas pouvoir donner suite.
