### ISSUE TITLE
Les demandes n'apparaissent pas en double validation

### ISSUE THREAD

**Issue by stephanetanne** [Libertempo/Libertempo-web#407]
Bonjour,

Sur la version Libertempo 1.9 Ceres, nous avons paramétré une double validation des congés.

Lors d'une demande de congé, le responsable direct reçoit bien un email de demande de validation. Sur l'interface la demande peux être validé et passe en pré-validé pour le demandeur (et il reçoit l'email de première validation).

Le second responsable reçoit bien un email comme quoi il doit valider un congé en deuxième validation mais quand il se connecte à l'interface aucune demande a valider n'apparait. Nous avons regardé en mode RH et la demande n'apparait pas non plus.

Est-ce un problème connu et si oui pouvez-vous m'aider a résoudre le problème.

Pour information, les validations de congés avec un responsable unique (pas en double validation) passe sans aucun problème.

Je vous remercie par avance.

**Comment by wouldsmina** [comment]
Bonjour,

Peux tu nous donner plus d'infos sur le paramétrage que tu as fait au niveau des groupes? 
Un exemple précis nous permettrait d'essayer de reproduire ton bug...

Merci

**Comment by stephanetanne** [comment]
Alors le problème ne se présenté pas sur la version php_conges 1.5 et libertempo 1.8.1.

Au niveau de la configuration :

Responsable :

![image](https://cloud.githubusercontent.com/assets/28647958/25993945/282985e8-370c-11e7-8438-1c28c98da07e.png)

Fonctionnement de l'établissement :

![image](https://cloud.githubusercontent.com/assets/28647958/25994017/773b1818-370c-11e7-87b1-12c752ad2215.png)

Concernant le cas concret, mon agent réalise une demande de congés pour fin mai. En tant que responsable direct de l'utilisateur et responsable du service de l'agent, je reçoit la demande.
De mon coté j'ai les droits responsable, admin et RH.
Je peux donc me connecter à mon interface et valider la demande de congés en première validation.
Une fois validé, l'agent reçoit un email de première validation et voit sa demande dans son interface comme pré-validé.
Mon responsable qui a les droits responsable et RH, et qui est mon responsable direct sur l'interface et qui est a la fois grand responsable de mon groupe reçoit un email de notification pour la seconde validation. Par contre une fois sur l'interface, il ne voit aucune demande en attente de traitement dans son mode responsable.
De mon coté je me suis connecté et j'ai regardé dans le mode RH si la demande apparait et ce n'est pas le cas.
La demande a comme disparu, sauf pour l'agent qui voit sa demande uniquement pré-validé.

Est-ce que les éléments sont assez précis ?

**Comment by wouldsmina** [comment]
oui, mais du coup je comprends pas pourquoi le grand responsable ne voit rien! As tu accès au code source et à la bdd? je veux te faire faire quelques teste de débogage pour comprendre...

**Comment by stephanetanne** [comment]
Bonjour,

Oui je suis admin de la plateforme et j'ai donc accès au serveur linux (base de données MariaDB et Apache2).
Je suis dispos pour les tests de débogage quand tu pourras.

Je te remercie par avance.

**Comment by stephanetanne** [comment]
Je viens de regarder la base de données et le problème viens bien depuis la migration vers la version 1.9.
J'ai retrouvé les demandes en attente de seconde validation sur Libertempo via PHPMyAdmin.

![image](https://cloud.githubusercontent.com/assets/28647958/26054333/756018ce-396c-11e7-8020-0562d31576f5.png)

La première demande ayant le problème date du 03/05/2017 et j'ai effectué la migration le 02/05/2017...
J'aurais pas du migrer immédiatement ^^

**Comment by wouldsmina** [comment]
ok, alors je t'invite à nous rejoindre sur [irc](https://client02.chat.mibbit.com/?url=irc%3A%2F%2Firc.tuxfamily.org%2FLibertempo)

**Comment by bphanguyen** [comment]
Bonjour,

Nous avons des problèmes similaires concernant la double validation des congés sur la version Libertempo 1.9 Ceres.

**Situation 1** : 
Mon responsable direct (mon N+1) valide ma demande de congé, ma demande apparaît alors dans ma liste des congés de ma session comme **pré-validée** et je suis informé par mail de la 1ere validation et de l'attente d'une 2e validation.
Mais le responsable de mon responsable (mon N+2) **ne reçoit aucun mail** lui informant de la demande de 2ème validation et **ma demande n'apparaît pas dans la liste des congés à valider** lorsque mon N+2 est connecté à sa session.
De plus mon congé n'apparaît pas dans le calendrier des congés.

**Situation 2** :
Un collègue a fait une demande de congé. 
Cette demande apparaît comme **validée** dans sa session (après 1ere validation) 
mais il ne reçoit pas de notification par mail, et
son responsable de 2e validation N+2 ne voit pas la demande de congé dans le tableau des congés à valider et il n'est pas notifié par mail.
De plus son congé n'apparaît pas dans le calendrier des congés.

Pourriez-vous nous aider à résoudre ces problèmes?
Nous vous remercions par avance.

**Comment by teger** [comment]
Bonjour,

Comme le ticket précédent, j'ai des problèmes avec la double validation.
Le premier responsable valide une demande de congés, elle passe en pré-validée mais le deuxième responsable ne recoit pas de mail et surtout la demande n'est plus visible dans l'interface pour personne !!!

Merci d'avance,

**Comment by wouldsmina** [comment]
Je n'arrive pas a reproduire le problème. Si quelqu'un pouvait passer sur [irc](https://client02.chat.mibbit.com/?url=irc%3A%2F%2Firc.tuxfamily.org%2FLibertempo) pour qu'on identifie et corrige le bug rapidement, ce serait bien...

**Comment by wouldsmina** [comment]
j'ai trouvé la source du problème. Un  patch vous sera proposé dans les heures qui viennent :smile:

**Comment by Prytoegrian** [comment]
Je ne reproduis pas sur la 1.9. Donnez moi plus de billes pour que je puisse tester et qu'on livre au plus tôt.
