### ISSUE TITLE
Accents & caractères spéciaux

### ISSUE THREAD

**Issue by exyl** [Libertempo/Libertempo-web#419]
Bonjour,

Je rencontre un problème en v1.9 (pareil quand j'étais en v1.8.1) avec les accents et caractères spéciaux.
Mes utilisateurs sont importés depuis mon LDAP (Active Directory).
Outre l'affichage défaillant des accents dans le nom et/ou le prénom, si un mot de passe contient un caractère spécial (tel qu'un accent), il ne peut pas se logger (c'est mon cas).
J'ai regardé un peu les différents tickets sur le sujet (93, 368,...), mais tous concerne openLDAP, et les solutions présentés ne marchent pas.

J'ai changé le character set de la table conges_users de latin1 à utf8. Ca ne change rien.

Je peux enlever les accents dans les noms et prénoms.
Mais pour les mots de passe, je ne peux rien faire.
Auriez-vous des idées ?

**Comment by wouldsmina** [comment]
Bonjour @exyl 
Normalement avec LDAP/AD, le mot de passe ne passe pas par la base de donnée de Libertempo. Peux tu me dire ce que tu as, dans la configuration générale, pour l'option `how_to_connect_user`?

**Comment by exyl** [comment]
Bonjour,

J’ai ldap.
Dans mon cas, j’avais un accent dans mon mot de passe : ERREUR : Nom d'utilisateur et/ou mot de passe incorrect !!!
J’ai remplacé l’accent par le symbôle € et pareil.
Par contre, sans accent et sans caractère spécial, pas de soucis.
Pas d’accent ou caractère spécial dans le login.

Guillaume

De : wouldsmina [mailto:notifications@github.com]
Envoyé : mercredi 24 mai 2017 09:09
À : Libertempo/Libertempo-web <Libertempo-web@noreply.github.com>
Cc : Guillaume HERVE <exyl@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [Libertempo/Libertempo-web] Accents & caractères spéciaux (#419)


Bonjour @exyl<https://github.com/exyl>
Normalement avec LDAP/AD, le mot de passe ne passe pas par la base de donnée de Libertempo. Peux tu me dire ce que tu as, dans la configuration générale, pour l'option how_to_connect_user?

**Comment by Prytoegrian** [comment]
Tu as la main sur le code ? Effectues une comparaison des chaînes juste avant l'erreur, et dis nous ce que renvoie `mb_detect_encoding`.

**Comment by exyl** [comment]
Oui, j’ai la main.
Où est-ce que je vais trouver ca ? Quelle page ?

De : Prytoegrian [mailto:notifications@github.com]
Envoyé : mercredi 24 mai 2017 13:48
À : Libertempo/Libertempo-web <Libertempo-web@noreply.github.com>
Cc : Guillaume HERVE <exyl@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [Libertempo/Libertempo-web] Accents & caractères spéciaux (#419)


Tu as la main sur le code ? Effectues une comparaison des chaînes juste avant l'erreur, et dis nous ce que renvoie mb_detect_encoding.

**Comment by Prytoegrian** [comment]
Sur `includes/fonctions::authentification_ldap_conges()`, tu peux tenter un : 
```php
var_dump(mb_detect_encoding($username), mb_detect_encoding($password);
exit();
```

Mais dis nous en quelle version est ton LDAP. Tu trouveras ça dans ton fichier de config LDAP, `cfg/config_ldap.php`

**Comment by exyl** [comment]
J’ai passé ldap en version 3 et ca marche.
Désolé, comme je suis reparti de 0 après ma tentative de migration en 1.9, je n’ai pas tout repointé.

De : Prytoegrian [mailto:notifications@github.com]
Envoyé : mercredi 24 mai 2017 14:31
À : Libertempo/Libertempo-web <Libertempo-web@noreply.github.com>
Cc : Guillaume HERVE <exyl@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [Libertempo/Libertempo-web] Accents & caractères spéciaux (#419)


Sur includes/fonctions::authentification_ldap_conges(), tu peux tenter un :

var_dump(mb_detect_encoding($username), mb_detect_encoding($password);

exit();

Mais dis nous en quelle version est ton LDAP. Tu trouveras ça dans ton fichier de config LDAP, cfg/config_ldap.php

**Comment by wouldsmina** [comment]
Super! on saura pour l'avenir... Merci.
