### ISSUE TITLE
Compter les jours

### ISSUE THREAD

**Issue by exyl** [Libertempo/Libertempo-web#420]
Bonjour,

J'ai la dernière version 1.9 de Libertempo.
En faisant une démo avant de donner accès aux collaborateurs jeudi 01/06, je me suis aperçu que la zone "Nombre de jours" qui compte automatiquement, ne compte que les journées qu'en 1/2.
Exemple : je pose 3 jours (mardi, mercredi, jeudi), cela m'affiche 1,5.

Merci.

**Comment by wouldsmina** [comment]
salut,
tu as quoi dans le planning de l'employé?

**Comment by exyl** [comment]
J'allais y venir.
Comme c'est nouveau, j'ai créé un planning vite fait 09:.00/18:00
Mais j'ai pas coché matin ou après-midi

**Comment by wouldsmina** [comment]
tu as trouvé le problème! si tu bosse le matin de 09:00 à 18:00, ça te compte qu'une demi-journée :smiley: 

On a fait le choix de ne pas limiter les horaires du matin et de l'après-midi pour la simple raison qu'on ne peut pas définir quand fini une matinée ou débute un après-midi de travail...

**Comment by exyl** [comment]
Vu ! :)
Par contre, pour la nouvelle version, il faudrait pouvoir éditer la plage horaire sans tout effacer :p
