### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by exyl** [Libertempo/Libertempo-web#422]
Bonjour à tous,

Libertempo : 1.9
Serveur : Centos 7

Je ne sais pas comment résoudre le problème des accents.
Pour la partie LDAP, j'ai réussi à bidouiller entre mon AD et Libertempo.
Mais là, entre le calendrier, et surtout, les emails reçus, c'est très moche pour les utilisateurs.
Voir Screenshots joints.
![capture1](https://cloud.githubusercontent.com/assets/28304217/26679282/a9592cae-46d4-11e7-8904-ad73f3037adc.PNG)
![capture2](https://cloud.githubusercontent.com/assets/28304217/26679285/ab585e12-46d4-11e7-8bcc-2ac28dae1af3.PNG)

**Comment by exyl** [comment]
La table conges_mail est en MyISAL / Latin1 cp 1252
Les é sont vu comme ca dans la table : Ã©

**Comment by exyl** [comment]
J'ai changé la table en UTF8 et je retapé tous les accents depuis l'interface de configuration des mails envoyés.
Pour les mails, ca semble bon.

**Comment by wouldsmina** [comment]
Salut,

peux tu me dire quelles "locale" sont installé sur ton serveur?

**Comment by exyl** [comment]
[root@pbbsrvwww01 ~]# locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

**Comment by wouldsmina** [comment]
ok, vérifie aussi le codage caractère des fichiers de LT, normalement c'est de l'utf-8

**Comment by exyl** [comment]
Là, je vois pas désolé :)

**Comment by wouldsmina** [comment]
avec la commande `file`

**Comment by exyl** [comment]
Bonjour,
On arrive sur les mois à accents.
Comment je peux corriger août ?

**Comment by wouldsmina** [comment]
tu ne m'as pas répondu au sujet de la commande `file n'importe_quel_fichier_Libertempo.php`

corriger chaque mot n'est pas une solution, il faut que tu cherches du coté de la configuration de ton serveur.

**Comment by exyl** [comment]
C'est ca ? 
[root@pbbsrvwww01 ~]# file /var/www/html/intranet/libertempo/calendrier.php
/var/www/html/intranet/libertempo/calendrier.php: PHP script, ASCII text

**Comment by wouldsmina** [comment]
ouaip. vérifie dans ton fichier de conf apache que tu as bien cette option : `AddDefaultCharset UTF-8`

**Comment by Prytoegrian** [comment]
j'ai fait la même commande et j'ai le même résultat. Pour autant, j'ai bien août qui s'affiche correctement dans le calendrier

**Comment by wouldsmina** [comment]
oui, le codage du fichier n'est pas la cause du problème. Comme je le soupçonnais, c'est le serveur qui pose problème...

**Comment by wouldsmina** [comment]
ping @exyl et je t'invite à faire ce que j'ai demandé dans #468

**Comment by exyl** [comment]
Bonjour,
Désolé, je suis en vacances.
Je pourrais vérifier vers la fin du mois.

**Comment by exyl** [comment]
La base est en latin1_swedish_ci
Les tables : 
![libertempo](https://user-images.githubusercontent.com/28304217/28778375-3fc22ce6-75ff-11e7-9666-5eb11d3ce8b0.PNG)

Et : 
Liste des fichiers non UNIX (\r) : ./cfg/config_SMTP.php ./cfg/config_ldap.php ./cfg/dbconnect.php ./cfg/env.php ./export/ics_export.php ./template/reboot/popup_header.php ./vendor/jasig/phpcas/docs/examples/example_advanced_saml11.php ./vendor/jasig/phpcas/docs/examples/example_hardening.php ./vendor/jasig/phpcas/source/CAS.php ./vendor/jasig/phpcas/source/CAS/Autoload.php ./vendor/jasig/phpcas/source/CAS/OutOfSequenceBeforeAuthenticationCallException.php ./vendor/jasig/phpcas/source/CAS/OutOfSequenceBeforeClientException.php ./vendor/jasig/phpcas/source/CAS/OutOfSequenceBeforeProxyException.php Liste des fichiers utilisant mysql et non mysqli : ./check_file_coding_standard.php Liste des fichiers non UTF-8 : ./cfg/config_SMTP.php ./cfg/config_ldap.php Liste des fichiers avec short tag php : ./check_file_coding_standard.php

**Comment by Prytoegrian** [comment]
J'ai (enfin) pu le reproduire, je me mets dessus au plus tôt

**Comment by Prytoegrian** [comment]
Nous l'avons corrigé. Au vu de la nature du bug, j'ai pris la décision de ne pas casser notre workflow et de poser le correctif sur `beta`. Il sera donc mis à disposition pour la production lors de la publication finale de `1.10`.
