### ISSUE TITLE
question : gestion des users qui changent de noms

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#423]
Bonjour à tous,

je n'avais pas encore eu ce cas de figure, et je viens de m'y casser les dents : une utilisatrice s'est mariée et a demandé à ce que l'on mettre son nom à jour.
On a commencé par le LDAP : libertempo lui est devenu inaccessible.

Dans l'interface de gestion des utilisateurs, on peut modifier certains champs MAIS pas celui du login ET on ne peut pas "resynchroniser" avec le LDAP.
En Bdd, je peux changer son login MAIS je perds tout l'historique.
Y aurait-il une manip' pour ce cas de figure que j'aurais manqué ?

Merci

**Comment by wouldsmina** [comment]
Salut,
On a prévu de modifier la BDD pour avoir une PK auto-incrémenté sur la table, mais malheureusement, pour le moment, non. Tu va devoir passer sur chaque table pour mettre à jour le login... :s

**Comment by LRCorwin** [comment]
salut,

argh ;)
ceci dit, j'ai essayé sur l'une des tables et je me suis fait jeté.
Je vérifie ça en début de semaine prochaine.

**Comment by exyl** [comment]
Salut, 
En général, (c'est mon expérience), les femmes peuvent comprendre que c'est difficile de changer le système quand elles se marient, et peuvent accepter de garder leur nom de jeune fille.
Mais quand c'est un divorce, là, on a pas le choix, faut changer.

**Comment by LRCorwin** [comment]
Hello,

le problème c'est qu'on a des procédures éprouvées pour les modifs dans le LDAP, la messagerie etc etc, et que là, c'est une première pour une utilisatrice sous Libertempo.
Comme on migre de plus en plus de monde sous l'appli, le cas risque de se présenter de nouveau.
Je regarderai du côté de la Bdd pour voir si je m'en sors.

**Comment by wouldsmina** [comment]
@LRCorwin je laisse le ticket ouvert le temps que tu fasses le changement... Tiens nous au jus.

**Comment by LRCorwin** [comment]
Hello,

il y a certaines entrées en BdB que je ne peux pas modifier. J'ai une erreur mysql de ce genre :
 MySQL a répondu: Documentation
#1062 - Duplicate entry 'keravec-9999-12-31' for key 'PRIMARY'

**Comment by LRCorwin** [comment]
bon écoute, je suis allé dans toutes les tables de la Bdd : là où la modif n'était pas passible, j'ai supprimé la ligne avant d'en recréer une avec les "bonnes" valeurs.
Pas très joli-joli, mais ça marche.
On ferme le ticket, et on espère une "amélioration" de cette prise en charge du renommage dans les prochaines versions :)

**Comment by wouldsmina** [comment]
:+1: cette amélioration viendra naturellement lorsqu'on aura "retapé" la base de donnée pour qu'elle soit plus cohérente.
a+

**Comment by Prytoegrian** [comment]
Je paraphrase mon camarade. À l'avenir (que j'espère pas si lointain), l'élément déterminant d'un utilisateur ne sera pas son login. On pourra à ce moment faire les changements qui nous intéressent aisément.
