### ISSUE TITLE
Suite déploiement 1.9

### ISSUE THREAD

**Issue by exyl** [Libertempo/Libertempo-web#424]
Libertempo : 1.9
Centos 7

Bonjour à tous,

24h après le déploiement, j'ai pas mal de retour. Du bon.
Et du moins bon. Voici une petite liste. 
A voir après ce qui est du bug ou pas.
- on ne voit pas les congés dans le calendrier sur Septembre.
Un collaborateur a pris des congés sur fin août/début septembre.
Quand on affiche août, on voit les jours posés dans la partie grisée correspondant à septembre. Mais plus rien quand on va sur septembre. Limite à 3 mois ?
- On ne peut pas modifier ses demandes ou les supprimer.
Demandes non approuvées, on a la main pour éditer ou supprimer. On valide. Pas de message d'erreur. On revient sur la page principale, mais les modifs ne sont pas prises en compte.
- Demandes approuvées. On ne peut rien faire. Les options édition ou suppression ne sont pas cliquables.
Au manager de les supprimer. Mais l'endroit et la manière, ce n'est pas très intuitif.
- Décompte solde. Un collaborateur fait 3 demandes pour un total de 19 jours (12 + 6 +1).
Le manager valide les 3 demandes. il y a un décompte que des 2 dernières, soit 7 jours.

Guillaume

**Comment by wouldsmina** [comment]
salut,

> on ne voit pas les congés dans le calendrier sur Septembre.

ça semble etre un bug, mais vu que le calendrier va changer sous peu, on va attendre...

> On ne peut pas modifier ses demandes ou les supprimer.

C'est un bug qui a été corrigé. Télécharge la version 1.9.2 et remplace tes fichiers (inutile d’exécuter la mise à jour, il n'y a pas de changement dans la base de données entre 1.9 et 1.9.x)

> Demandes approuvées. On ne peut rien faire. Les options édition ou suppression ne sont pas cliquables. 

L'employé n'a pas le droit d'annuler ou modifier une demande traitée.

>Au manager de les supprimer. Mais l'endroit et la manière, ce n'est pas très intuitif.

Oui, c'est pas faux... Si tu as une proposition pour améliorer l'ergonomie à ce niveau, on t'écoute :smile: 

> Décompte solde. Un collaborateur fait 3 demandes pour un total de 19 jours (12 + 6 +1).
Le manager valide les 3 demandes. il y a un décompte que des 2 dernières, soit 7 jours.

ça mérite un nouveau ticket pour une investigation...

Merci bien pour ton retour d'expérience.

**Comment by exyl** [comment]
Merci pour le retour rapide.
Je télécharge la dernière version tout de suite.

**Comment by exyl** [comment]
J'ai écrasé les fichiers avec la dernière version.
J'ai plein de trucs bizarres dans les affichages...
Par exemple, dans la config, quand je clique sur Voir les logs.
![capture1](https://cloud.githubusercontent.com/assets/28304217/26732928/9610b230-47b9-11e7-9c8d-6a0aeb7fe9ac.PNG)

Quand je clique sur RH par exemple, après une modif, le nom des tabs ne correspond plus.
![capture2](https://cloud.githubusercontent.com/assets/28304217/26733037/ec1bce3a-47b9-11e7-95e7-848447f3a48f.PNG)

Pas de mise à jour le vendredi pourtant :(

**Comment by exyl** [comment]
Bon, je suis revenu en arrière, à la version 1.9

**Comment by wouldsmina** [comment]
Oups, j'ai oublié un détail, il faut restart apache pour qu'il charge le
nouveau binaire pour les traductions...
