### ISSUE TITLE
Demi-journée

### ISSUE THREAD

**Issue by teger** [Libertempo/Libertempo-web#425]
Bonjour,

Sur la vue calendrier ou sur l'export des congés, il n'y a pas de différence entre une demi-journée ou une journée de congés (à part au survol).
Serait-il possible de mettre une couleur différente ou un picto pour expliciter cette notion ?
Avec bien entendu une légende pour expliquer la couleur ou le picto.

D'autres part, dans la vue calendrier également, tous les utilisateurs ont la même couleur.
Serait-il possible de fixer une couleur (automatique ou manuellement) à chaque utilisateur ?
Le vue n'en serait que plus lisible.

Merci d'avance et bonne continuation

**Comment by wouldsmina** [comment]
Bonjour,

Nous prévoyons de (re-)refaire le calendrier pour revenir à quelque chose de plus proche de l'ancien (avec du code propre!). Je t'invite donc à patienter, ça devrait arriver avant la fin de l'été...

a+
