### ISSUE TITLE
Décompte solde.

### ISSUE THREAD

**Issue by exyl** [Libertempo/Libertempo-web#426]
Un collaborateur qui à 41 jours (11+30) a fait 3 demandes pour un total de 19 jours (12 + 6 +1).
Le manager valide les 3 demandes. 
Son solde est à 33 ?!
Voici les logs de la validation
![capture1](https://cloud.githubusercontent.com/assets/28304217/26732848/4fc372b8-47b9-11e7-8a60-f6e37fcfca0b.PNG)
Voici en base
![capture2](https://cloud.githubusercontent.com/assets/28304217/26732850/516362e0-47b9-11e7-8633-c1eaf491c142.PNG)

**Comment by wouldsmina** [comment]
pourrais-tu regarder dans la table conges_logs (ou dans admin > configuration > logs) ce qui s'y trouve à propos de ces demandes?

**Comment by exyl** [comment]
![capture1](https://cloud.githubusercontent.com/assets/28304217/26787721/50328f3c-4a0b-11e7-8cd9-264a881bc2c3.PNG)

**Comment by exyl** [comment]
![capture1](https://cloud.githubusercontent.com/assets/28304217/26787758/6a32764a-4a0b-11e7-93d2-2ffe32fe2d40.PNG)

**Comment by wouldsmina** [comment]
il n'avait pas de reliquat?

**Comment by exyl** [comment]
Si 11 jours d'ou les 41 jours (11+30)

**Comment by wouldsmina** [comment]
ok, merci. Je vais essayer de reproduire...

**Comment by wouldsmina** [comment]
une dernière question :) tu as quelque chose dans les logs apache?

**Comment by exyl** [comment]
Voici le error_log :
[Mon May 29 03:45:06.307758 2017] [auth_digest:notice] [pid 26515] AH01757: generating secret for digest authentication ...
[Mon May 29 03:45:06.308716 2017] [lbmethod_heartbeat:notice] [pid 26515] AH02282: No slotmem from mod_heartmonitor
[Mon May 29 03:45:06.341173 2017] [mpm_prefork:notice] [pid 26515] AH00163: Apache/2.4.6 (CentOS) PHP/5.6.30 configured -- resuming normal operations
[Mon May 29 03:45:06.341192 2017] [core:notice] [pid 26515] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed May 31 20:31:52.322994 2017] [mpm_prefork:notice] [pid 26515] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Jun 01 14:34:57.650249 2017] [core:notice] [pid 852] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu Jun 01 14:34:57.700300 2017] [suexec:notice] [pid 852] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu Jun 01 14:34:57.838168 2017] [auth_digest:notice] [pid 852] AH01757: generating secret for digest authentication ...
[Thu Jun 01 14:34:57.839411 2017] [lbmethod_heartbeat:notice] [pid 852] AH02282: No slotmem from mod_heartmonitor
[Thu Jun 01 14:34:59.883415 2017] [mpm_prefork:notice] [pid 852] AH00163: Apache/2.4.6 (CentOS) PHP/5.6.30 configured -- resuming normal operations
[Thu Jun 01 14:34:59.883450 2017] [core:notice] [pid 852] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Jun 01 14:35:55.738135 2017] [:error] [pid 3171] [client 192.168.2.1:61910] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges07b988ae7652f03f1c5f311bbb8526f9&p_num=154&onglet=suppr_demande
[Thu Jun 01 14:36:33.892280 2017] [:error] [pid 3167] [client 192.168.2.1:61933] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges07b988ae7652f03f1c5f311bbb8526f9&p_num=154&onglet=modif_demande
[Thu Jun 01 14:39:10.894359 2017] [:error] [pid 3170] [client 192.168.2.10:51558] PHP Notice:  Undefined offset: 2 in /var/www/html/intranet/libertempo/fonctions_calcul.php on line 145, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges4c93a7daf3274f5448ee52c45dc4e50c
[Thu Jun 01 14:39:10.894505 2017] [:error] [pid 3170] [client 192.168.2.10:51558] PHP Notice:  Undefined offset: 2 in /var/www/html/intranet/libertempo/fonctions_calcul.php on line 145, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges4c93a7daf3274f5448ee52c45dc4e50c
[Thu Jun 01 14:39:10.895318 2017] [:error] [pid 3170] [client 192.168.2.10:51558] PHP Notice:  Undefined index: 2017-06 in /var/www/html/intranet/libertempo/fonctions_calcul.php on line 296, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges4c93a7daf3274f5448ee52c45dc4e50c
[Thu Jun 01 14:39:10.895421 2017] [:error] [pid 3170] [client 192.168.2.10:51558] PHP Notice:  Undefined variable: periodeFin in /var/www/html/intranet/libertempo/fonctions_calcul.php on line 314, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges4c93a7daf3274f5448ee52c45dc4e50c
[Thu Jun 01 14:39:10.896352 2017] [:error] [pid 3170] [client 192.168.2.10:51558] PHP Warning:  fopen(dump/sql_2017-06-01T14:39:10+02:00.dump): failed to open stream: Permission non accord\xef\xbf\xbde in /var/www/html/intranet/libertempo/includes/SQL.php on line 157, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges4c93a7daf3274f5448ee52c45dc4e50c
[Thu Jun 01 14:39:13.268304 2017] [:error] [pid 3170] [client 192.168.2.10:51558] PHP Notice:  Undefined offset: 2 in /var/www/html/intranet/libertempo/fonctions_calcul.php on line 145, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges4c93a7daf3274f5448ee52c45dc4e50c
[Thu Jun 01 14:39:13.268371 2017] [:error] [pid 3170] [client 192.168.2.10:51558] PHP Notice:  Undefined offset: 2 in /var/www/html/intranet/libertempo/fonctions_calcul.php on line 145, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges4c93a7daf3274f5448ee52c45dc4e50c
[Thu Jun 01 14:39:13.268946 2017] [:error] [pid 3170] [client 192.168.2.10:51558] PHP Notice:  Undefined index: 2017-06 in /var/www/html/intranet/libertempo/fonctions_calcul.php on line 296, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges4c93a7daf3274f5448ee52c45dc4e50c
[Thu Jun 01 14:39:13.269014 2017] [:error] [pid 3170] [client 192.168.2.10:51558] PHP Notice:  Undefined variable: periodeFin in /var/www/html/intranet/libertempo/fonctions_calcul.php on line 314, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges4c93a7daf3274f5448ee52c45dc4e50c
[Thu Jun 01 14:39:13.269497 2017] [:error] [pid 3170] [client 192.168.2.10:51558] PHP Warning:  fopen(dump/sql_2017-06-01T14:39:13+02:00.dump): failed to open stream: Permission non accord\xef\xbf\xbde in /var/www/html/intranet/libertempo/includes/SQL.php on line 157, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges4c93a7daf3274f5448ee52c45dc4e50c
[Thu Jun 01 14:42:44.864713 2017] [:error] [pid 9983] [client 192.168.2.31:63301] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges6394958ef905ad6b43fd364bcac0b09a&p_num=156&onglet=modif_demande
[Thu Jun 01 14:42:57.146395 2017] [:error] [pid 9977] [client 192.168.2.31:63329] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges6394958ef905ad6b43fd364bcac0b09a&p_num=156&onglet=modif_demande
[Fri Jun 02 11:12:14.592685 2017] [:error] [pid 13014] [client 192.168.2.16:56132] PHP Notice:  Undefined index: userlogin in /var/www/html/intranet/libertempo/template/reboot/menu_header.php on line 5, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesc3c6f3222505cd070eca1c12536dadd9
[Fri Jun 02 11:12:14.592782 2017] [:error] [pid 13014] [client 192.168.2.16:56132] PHP Notice:  Undefined index: userlogin in /var/www/html/intranet/libertempo/template/reboot/menu_header.php on line 7, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesc3c6f3222505cd070eca1c12536dadd9
[Fri Jun 02 11:12:14.592801 2017] [:error] [pid 13014] [client 192.168.2.16:56132] PHP Notice:  Undefined index: userlogin in /var/www/html/intranet/libertempo/template/reboot/menu_header.php on line 9, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesc3c6f3222505cd070eca1c12536dadd9
[Fri Jun 02 11:12:14.592866 2017] [:error] [pid 13014] [client 192.168.2.16:56132] PHP Notice:  Undefined index: userlogin in /var/www/html/intranet/libertempo/template/reboot/menu_header.php on line 121, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesc3c6f3222505cd070eca1c12536dadd9
[Fri Jun 02 11:12:14.592877 2017] [:error] [pid 13014] [client 192.168.2.16:56132] PHP Notice:  Undefined index: u_prenom in /var/www/html/intranet/libertempo/template/reboot/menu_header.php on line 123, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesc3c6f3222505cd070eca1c12536dadd9
[Fri Jun 02 11:12:14.592883 2017] [:error] [pid 13014] [client 192.168.2.16:56132] PHP Notice:  Undefined index: u_nom in /var/www/html/intranet/libertempo/template/reboot/menu_header.php on line 124, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesc3c6f3222505cd070eca1c12536dadd9
[Fri Jun 02 11:12:14.592889 2017] [:error] [pid 13014] [client 192.168.2.16:56132] PHP Notice:  Undefined index: userlogin in /var/www/html/intranet/libertempo/template/reboot/menu_header.php on line 129, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesc3c6f3222505cd070eca1c12536dadd9
[Fri Jun 02 11:12:14.592897 2017] [:error] [pid 13014] [client 192.168.2.16:56132] PHP Notice:  Undefined index: userlogin in /var/www/html/intranet/libertempo/template/reboot/menu_header.php on line 137, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesc3c6f3222505cd070eca1c12536dadd9
[Fri Jun 02 11:12:14.592918 2017] [:error] [pid 13014] [client 192.168.2.16:56132] PHP Notice:  Undefined index: userlogin in /var/www/html/intranet/libertempo/template/reboot/menu_header.php on line 145, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesc3c6f3222505cd070eca1c12536dadd9
[Fri Jun 02 11:12:14.592938 2017] [:error] [pid 13014] [client 192.168.2.16:56132] PHP Notice:  Undefined index: config in /var/www/html/intranet/libertempo/template/reboot/menu_header.php on line 168, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesc3c6f3222505cd070eca1c12536dadd9
[Fri Jun 02 11:31:44.842776 2017] [:error] [pid 13152] [client 192.168.2.16:56456] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesad983d12e4287b748b2db9439aaed416&p_num=162&onglet=suppr_demande
[Fri Jun 02 11:32:54.562174 2017] [:error] [pid 13029] [client 192.168.2.16:56476] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpcongesad983d12e4287b748b2db9439aaed416&p_num=162&onglet=suppr_demande
[Fri Jun 02 12:37:33.397580 2017] [:error] [pid 13535] [client 192.168.2.34:49824] PHP Warning:  ldap_search(): Search: Bad search filter in /var/www/html/intranet/libertempo/library/authLDAP.php on line 128, referer: http://intranet/libertempo/index.php
[Fri Jun 02 12:37:33.397633 2017] [:error] [pid 13535] [client 192.168.2.34:49824] PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in /var/www/html/intranet/libertempo/library/authLDAP.php on line 132, referer: http://intranet/libertempo/index.php
[Fri Jun 02 12:38:16.805024 2017] [:error] [pid 13536] [client 192.168.2.34:49828] PHP Warning:  ldap_search(): Search: Bad search filter in /var/www/html/intranet/libertempo/library/authLDAP.php on line 128, referer: http://intranet/libertempo/index.php
[Fri Jun 02 12:38:16.805070 2017] [:error] [pid 13536] [client 192.168.2.34:49828] PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in /var/www/html/intranet/libertempo/library/authLDAP.php on line 132, referer: http://intranet/libertempo/index.php
[Fri Jun 02 12:39:18.134767 2017] [:error] [pid 13541] [client 192.168.2.34:49832] PHP Warning:  ldap_search(): Search: Bad search filter in /var/www/html/intranet/libertempo/library/authLDAP.php on line 128, referer: http://intranet/libertempo/index.php
[Fri Jun 02 12:39:18.134818 2017] [:error] [pid 13541] [client 192.168.2.34:49832] PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in /var/www/html/intranet/libertempo/library/authLDAP.php on line 132, referer: http://intranet/libertempo/index.php
[Fri Jun 02 12:42:25.466564 2017] [:error] [pid 13007] [client 192.168.2.1:64105] PHP Notice:  Undefined index: tab_j_fermeture in /var/www/html/intranet/libertempo/hr/Fonctions.php on line 1015, referer: http://intranet/libertempo/hr/hr_index.php?session=phpconges2fc0cc65074d8ab4515e417479c6b140
[Fri Jun 02 12:47:23.719346 2017] [:error] [pid 13153] [client 192.168.2.1:64180] PHP Notice:  Undefined index: tab_j_fermeture in /var/www/html/intranet/libertempo/hr/Fonctions.php on line 1015, referer: http://intranet/libertempo/hr/hr_index.php?session=phpconges2fc0cc65074d8ab4515e417479c6b140
[Fri Jun 02 12:48:49.234505 2017] [:error] [pid 13534] [client 192.168.2.1:64202] PHP Notice:  Undefined index: tab_j_fermeture in /var/www/html/intranet/libertempo/hr/Fonctions.php on line 1015, referer: http://intranet/libertempo/hr/hr_index.php?session=phpconges2fc0cc65074d8ab4515e417479c6b140
[Fri Jun 02 12:49:09.583548 2017] [:error] [pid 13535] [client 192.168.2.1:64205] PHP Notice:  Undefined index: tab_j_fermeture in /var/www/html/intranet/libertempo/hr/Fonctions.php on line 1015, referer: http://intranet/libertempo/hr/hr_index.php?session=phpconges2fc0cc65074d8ab4515e417479c6b140&onglet=page_principale
[Fri Jun 02 12:49:55.544412 2017] [:error] [pid 13153] [client 192.168.2.1:64220] PHP Notice:  Undefined index: tab_j_fermeture in /var/www/html/intranet/libertempo/hr/Fonctions.php on line 1015, referer: http://intranet/libertempo/hr/hr_index.php?session=phpconges2fc0cc65074d8ab4515e417479c6b140&onglet=page_principale
[Fri Jun 02 13:14:13.277481 2017] [:error] [pid 13543] [client 192.168.2.73:58682] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges5e9a3cce10977daf4cd9c82190c5d64d&p_num=170&onglet=modif_demande
[Fri Jun 02 13:14:42.810819 2017] [:error] [pid 13589] [client 192.168.2.73:58692] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges5e9a3cce10977daf4cd9c82190c5d64d&p_num=170&onglet=modif_demande
[Fri Jun 02 13:21:44.624212 2017] [:error] [pid 13544] [client 192.168.2.73:58714] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges5e9a3cce10977daf4cd9c82190c5d64d&p_num=170&onglet=suppr_demande
[Fri Jun 02 13:26:15.684032 2017] [:error] [pid 13543] [client 192.168.2.73:58799] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges3a2efd053cc540c963f764ff7c06cd40&p_num=170&onglet=modif_demande
[Fri Jun 02 13:26:28.395839 2017] [:error] [pid 13534] [client 192.168.2.73:58800] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges3a2efd053cc540c963f764ff7c06cd40&p_num=170&onglet=suppr_demande
[Fri Jun 02 13:27:14.909477 2017] [:error] [pid 13589] [client 192.168.2.73:58805] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges3a2efd053cc540c963f764ff7c06cd40&p_num=170&onglet=suppr_demande
[Fri Jun 02 13:27:40.660031 2017] [:error] [pid 13541] [client 192.168.2.73:58808] PHP Notice:  Undefined index: p_etat in /var/www/html/intranet/libertempo/utilisateur/Fonctions.php on line 1527, referer: http://intranet/libertempo/utilisateur/user_index.php?session=phpconges3a2efd053cc540c963f764ff7c06cd40&p_num=170&onglet=modif_demande
[Fri Jun 02 18:05:42.638260 2017] [:error] [pid 14372] [client 192.168.2.1:53421] PHP Notice:  Constant _PHP_CONGES already defined in /var/www/html/intranet/libertempo/define.php on line 2, referer: http://intranet/libertempo/config/index.php?session=phpconges6669ec3b2e757d9efe0d02a9541bf50a
[Sun Jun 04 03:10:06.279901 2017] [mpm_prefork:notice] [pid 852] AH00171: Graceful restart requested, doing restart

**Comment by wouldsmina** [comment]
ok, a priori, il n'y a pas d'erreur au sujet du décompte, je mets les autres erreurs sur le compte du passage à la 1.10... a surveiller après correction de #427

**Comment by wouldsmina** [comment]
je n'arrive pas a reproduire :/ quel version tu utilises? 33 c'est 30+3 ou le solde a été incrémenté?? est ce que tu arrive a reproduire? si tu n'as pas de plateforme de test, utilise la [démo](http://libertempo.tuxfamily.org/info_demo/)

**Comment by exyl** [comment]
Au moment du bug, c'était la 1.9 je crois.
Moi, j'ai une question, pourquoi chaque approbation de congés génère 2 entrées identiques dans les logs ?
Sauf pour cette demande buggée qui n'en a qu'une d'ailleurs.

**Comment by wouldsmina** [comment]
> Moi, j'ai une question, pourquoi chaque approbation de congés génère 2 entrées identiques dans les logs ?

la fonction qui génère les logs est appelé deux fois. C'est une petite erreur d'inadvertance de ma part, mais  qui révèle que quelque chose s'est mal passé entre [ici](https://github.com/Libertempo/Libertempo-web/blob/develop/App/ProtoControllers/Responsable/Traitement/Conge.php#L201) et [la](https://github.com/Libertempo/Libertempo-web/blob/develop/App/ProtoControllers/Responsable/Traitement/Conge.php#L287). 

Si tu pouvais reproduire le bug avec la démo et me donner le "pas à pas", ça me permettrait de rapidement identifier la source du problème...

**Comment by exyl** [comment]
Je ne sais pas comment reproduire l'erreur, car depuis, il n'y a pas d'autres problèmes.
Peut-être une validation (trop) rapide entre les 3 demandes ?
Je vois qu'il y a eu 15 secondes entre chaque.

**Comment by Prytoegrian** [comment]
Hésite pas à nous dire si le problème a reparu pour qu'on puisse se pencher dessus pour la livraison prochaine.

**Comment by exyl** [comment]
Le problème n'est pas réapparu.
Mais je n'ai pas corrigé le solde pour le moment.
Comment faire ? Par la fonction RH ? En ajoutant la 2ème ligne manquante dans la base ?

**Comment by wouldsmina** [comment]
modifie le solde à partir du profil admin.

**Comment by Prytoegrian** [comment]
Je prends sur moi de fermer le ticket. S'il revient, on rouvrira.
