### ISSUE TITLE
Échange de jour RTT : notification du responsable par mail

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#428]
Bonjour,

plusieurs responsables locaux me demandent s'il est possible que l'appli émette un mail automatique vers eux lorsque l'un des membres de leurs groupes gérés utilise la fonction "échange jour rtt" ?

Est-ce déjà faisable ? (Auquel cas, je n'ai pas trouvé la manip', désolé)
Est-ce envisageable dans une prochaine version ?

merci

**Comment by wouldsmina** [comment]
Bonjour,

Je crois qu'on a déjà eu cette demande. Je dois avouer que j'ai mis de coté la refonte de cette fonctionnalité car je ne savais pas si elle était vraiment utilisée...

 > Est-ce envisageable dans une prochaine version ?

ça devrait pouvoir ce faire :)

**Comment by LRCorwin** [comment]
nickel :+1:

**Comment by wouldsmina** [comment]
j'ai retrouvé le ticket : #46 :champagne:

**Comment by LRCorwin** [comment]
Effectivement. C'est bien l'idée :)

**Comment by Prytoegrian** [comment]
Doublon #7 donc. Je ferme en conservant la référence, pour éviter qu'on croit qu'il y a un encours énorme.
