### ISSUE TITLE
Calendrier pour afficher présents et absents

### ISSUE THREAD

**Issue by cezaropa** [Libertempo/Libertempo-web#438]
Comme l'indique  (LRCorwin commented on 6 Apr)  dans son post, l'affichage actuel ne rend plus le même service que l'ancien. En ce qui nous concerne on ne passera pas à la v1.9 de ce seul fait là.
Dommage !
Je rejoins ceux qui proposent le choix d'un affichage au grès des besoins des utilisateurs. Plus de code certes, mais plus de personnes satisfaites dans les nombreux usages qui peuvent en être faits.
Cordialement

**Comment by Prytoegrian** [comment]
Je me permets de clore, ça fait doublon et je t'ai répondu ici https://github.com/Libertempo/Libertempo-web/issues/374#issuecomment-308450730

**Comment by cezaropa** [comment]
Ok.
Merci beaucoup.
Cordialement
