### ISSUE TITLE
Migrer les mots de passe vers un algo plus robuste

### ISSUE THREAD

**Issue by prytoegrian** [Libertempo/Libertempo-web#444]
L'algo MD5 chiffre actuellement les mots de passe utilisateurs et son successeur, sha1, est considéré comme obsolète depuis 2011. Pire, [Google a prouvé](http://www.numerama.com/tech/235436-shattered-google-a-casse-la-methode-de-chiffrement-sha-1.html) la collision de cet algo dans l'année.

Je propose donc que nous migrions aussi vite que possible la gestion des mots de passe vers un algo plus actuel.
La procédure pourrait être comme suit : 
- à la création d'utilisateur : création directement avec le nouvel algo
- au login, confrontation du mot de passe passé avec le hash du nouvel algo de chiffrement
  - si la vérification est OK, on passe
  - sinon, confrontation du mot de passe passé avec le hash MD5
    - si la vérification est OK, on chiffre avec le nouvel algo, on stocke ce dernier et on passe
    - sinon, échec de l'authentification

De cette façon, la migration se fera très vite.

Il est à noter que la colonne `conges_users.password` a une dimension particulière, il faut donc trouver un chiffrement robuste dans cette dimension si on ne veut pas d' `alter table`.

Nous pouvons nous appuyer pour cela sur les fonctions [password_verify](http://php.net/manual/fr/function.password-verify.php) et [password_hash](http://php.net/manual/fr/function.password-hash.php)
L'api n'est bien évidemment pas à oublier.

**Comment by Prytoegrian** [comment]
Il y a la modif de mot de passe à faire évoluer

**Comment by wouldsmina** [comment]
> Il y a la modif de mot de passe à faire évoluer

J'ai mis en place ce garde fou : 
https://github.com/Libertempo/Libertempo-web/pull/445/files#diff-f9389f5654a7afb8e5df2e3e54b66fbcR111

C'est plus cohérent qu'actuellement :angel:

**Comment by Prytoegrian** [comment]
NB : l'api a déjà été faite. Il faut donc suivre le choix du nouvel algorithme de chiffrement fait là-bas.

**Comment by Prytoegrian** [comment]
Update : attention à la création de l'admin !
