### ISSUE TITLE
Nouveau calendrier 

### ISSUE THREAD

**Issue by ClementNoury** [Libertempo/Libertempo-web#451]
Pour le nouvel affichage qui sera disponible sur la version 1.10.

Dans notre société une requête de la direction et qu'un "simple employé" ne puisse accéder seulement au calendrier de son groupe(voir les différents congés de son équipe par exemple) et celui de son responsable (N+1).
Cependant voir le calendrier des autres sociétés du groupe n'a aucun intérêt  pour le reste des utilisateurs et donc souhaite leur refusé cet accès. Mais seulement aux employés les responsables pourraient toujours voir les groupes dont ils sont responsables.

La question est la suivante : y-a-t'il un intérêt d'étudier la possibilité de le rajouter ou il y a aucun intérêt à étudier cette requête trop particulière ?

Merci d'avance
Cordialement

**Comment by wouldsmina** [comment]
sur irc, nous avions plutôt discuté de permettre aux employés d'un groupe de voir leurs responsables dans le calendrier, non? 

ce que tu demande ici (un employé ne voit que son groupe) est déjà prévu dans le futur calendrier...

**Comment by Prytoegrian** [comment]
Clos par le déploiement du nouveau calendrier
