### ISSUE TITLE
Le solde des congés utilisateurs n'apparait pas dans le calendrier.

### ISSUE THREAD

**Issue by bopware** [Libertempo/Libertempo-web#452]
### Environnement
Linux / Apache 2.4 / PHP 5.6 / PhpMyAdmin 4.6.6
Dernières versions de Chrome / Firefox / Edge

### Configuration Libertempo 1.9.3 : 
Dans la rubrique 13 "Divers", tout est à TRUE excepté "L'affichage des demandes de congés des utilisateurs dans le calendrier".

Bonjour,

Lors de la consultation des congés via le calendier, aucun solde n'apparait (voir ci-dessous) :
1ère image : Libertempo 1.8.1
2e image : Libertempo 1.9.3

![capture1](https://user-images.githubusercontent.com/22081165/27588692-4b386aa2-5b49-11e7-88e2-6623c878a3b2.jpg)
![capture2](https://user-images.githubusercontent.com/22081165/27588691-4b35cfae-5b49-11e7-9171-6d6f5976d6ca.jpg)

Est-ce qu'il y a un nouveau paramétrage à mettre en place suite à cette nouvelle mise à jour ?

Bien cordialement.

**Comment by wouldsmina** [comment]
bonjour,

Le calendrier n'affiche plus les soldes des congés car cette information est personnelle. L'employé y a accès lors d'une demande et le responsable depuis la page principale.
