### ISSUE TITLE
congés à cheval

### ISSUE THREAD

**Issue by hassai** [Libertempo/Libertempo-web#457]
[Bug] Pour nous aider à corriger le bug dans les meilleures conditions, merci de prendre le temps de détailler ces quelques points

### Système et application

* Version de l'application : Libertempo 1.9 "Ceres"
* Avez-vous des notifications dans la console du navigateur : non
* Avez-vous des erreurs dans le log du serveur http (ex : /var/log/apache2) : non
    
Bonjour,

Pourriez vous rajouter la gestion des congés à cheval + l'exportation des jours de congés pris par un utilisateurs ou plusieurs pour un mois donné ... ?

Merci d'avance

**Comment by wouldsmina** [comment]
Bonjour,

que veux tu dire par congés à cheval? les chevauchement de congés sont impossible normalement, peut être as tu rencontré un bug? donne nous plus d'informations...

Au sujet de l'exportation il y a déja 2 tickets à ce sujet #261 et #415 :)

**Comment by hassai** [comment]
Bonjour,

Je parle d'un congé qui affecte deux mois par exemple, toute la durée du congé est comptabilisé sur le premier mois, et aussi dans le Calendrier, le congé ne s'affiche pas sur les pages du mois suivant ...

Pour clarifier je vous donne un exemple : 
Un congé du 27 juin au 5 juillet = 7jours.
Dans la base vous le considérer :
juin = 7 jours
Mais pour l'extraction de donnée et pour faire les fiches de paie, le mieux c'est de considérer : 
Juin = 4jours
Juillet = 3jours

Et merci d'avance
  

Cordialement
Hassai othmane

**Comment by wouldsmina** [comment]
alors dans ce cas, il y a #433 à ce sujet. Tu trouvera la réponse dessus...
a+
