### ISSUE TITLE
Dupliquer l'accès BDD côté web et supprimer upgrade.sh

### ISSUE THREAD

**Issue by Prytoegrian** [Libertempo/Libertempo-web#458]
C'est une mauvaise approche de ma part de demander aux utilisateurs d'exécuter le script `upgrade.sh`, nous devrions plutôt le mettre dans le corps de page web durant le processus d'installation.
J'ai vérifié, côté droit d'accès, ça ne devrait pas poser de problèmes. Si je me trompe, ça se verra vite.

**Comment by Prytoegrian** [comment]
J'aurais voulu m'y atteler, mais il y a un truc sur les droits d'accès que je ne saisis pas, la création / modif de fichier de fonctionne pas dans le docker via la page web.

**Comment by wouldsmina** [comment]
c'est parce que l'UID de www-data de ton docker, ne correspond pas au propriétaire de tes fichiers. Tu peux contourner cela en modifiant l'UID de www-data dans le docker afin qu'il corresponde à l'UID propriétaire des fichiers... ([source](https://github.com/docker-library/php/issues/222)).

**Comment by Prytoegrian** [comment]
JTM :heart: 

J'en était arrivé à la même conclusion mais j'avais pas pensé à modifier l'UID !  :1st_place_medal:

**Comment by wouldsmina** [comment]
tu as les UID dans /etc/passwd
