### ISSUE TITLE
Lien vers la version Libertempo 1.9 Ceres

### ISSUE THREAD

**Issue by howvrell** [Libertempo/Libertempo-web#469]
Bonjour,

est-il possible d'avoir le lien de téléchargement pour Libertempo 1.9 Ceres.
ou est-ce que Libertempo 1.9.3 Ceres peut être téléchargé directement en lieu et place de Libertempo 1.8.1 Quinnis ?

Merci bcp

**Comment by Prytoegrian** [comment]
Hello,

Toutes les versions, dont `Ceres`, sont accessibles sur le [blog](http://libertempo.tuxfamily.org/downloads/). Pense à bien faire une sauvegarde avant la montée en version pour repartir de zéro en cas de problème ; à partir de `Kantra` (1.10), ce sera fait automagiquement.
