### ISSUE TITLE
Le responsable ne peut ajouter d'absence à un subalterne sur sa propre période de congés

### ISSUE THREAD

**Issue by exyl** [Libertempo/Libertempo-web#473]
Je me suis aperçu qu'en tant que manager, je ne peux ajouter d'absence pour un collaborateur si ses absences sont pendant mes congés : 

> attention: cette période chevauche d'autres congés !
ERREUR ! Les valeurs saisies sont invalides ou manquantes !!!

**Comment by Prytoegrian** [comment]
caeb530b155e3463b7fd6c2f34890c6671ad3cab Mergé
