### ISSUE TITLE
Ajout planning.

### ISSUE THREAD

**Issue by exyl** [Libertempo/Libertempo-web#485]
Hello,

J'ai 3 nouveaux utilisateurs depuis cet été.
Je viens de les importer dans Libertempo.
Mais pour les associer au planning par défaut (identique pour tout le monde), j'ai du passer par la base de données direct.
On ne peut pas via la fiche de l'utilisateur. 
Et depuis le planning, je bloque car des congés sont en attente parmi des utilisateurs du planning.

**Comment by Prytoegrian** [comment]
Hello!
Tu nous fait un constat d'un comportement en défaut, quel comportement attendrais-tu ?

**Comment by exyl** [comment]
Salut,
Soit de pouvoir ajouter un planning depuis la fiche utilisateur.
Soit depuis la fiche planning d'ajouter l'utilisateur. Mais là, j'étais bloqué car dans ce planning, des congés étaient en attente d'approbation.
