### ISSUE TITLE
[Bug ?] : pas de prise en charge de la CSS pour le calendrier (v1.10)

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#493]
Hello,

upgrade d'une version bac-à-sable de la 1.8 vers la 1.10 (serveur debian jessie virtuel, à jour).
le fameux calendrier ne m'affiche rien en terme de look : j'ai bien les données (nom des  users, date, et des éléments comme "*weekend" ou "*conges") mais pas les éléments graphiques (border, color,background-color).

rem : j'essaierai une install from scratch un peu plus tard.

**Comment by wouldsmina** [comment]
Salut @LRCorwin 
c'est un problème que nous connaissons, nous devons versionner les assets pour ne plus avoir ce problème à l'avenir. En attendant, il te suffit de rafraîchir le cache de ton navigateur (ctrl+F5 ou ctrl+r)

**Comment by LRCorwin** [comment]
hello @wouldsmina 

quel âne !
Je n'avais pas pensé à vider le cache.
ça marche en effet, merci !

**Comment by Prytoegrian** [comment]
T'es pas un âne, c'est normal, il n'est attendu de toi que tu fasses ça, c'est à nous de gérer le cas. Un ticket est déjà prévu d'ailleurs, mais d'autres choses passent toujours avant https://github.com/Libertempo/Libertempo-web/issues/406
