### ISSUE TITLE
[Bug ?] : crash en accédant à la gestion des plannings

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#494]
Hello,

lors d'un clic sur l'onglet "liste des plannings", j'obtiens ce message d'erreur : 
_uri   : /libertempo/hr/hr_index.php?onglet=liste_planning
dump  : ../dump/sql_2017-10-02T11:46:38+02:00.dump

file  : /var/www/html/libertempo/includes/SQL.php
line  : 85
fx    : $SQL->query
error : Table 'conges.planning' doesn't exist
sql   : SELECT planning_id AS id
                FROM planning
                WHERE status = 1_

Instance virtuelle sur debian jessie, version de libertempo 1.10 en mise à jour depuis la 1.8.1

**Comment by wouldsmina** [comment]
tu n'as pas eu d'erreur durant l'upgrade??

**Comment by wouldsmina** [comment]
est ce que tu as un champ `planning_id` dans la table conges_users?
est ce que tu as un champ  `token` dans la table conges_users?

**Comment by LRCorwin** [comment]
si je fais "installation d'une nouvelle instance", puis restauration de mon backup : c'est bon.
Curieux non ?

**Comment by LRCorwin** [comment]
pour tes questions : non, et je n'avais pas la table conges_planning non plus....

**Comment by wouldsmina** [comment]
J'ai l'impression que ta BDD n'a pas été mise a jour. Tu a quel version dans conges_config?

**Comment by LRCorwin** [comment]
version 1.10
cela étant ma seconde manip' qui a consisté à reprendre de zéro la partie
BdD semble donner meilleurs résultats.
Il faut garder à l'esprit que venant des premières versions php_congés,
j'ai régulièrement des soucis lors des upgrades... ça fonctionne mieux en
vidant la bdd, en faisant la màj puis en important une sauvegarde....

**Comment by Prytoegrian** [comment]
Si ça peut t'aider à l'avenir, nous avons fait un mécanisme de sauvegarde auto de la db à la maj. Je suis sur mobile, je peux pas trouver la pr mais elle ne devrait pas être loin.

**Comment by LRCorwin** [comment]
ça vaut le coup d'avoir ça pas loin, oui, merci :)

**Comment by Prytoegrian** [comment]
https://github.com/Libertempo/Libertempo-web/pull/390 :-*
