### ISSUE TITLE
[Kantra / V1.10] : plusieurs remarques IHM

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#495]
Hello,

sur la V1.10 toujours, après un upgrade depuis la 1.8.1 :

** lorsqu'un utilisateur accède au calendrier, par défaut, il est sur "tous"
est-il possible d'avoir la vue du groupe principal ? ou groupe par défaut ? (si tant est que cette notion existe....)

** lorsque l'utilisateur est sur son onglet "user_conge", sous le tableau récapitulatif, il y a la liste des congés : celle-ci a l'air de concerné TOUS les congés posés depuis qu'il a accès à l'appli
est-il possible de n'avoir QUE l'année en cours ?
d'ailleurs, techniquement, ce n'est pas "liste des congés" qu'il faudrait libeller, mais "liste des absences"...

**si l'on accède à la fonction "édition papier", il n'y a pas de bouton "retour"
ajout d'un bouton ? ouverture dans un nouvel onglet / nouvelle fenêtre ?

C'est tout pour le moment ;-)

**Comment by LRCorwin** [comment]
ok : vider le cache du navigateur résout les problèmes de libellés !

**Comment by wouldsmina** [comment]
tu peux modifier ton premier commentaire pour ne laisser que les problèmes toujours d'actu stp?
Ce sera plus simple pour moi pour faire le tri :see_no_evil:

**Comment by LRCorwin** [comment]
ça marche !

**Comment by wouldsmina** [comment]
et merci pour tes retours, il vont nous être utile :kissing_cat:

**Comment by LRCorwin** [comment]
avec plaisir :)
je continue à "gratter" du côté du calendrier qui était LA fonction attendue ^^

**Comment by wouldsmina** [comment]
>** lorsqu'un utilisateur accède au calendrier, par défaut, il est sur "tous"
est-il possible d'avoir la vue du groupe principal ? ou groupe par défaut ? (si tant est que cette notion existe....)

Comme tu l'as compris, il n'y a pas de groupe par défaut, donc difficile de choisir un groupe plutôt qu'un autre. Par contre tu remarqueras que "Tous" veut dire tous les groupes auxquels tu appartiens.

**Comment by LRCorwin** [comment]
Ok.
Est-ce qu'on peut se garder ça en "feature request" pour une prochaine version, s'il y a d'autres utilisateurs intéressés ? Ajouter une notion de "groupe préféré" dans la fiche du user lors de sa création ? Si rien n'est donné, le "tous" sera le défaut.

**Comment by wouldsmina** [comment]
on peut :) si le besoin ce fait ressentir on cherchera une solution
je t'invite à créer un ticket pour chaque demande, ce sera plus simple à suivre. Merci.

**Comment by wouldsmina** [comment]
ping @LRCorwin : un ticket par demande stp

**Comment by LRCorwin** [comment]
Hello,
je vous avais oublié ;)

**Comment by LRCorwin** [comment]
c'est fait !
