### ISSUE TITLE
[Kantra / V1.10] : gestion des jours RTT ou temps partiels hedbomadaires

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#496]
Hello,

juste pour être sûr...
je note que dans la fiche des utilisateurs, le calendrier semaine paire/semaine impaire a disparu.
En parallèle, avec l'upgrade depuis la 1.8.1, mon affichage de calendrier perd donc la visualisation de ces jours ou demi-journées "off" (on gère de manière identique les RTT et les temps partiels).
J'en déduis donc qu'il faut créer autant de planning qu'il y a de cas de figure pour les utilisateurs et affecter à chacun celui qui lui correspond.

Correct ?
C'est la nouvelle logique ?

**Comment by wouldsmina** [comment]
> J'en déduis donc qu'il faut créer autant de planning qu'il y a de cas de figure pour les utilisateurs et affecter à chacun celui qui lui correspond.

C'est tout a fait ça. Le nouveau planning a fait son entrée dans Ceres. Tu trouvera la [documentation ici](http://libertempo.tuxfamily.org/documentation/gestion-des-plannings/)

**Comment by LRCorwin** [comment]
ok !
du coup, je retombe sur ma demande #497 pour "voir" l'application d'un planning sur la fiche du user.
On peut clore ce ticket si tu veux.
