### ISSUE TITLE
[Kantra / V1.10] : fiche d'ajout d'un user, pas de champ "planning"

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#497]
serait-il possible d'avoir un champ qui permette l'affection d'un planning lors de l'ajout d'un nouvel utilisateur ?

Là, si je comprends bien, il faut : 1/ créer le user, 2/ aller dans la gestion des plannings, éditer le "bon" planning, et 3/ l'affecter au user...

Question Bonus : comment est géré le fait qu'un utilisateur puisse avoir un planning affecté sur son nom alors qu'un autre planning est associé au groupe dont il est membre ?

**Comment by Prytoegrian** [comment]
Hello,

c'est exactement ça. L'objectif est double : 
* avoir qu'une seule manière de faire les choses
* faire l'association employé <> planning à l'endroit où il y a le plus de contexte

Mais on est là pour discuter du bien fondé de cette décision.

Il n'est pas possible d'affecter un planning à un groupe en tant que tel. Tu peux m'en dire plus ?

Par contre, tu triches, le planning est une fonctionnalité de `1.9` :tongue:

**Comment by LRCorwin** [comment]
non, mais je triche à moitié seulement : on n'avait pas fait le saut à 1.9 à cause du calendrier :)

Et puis, non, vous avez eu raison de choisir l'affectation à un user et pas à un groupe. Je vois bien les risques de collision. Vrai que ça va être fastidieux au départ de créer "n" planning en fonction de tous les cas de figure, mais c'est plus sage de les affecter un à un.

On peut fermer cette discussion.
