### ISSUE TITLE
Compatibilité avec PHP 7

### ISSUE THREAD

**Issue by Tera-Two** [Libertempo/Libertempo-web#498]
Bonjour,

Une question simple : A ce jour, Libertempo peut-il fonctionner avec PHP 7 ?

**Comment by wouldsmina** [comment]
Salut,
 Je fais mes tests dessus depuis près de 12 mois sans rencontrer de problème bloquant.

Il y a tout de même un warning au sujet d'un «deprecated» mais ça ne devrait pas poser de problème.

**Comment by Prytoegrian** [comment]
Ça vaut ce que ça vaut, mais nous avions déjà fait [un passage](https://github.com/Libertempo/Libertempo-web/issues/117#issuecomment-219782981). Ça a l'air d'être compatible, même si nous (j'ai ?) n'avons pas encore eu la volonté de pousser l'appli à fond pour voir la compat'.
Cela étant, comme le dit @wouldsmina, un an d'utilisation te donne un bon niveau de confiance.

**Comment by Tera-Two** [comment]
Ok, du coup, il n'y a pas de raison que ca ne tourne pas chez moi.
Merci !
