### ISSUE TITLE
[Kantra / V1.10] : remarques IHM -> groupe préféré ?

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#507]
Hello,

sur la V1.10, lorsqu'un utilisateur accède au calendrier, par défaut, il est sur "tous"
est-il possible d'avoir la vue du groupe principal ? ou groupe par défaut ? (si tant est que cette notion existe....)
Ajouter une notion de "groupe préféré" dans la fiche du user lors de sa création ? Si rien n'est donné, le "tous" sera le défaut.

**Comment by wouldsmina** [comment]
salut,

Nous avons malheureusement déjà beaucoup à faire, cette fonctionnalité ne me paraissant pas crucial, je vais devoir recaler ta demande (disons pour le moment).

désolé.
