### ISSUE TITLE
[Kantra / V1.10] : remarques IHM -> 

### ISSUE THREAD

**Issue by LRCorwin** [Libertempo/Libertempo-web#509]
Si l'on accède à la fonction "édition papier", il n'y a pas de bouton "retour" : 
ajout d'un bouton ?
ouverture dans un nouvel onglet / nouvelle fenêtre ?

**Comment by wouldsmina** [comment]
+1 pour "retour"

**Comment by Prytoegrian** [comment]
C'est prévu dans les cartons, mais je sais pas quand ça pourrait sortir (@wouldsmina a déjà aperçu la nouvelle interface).

**Comment by Prytoegrian** [comment]
Mergé dans develop. Ce sera donc pour la sortie de Mondaran.
