### ISSUE TITLE
Pas de décompte du solde lorsqu'il subsiste un reliquat.

### ISSUE THREAD

**Issue by regismarion** [Libertempo/Libertempo-web#511]
Bonsoir à tous,
suite au chat IRC de ce soir, je dépose un ticket pour mémoire.

J'ai constaté que lorsque qu'une personne avec un reliquat de congés pose des jours de congés, le le reliquat et bien décrémenté, mais le solde ne bouge pas.

Exemple : à la bascule au 31 août il me restait 13 jours de congés. Pour la nouvelle année universitaire j'ai un droit à congés de 55 jours. J'ai donc dans LT un solde de 68(dont 13 de reliquat). 

Je pose 5 jours de congés. Ces congés sont validés par ma N+1. LT m'affiche un solde de 68(dont 8 de reliquat.

Un coup d'oeil à la base de donnée, j'ai la même chose.
Merci pour votre aide

LT 1.9.3

**Comment by regismarion** [comment]
merci pour ta rapidité.
Je teste cette modification rapidement.

**Comment by wouldsmina** [comment]
attend, c'est pas encore tout a fait pret :smile:

**Comment by wouldsmina** [comment]
maintenant c'est prêt à être testé, mais c'est pour le moment basé sur la branche `develop` (une petite erreur de ma part). Si tu veux tester il faudra exécuter la mise à jour (dans un environnement de test bien sur, pas sur ta prod :smiley_cat: ). une fois le correctif validé, nous livrerons évidement une nouvelle version mineure de 1.9

**Comment by regismarion** [comment]
Bonjour,
j'ai testé c'est OK.
J'ai encore une remarque toujours liée à cette histoire de solde. MAis là j'imagine que cela va être plus compliqué à résoudre. C'est un mécanisme plus profond à modifier.
Je m'explique : 
Un utilisateur à un solde de 40 jours dont 10 jours de reliquat. Je le note 40(10)
Il pose 5 jours de congés. Son responsable valide sa demande. Le solde passe à 35(5) 
Jusque là tout va bien! (depuis ton dernier patch, merci).
Là ou cela se gâte c'est lorsque son responsable, ou les Rh annule sa demande de congés. 
Son solde devient 40(5) !!! et non pas 40(10)

J'imagine qu'il n'y aura pas de solution dans la mesure ou on ne conserve pas dans la table conges_periode le nombre de jours pris sur le reliquat.

Mais peut-être une amélioration dans une future version

Bien cordialement

**Comment by wouldsmina** [comment]
Oui, j'ai constaté cette effet de bord il y a déjà longtemps, mais ne pouvant différencier un reliquat d'un solde normal je n'avais pas pu corriger. Cela impliquerait beaucoup de changement dans la bdd, ça viendra peut être un jour, mais pas dans l'immédiat.

a+
