### ISSUE TITLE
Lisibilité du calendrier BETA 

### ISSUE THREAD

**Issue by Nulos** [Libertempo/Libertempo-web#513]
Bonjour,

Suite à l'ouverture de l'issue : "Lisibilité du calendrier #488" j'ai mis a jour en beta pour avoir une meilleur lisibilité du calendrier.

Dans cette version nous récupérons bien un calendrier linéaire, mais il n'y a aucune différence de couleur ou description  entre un rtt / congé / arret maladie/ etc ... 

Est-ce qu'il y a un réglage à faire? Est-ce possible de prévoir une différence de couleur ainsi que plus d'informations comme dans la version 1.8 ?

D'avance merci de votre aide.

**Comment by stillcut** [comment]
Je plussoie.

**Comment by wouldsmina** [comment]
nous avons fait le choix de ne pas "divulguer" ces informations sur le calendrier. Dites nous quelle est le besoin (pourquoi? pour qui, RH, resp, tous? ...), ça nous aidera a comprendre et à apporter la meilleur solution possible. Bien sur, si nous ne trouvons pas d'alternative satisfaisante nous remettrons cette fonctionnalité.

et au passage merci de tester la beta, ça nous aide à avancer :wink:

**Comment by Nulos** [comment]
Pour mon cas c’est notre RH et comptable qui utilisent le calendrier linéaire pour faire les bulletins et décompter rtt / congés / arrêt etc... et d’avoir les différentes couleurs ainsi que le type du congé dans la description ça aide énormément.  

Merci.

**Comment by LRCorwin** [comment]
bonjour,
on aurait "éventuellement" (c'est une demande, mais pas "forte") besoin de ça pour le rôle RH et le responsable : l'idée est de ne pas aller dans la fiche users pour se souvenir s'il y avait une raison particulière à certaines prises d'absences.

**Comment by regismarion** [comment]
Bonjour,
en ce qui me concerne, je suis plutôt favorable à un planning sans information comme cela semble être le cas dans la version Beta.
Les plannings de présence sont des informations importantes à partager au sein même des équipes pour des raisons évidentes de fonctionnement, de management et d'animation. En revanche les raisons pour lesquelles une personne est absentes doivent pouvoir rester confidentielles et uniquement partagées avec le N+1 et/ou les RH. 
De ce fait l'utilité de qualifier les absences dans le planning dépend de l'utilisation faite de cette fonctionnalité. Pour ma part, comme nous souhaitons que les plannings soient une information utile au plus grand nombre, la neutralité et la confidentialité sont une grande avancée.
Merci

**Comment by JEPlevallois** [comment]
Je rejoins les commentaires précédents  sur : 
- la neutralité nécessaire pour les utilisateurs par défaut (auquel cas indiquer "absence" et non "congé" au survol afin de ne pas laisser supposer que certains bénéficient de plus de jours de congés en créant la confusion avec les arrêts maladie ou les récups)
- le besoin pour les utilisateurs RH, admin et responsable de pouvoir distinguer facilement visuellement les différents types de journées

Merci !

**Comment by Prytoegrian** [comment]
Ok, on s'approche d'un truc pas mal. À but de discretion, les employés « normaux » n'ont qu'une information neutre, tandis que les responsable et RH ont davantage de détails. J'ai toutefois une question : être responsable suffit-il a voir les infos détaillées ou faudrait-il être *responsable de l'employé *N exclusivement, les autres retombant dans le cas par défaut ?
Je pense qu'il n'est pas nécessaire de poser la question pour le RH (il voit par défaut tout), mais si vous avez des remarques, je prends aussi.

**Comment by regismarion** [comment]
Bonjour,
de mon point de vue, être responsable donne la légitimité à connaitre les raisons des absences de ses subordonnés (puisque le responsable doit valider les absences), mais cette légitimité n'est pas valable vis à vis  des membres des autres groupes pour lesquels le responsable n'a potentiellement aucun lien hiérarchique. 
En clair un responsable n'a le détail des absences que pour les groupes dont il est responsable ou grand responsable. 
Mais ce n'est que mon point de vue.
Bonne journée

**Comment by ClementNoury** [comment]
Bonjour,
Même cas de notre côté seul la direction et la RH doivent pouvoir avoir accès à cette information pour tous les employés.
Les responsables l'ont seulement pour le groupe dont ils sont responsable.
Bonne journée

**Comment by wouldsmina** [comment]
doublon #488
