### ISSUE TITLE
[Kantra V1.10] calendrier

### ISSUE THREAD

**Issue by JEPlevallois** [Libertempo/Libertempo-web#514]
Bonjour,

merci pour cette nouvelle version qui semble très prometteuse ! 

Je regrette en revanche plusieurs points quant à la présentation du calendrier qui sont des freins pour envisager le déploiement de libertempo auprès de mon équipe
- les jours non travaillés par un agent en particulier n'apparaissent pas en grisé (exemple un temps partiel qui ne travaille jamais le mercredi ; autre exemple équipes alternées l'une du lundi au vendredi, l'autre du mardi au samedi, ce qui est permis par la gestion des semaines différentes)
- les absences, quelle qu'en soit la raison, sont toutes indiquées "congé" au survol et ne sont pas différenciées par un code couleur ; je voudrais a minima pouvoir distinguer une absence (maladie...)  d'un congé

Par ailleurs la perte de la gestion des heures de recup me semble vraiment regrettable, surtout dans la mesure où le planning rentré indique clairement les plages horaires travaillées. Imaginer avoir un outil pour gérer les congés d'une part, et un autre pour gérer les heures de récup (et notamment avoir un nombre suffisant d'agents pour assurer les ouvertures et les fermetures) serait tout à fait regrettable et m'incite à continuer d'utiliser un tableur avec tous les inconvénients que cela représente.

D'avance merci pour votre retour et encore un grand merci pour le travail engagé sur libertempo !

**Comment by Prytoegrian** [comment]
> la perte de la gestion des heures de recup me semble vraiment regrettable

Bonjour,
rien n'a été fait dans ce sens, il s'agit donc d'un Bug. De ce fait, il nous faudra davantage d'informations sur l'état de ton système pour le corriger (l'état des options notamment).

**Comment by JEPlevallois** [comment]
Merci pour cette rapide réponse !

Je ne peux donner d'information n'ayant pas déployé Libertempo, mais dans la version de demo je n'ai pas accès à la possibilité de déclarer (ou approuver selon le profil) un changement d'horaire, que ce soit pour indiquer des heures sup, ou un départ anticipé par exemple.

**Comment by wouldsmina** [comment]
l'option était désactivé et la restauration automatique était planté, c'est réparé.

**Comment by JEPlevallois** [comment]
Bonjour,

depuis hier je souhaite du coup tester de nouveau le planning, mais plusieurs utilisateurs par défaut de la démo semblent avoir été supprimés, nuisant considérablement au process. 

Pouvez-vous réinitialiser la démo ?

D'avance merci  !

**Comment by regismarion** [comment]
Bonjour,
je teste en local sur un MAMP la version KANTRA. Je fais ici mes premières remarques : 
1. Le grand responsable ne voit pas les congés  en deuxième validation dans l’onglet traitement de congés
2. Pas de pastille (badge) dans l’onglet traitement de congés pour le grand responsable quand il a un congés à valider
Bien cordialement

**Comment by wouldsmina** [comment]
@regismarion : nouveau bug == nouveau ticket. Si tu laisse ton commentaire ici, on risque de le zapper et de fermer le ticket une fois les corrections effectuée sur le calendrier

**Comment by wouldsmina** [comment]
@JEPlevallois encore désolé, c'est rétabli et je cherche la raison pour laquelle la restauration quotidienne de la démo ne fonctionne pas.

**Comment by JEPlevallois** [comment]
Merci @wouldsmina !

Concernant les jours (ou demies-journées) non travaillés par un agent qui n'apparaissent pas en grisé, Est-ce que j'ouvre un autre ticket ?

Belle journée.

**Comment by wouldsmina** [comment]
doublon #488
