### ISSUE TITLE
Impossible de poser une heure additionnelle quand un collègue à posé un congé

### ISSUE THREAD

**Issue by massonfr** [Libertempo/Libertempo-web#530]
Si j'ai bien compris le code, le test ne se limite pas à l'utilisateur courant, mais se fait pour l'ensemble des utilisateurs.
Patch ci-joint.
[AHeure.patch.txt](https://github.com/Libertempo/Libertempo-web/files/1458159/AHeure.patch.txt)

**Comment by wouldsmina** [comment]
Bonjour,
Merci pour cette correction. Je vais tester ça rapidement.

**Comment by wouldsmina** [comment]
corrigé. ce sera inclut dans la prochaine version, alias Mondaran

**Comment by Prytoegrian** [comment]
Fixé par https://github.com/Libertempo/Libertempo-web/pull/531
