### ISSUE TITLE
faute d'orthographe

### ISSUE THREAD

**Issue by regis** [Libertempo/Libertempo-web#543]
https://github.com/Libertempo/Libertempo-web/blob/520ad1e285cfbbd9c7090469ea9fa9d313b1489d/locale/fr_FR/LC_MESSAGES/php-conges.po#L1818

"Chevauchement avec une heure validé ou en attente de validation" -> "Chevauchement avec une heure validée ou en attente de validation"

**Comment by wouldsmina** [comment]
merci
