### ISSUE TITLE
CET

### ISSUE THREAD

**Issue by jmv42** [Libertempo/Libertempo-web#547]
Bonjour,

On me demande de gérer les compte épargne temps dans libertempo
Est ce prévu a court terme ?

Je voulais contourner avec un type de congé exceptionnel ou ordinaire mais j'ai peur que les compteurs soient remis a zéro lors de la date d'expiration des reliquats

Merci

**Comment by wouldsmina** [comment]
Bonjour,

oui c'est prévu (#270). à court terme? Je ne pense pas, on a déja beaucoup à faire avec les fonctionnalités actuel...
