### ISSUE TITLE
Un point qui traîne près du bouton "Retour" dans la partie demande d'un congé

### ISSUE THREAD

**Issue by hedus** [Libertempo/Libertempo-web#571]
On trouve des `!<br><br>.` dans `utilisateur/Fonctions.php`.
En plus du point, le point d'exclamation semble inutile car les phrases traduites en contiennent déjà.

**Comment by Prytoegrian** [comment]
Merci d'avoir rapporté. Puisque tu me parles de br, tu as pu localisé où était le bout de code incriminé ; je t'invite donc à créer une PR. Profite de la fenêtre de tir, au moins de février nous gelons les devs.
