### ISSUE TITLE
Faille XSS

### ISSUE THREAD

**Issue by vguede** [Libertempo/Libertempo-web#574]
Bonjour,

Vous avez une faille XSS sur la page http://demo.libertempo.fr/hr/hr_index.php?onglet=traite_user&user_login=xxx
En effet, le commentaire de la demande de congés n'est pas correctement échappé.

**Comment by Prytoegrian** [comment]
Salut,

tu aurais un exemple de ce que tu as tapé pour tester la XSS ? j'ai besoin de la tester pour savoir si c'est toujours d'actualité.

**Comment by vguede** [comment]
Bonjour,

Je n'ai actuellement qu'une grosse instance de prod (tous les
établissements scolaires de l'académie de Bordeaux) sur laquelle je ne peux
pas faire de tests d'intrusion.
Si tu as une instance de test accessible je pourrai prendre un moment
demain pour faire des tests de sécurité manuels.

Vincent Guédé

**Comment by vguede** [comment]
Excuse moi pour le message précédent, j'ai confondu avec une autre
application. Je te réponds demain.

Le mar. 8 mai 2018 à 21:37, Vincent Guédé <vincent.guede@gmail.com> a
écrit :

**Comment by vguede** [comment]
En attendant, voici le rapport d'audit de code via checkmarx. Nous avons
confirmé par analyse manuelle la quasi totalité des failles de sévérité
high.

Le mar. 8 mai 2018 à 21:46, Vincent Guédé <vincent.guede@gmail.com> a
écrit :

**Comment by Prytoegrian** [comment]
Ok, reproduis. Je m'y colle, merci !
