### ISSUE TITLE
En cas de mise à jour, la présence du htaccess prévu dans le dossier api n'est pas vérifié

### ISSUE THREAD

**Issue by hedus** [Libertempo/Libertempo-web#579]
La procédure d'installation prévoit la mise en place d'un fichier `.htaccess` dans le dossier `api` pour que l'api fonctionne (voir `\install\Fonctions::addInstanceName`) mais en cas de mise à jour, l'existence de ce fichier n'est pas contrôlé.

**Comment by Prytoegrian** [comment]
Merci hedus d'avoir vérifié ça ! Je soupçonnais un truc du genre quand tu en parlais ; si tu as pu confirmer, ça nous facilite la tâche. C'est ça qui vous donnait des lenteurs ?

**Comment by wouldsmina** [comment]
J'ai mis à jour la documentation afin de prendre en compte ce point. C'est une solution temporaire, ça nous laissera le temps de corriger ça lorsqu'on reprendra le module d'installation dans son ensemble.
