### ISSUE TITLE
Authentification : problème de session

### ISSUE THREAD

**Issue by hedus** [Libertempo/Libertempo-web#580]
C'est un cas particulier chez nous où on fait du SSO avec une authentification RSA et on passe donc une seule fois dans le `index.php` pour s'authentifier.
La première fois, ça fonctionne car la session est vide mais si on revient plus tard dans l'application et que la session est toujours active, le problème survient.

Le dysfonctionnement vient de la fonction `init_config_tab` pour mettre la conf en session et à l'utilisation de `session_destroy` suivi du `session_create` qui relance la session, on perd alors certaines informations qui devraient figurer dans la session (`u_nom` et `u_prenom` par exemple) :
1. le `init_config_tab` au début du `index.php` calcule la conf, met en session `u_nom` et `u_prenom` notamment et comme `$_SESSION['userlogin']` existe, il le retient
2. `session_destroy` dans `index.php`  suivi de `session_start` dans `session_create` vide `$_SESSION`
3. `$_SESSION` est réalimenté en rappelant `init_config_tab` dans `session_create`
4. `init_config_tab` considérant que la conf a déjà été récupérée, retourne ce qu'il a calculé la première fois sans remettre en session `u_nom` et `u_prenom`

Dans le cas d'une authentification via un formulaire login/password, le `session_destroy` est fait avant l'affichage du formulaire et donc à l'envoi du formulaire, `$_SESSION` étant vide au premier appel de `init_config_tab` au début du `index.php`, la fonction détecte l'absence d'utilisateur et à l'appel suivant (dans `session_create`), la présence de l'utilisateur déclenche le recalcul des informations et tout se passe donc bien.

**Comment by wouldsmina** [comment]
corrigé dans #565
