### ISSUE TITLE
Prendre en compte le solde de congés

### ISSUE THREAD

**Issue by kam0k** [Libertempo/Libertempo-web#592]
Bonjour,

Je suis actuellement en train de faire une série de tests sur libertempo pour le mettre en place au sein de mon organisation. Mais je me suis rendu compte de le solde de congés à part être affiché n'était pas vérifié.
Le solde peut passer au négatif et donc cela fausse toutes les informations générées par la suite.
Est ce un comportement voulu ou non ?

Cordialement,

**Comment by wouldsmina** [comment]
Bonjour,

Cela ne fausse en rien les informations, lors du changement d'exercice le solde négatif est déduit du nouveau solde. Si tu ne veux pas de solde négatif il te suffit de modifier l'option dans la configuration générale.
a+
