### ISSUE TITLE
Nombre de jours ne se calcule pas

### ISSUE THREAD

**Issue by Bastiencc** [Libertempo/Libertempo-web#593]
Bonjour

Je viens d'installer Libertempo en locam (wamp) pour tester. Lorsque j'ajoute un congés, le calcule du nombre de jour me retourne systématiquement 0. ai-je oublié quelque chose ?

merci pour votre aide

**Comment by wouldsmina** [comment]
Bonjour,

vérifie le planning associé à l'utilisateur. Tu n'as pas de message d'erreur?
