### ISSUE TITLE
Calendrier : des groupes manquent dans la liste dans certains cas

### ISSUE THREAD

**Issue by hedus** [Libertempo/Libertempo-web#595]
Le problème vient de ```\App\ProtoControllers\Utilisateur::getListeGroupesVisibles``` pour un responsable.
Les tableaux numériques sont mergés avec l'opérateur "+" mais celui-ci ignore une clé déjà présente dans le premier tableau :

> L'opérateur + retourne le tableau de gauche auquel sont ajoutés les éléments du tableau de droite. Pour les clés présentes dans les 2 tableaux, les éléments du tableau de gauche seront utilisés alors que les éléments correspondants dans le tableau de droite seront ignorés.

Illustration : https://softonsofa.com/php-array_merge-vs-array_replace-vs-plus-aka-union/

**Comment by Prytoegrian** [comment]
Afin de nous permettre de reproduire / tester dans les meilleures conditions, pour la prochaine fois, je t'invite à remplir le rapport de bug.
