### ISSUE TITLE
Libertempo 1.10 "Kantra" Avertissement service RH après double validation

### ISSUE THREAD

**Issue by Pompelup** [Libertempo/Libertempo-web#606]
Libertempo 1.10 "Kantra"

Bonjour,

Je reviens vers vous au sujet de l'avertissement auprès des utilisateur RH car après la double validation d'un congé d'un agent aucune notification ni avertissement remonte sur l'interface RH.
Comment le service RH peut être au courant du congé de l'agent ou des agents (après la double validation ) par notification sur l'interface ou mail?

Merci

**Comment by wouldsmina** [comment]
Bonjour,

Nous n'avons pas implémenté cette fonctionnalité. Il y a le ticket #226 à ce sujet. Je te laisse réagir directement dessus si tu le souhaites.

a+
