### ISSUE TITLE
duree_session does not work

### ISSUE THREAD

**Issue by benrubson** [Libertempo/Libertempo-web#627]
Hi,

With version 1.10 :
`duree_session` is set by default to 1800 seconds.
However it does not seem to work : session closes 1800 after login, not after 1800 seconds of inactivity.
Thus, session can close while user is browsing the application.

Debian 9 server with :
Apache 2.4
PHP FPM 7.0
MariaDB 10.1

Reproduced with Safari / Firefox.
No error log on server or in browser.

Sounds like timestamp is not updated in session file on server :
`userlogin|s:5:"admin";timestamp_start|i:1522621747;timestamp_last|i:1522621747`

Thx 👍 

Ben

**Comment by Prytoegrian** [comment]
Hi !

We'll not correct this default as #489 removes this option and hardcode the session duration ; the application will correct itself with an upgrade. However, thanks for reporting :cat:

**Comment by benrubson** [comment]
OK, thank you for your report @Prytoegrian, glad to hear this will be corrected in next version 👍
