### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by exyl** [Libertempo/Libertempo-web#630]
Bonjour à toute l'équipe,

Une question simple, je voudrais mettre à jour vers Kantra (1.10.2), et je suis en 1.9 Ceres.
Faut-il passer en Ceres 1.9.5 avant ?
Dans la doc, il n'est pas indiqué si l'on faire chaque montée de version , ou si on peut "sauter" les étapes.

Merci

**Comment by wouldsmina** [comment]
Salut,

tu peux passer d'une version majeur à l'autre sans passer par les mineurs, donc direct à la 1.10.2 :muscle: 

a+
