### ISSUE TITLE
09/05 : Pas férié

### ISSUE THREAD

**Issue by ocinlas** [Libertempo/Libertempo-web#631]
### Reproduction du bug

* Prérequis :
* Action de déclenchement :
* Résultat attendu :
* Résultat constaté :

impossible de changer le 09/05 de l'état ferié a "pas ferié"

Bizarre car ca fonction pour les autres jour a priori ca viendrai de la determination de jour ferie mais ou trouve il l'info ??

**Comment by wouldsmina** [comment]
Bonjour,

c'est un effet de bord du calcul automatique des jours fériés. Normalement, en décochant la case et en validant, le jour ne sera plus dans la base de donnée.Si tu veux vérifier, pense à te reconnecter pour rafraîchir la session. Tu peux aussi désactiver la gestion automatique des jours fériés dans la configuration (section divers).
