### ISSUE TITLE
Changer mot de passe admin Mondaran

### ISSUE THREAD

**Issue by pierr0t** [Libertempo/Libertempo-web#637]
Bonjour,
Pas sûr que ce soit ici qu'il faille poser ces questions mais comme je tourne en rond après une heure de recherche ... bref ... Je viens d'installer une Mondaran toute neuve à l'instant téléchargée du site et tout s'est bien passé aucune erreur, je me suis loggé no souci mais impossible de trouver ou changer le mot de passe admin ... j'ai utilisé le login admin et le mot de passe correspondant de la doc (donc carrément public) et la doc dit qu'il y a un bouton "configuration" en haut à droite ce qui n'est pas le cas (mais je suppose que la doc ne correspond pas à 100% à Mondaran), j'ai par contre un "configuration" à gauche mais rien pour changer ce mot de passe si ce n'est toutes les configs qui disent qu'un utilisateur peut ou pas changer de mdp, que l'admin peut ou pas changer le mdp des users etc ... Bref soit je suis total idiot soit y a un bug :-)
Merci.
Pierre.

**Comment by wouldsmina** [comment]
Bonjour,

En effet il y a une incohérence dans la gestion du mot de passe admin. L'installeur commence a montrer ses limites, on doit le reprendre de zero, j'espère le faire pour i prochaine version. En attendant, pour modifier le mot de passe admin, passe par le menu... utilisateur. 
A+

**Comment by pierr0t** [comment]
Non c'est pas si incohérent que ça, l'admin est un utilisateur ... c'est moi qui suit un idiot car j'y ai pensé et j'y suis allé et j'ai pas vu qu'il y avait un sous-menu pour ce changement. Merci pour cette réponse en week-end :-) Je vais poursuivre l'exploration !
Pierre.
