### ISSUE TITLE
Mondaran 1.11 - Perte des reliquats

### ISSUE THREAD

**Issue by jmv42** [libertempo/Libertempo-web#639]
Bonjour,

Sur la nouvelle version de démo http://demo.libertempo.fr poser un congé fait perdre tout ses reliquats

Exemple reproductible

Simon 30 jours dont 10 de reliquat
Date limite reliquats : 30/04
Le 26/04 il pose le 27/04 (fonctionne aussi avec le 03/05)
Marie valide la demande le 26/04
Le compteur de Simon affiche ensuite 19 jours et le reliquat complètement disparu !

Poser un jour de congé nuit très gravement a votre reliquat :(

Merci

**Comment by wouldsmina** [comment]
Je vais regarder ça, mais ca doit être a cause du champ conges_appli.date_limite... la bdd date de plusieurs années. Pour infos les précédentes versions le reliquats n'était simplement plus decrementé après  la date limite. Cela n'a pas de sens car le solde inclut toujours ce reliquat.

Ca va être dur pour les employés qui avaient repérés la combine :p

**Comment by wouldsmina** [comment]
A propos de la date de reliquat dans conges_appli,  c'est au format [aaaa-mm-jj](https://github.com/Libertempo/Libertempo-web/blob/develop/hr/Fonctions.php#L1836).

Je viens de tester le problème des reliquats sur la démo après avoir fait un changement d'exercice, le compteur ne revient pas à zero mais il y a peut etre un autre problème, je dois encore faire quelques vérifications...

**Comment by jmv42** [comment]
Merci, je regarde ca Lundi.
Mais ce que je peut dire cela n’était pas une affaire pour les employés car le reliquat disparaît mais aussi le solde général des congés donc mauvaise affaire !

Au contraire sur kantra, un tour de passe passe existe pour blanchir des jours de reliquats : 
1) poser des jours de reliquats
2) les faire refuser par ton responsable
3) ils sont alors recredités sans la mention "reliquats"

J'imagine que cela doit etre difficile a gerer coté dev, a moins peut etre de considérer 2 compteurs biens distincts (je n'ai aucune compétences en dev)

bonne soiree
