### ISSUE TITLE
quote en trop dans l'url d'export ICS

### ISSUE THREAD

**Issue by landryb** [Libertempo/Libertempo-web#641]
[Uniquement pour les bugs]

Sur /App/Views/Calendrier.php#L11 il y'a une quote en trop avant la value de usr (ie le lien généré est http://demo.libertempo.fr/export/ics_export.php?usr=%2748d164d298d19f4abf2494a957c071f82e5d79fe2674773ca41a93f60b143790), la quote est traduite en %27 et l'appli ne renvoie rien pour l'utilisateur. Si je supprime la quote de l'url l'export ICS se fait a priori correctement.

**Comment by wouldsmina** [comment]
c'est corrigé sur la beta, merci.
