### ISSUE TITLE
Affichage de la page planning impossible

### ISSUE THREAD

**Issue by teger** [libertempo/Libertempo-web#659]
**Décrivez le bug**
Quand je clique sur l'onglet planning ( par exemple avec un compte RH), une page blanche apparait.

**Pour reproduire**
Étapes de la reproduction du comportement :
1. Prérequis (rôle connecté, options de configuration, méthode de connexion, …) :
Compte RH connecté
2. Cliquer sur : 
Onglet Planning
3. Constater l'erreur : page blanche

**Poste (veuillez remplir les informations suivantes):**
 - Système: [i.e. iOS] : MacOS 10.13.4
 - Navigateur et version :  Firefox 60
 - Erreur dans la console :  Néant

**Serveur (veuillez remplir les informations suivantes):**
 - Système: [i.e. iOS8.1] : Debian 8
 - Version MySQL et PHP : Mysql 5.6 et PHP 5.6
 - Erreur dans le log du serveur : 

[22-May-2018 11:48:15 Europe/Berlin] PHP Fatal error:  Uncaught exception 'LogicException' with message 'Erreur client : Request -> GET /api/planning HTTP/1.1
User-Agent: GuzzleHttp/6.2.1 curl/7.38.0 PHP/5.6.33-0+deb8u1
Host: conges.nouveauxterritoires.fr
Token:
Content-Type: application/json
Accept: application/json

 | Response <- HTTP/1.1 404 Not Found
Date: Tue, 22 May 2018 09:48:15 GMT
Server: Apache
Content-Length: 289
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/planning was not found on this server.</p>
<hr>
<address>Apache Server at conges.nouveauxterritoires.fr Port 80</address>
</body></html>
' in /home/libertempo/www/App/Libraries/ApiClient.php:134
Stack trace:
#0 /home/libertempo/www/App/Libraries/ApiClient.php(63): App\Libraries\ApiClient->request('GET', 'planning', Array)
#1 /home/libertempo/www/App/Libraries/ApiClient.php(45): App\Libraries\ApiClient->securedRequest('GET', 'planning', in /home/libertempo/www/App/Libraries/ApiClient.php on line 134

**Comment by wouldsmina** [comment]
Ce ticket fait doublons avec #640. Je fermes, @teger tu peux toujours répondre sur #640 bien sur.
