### ISSUE TITLE
planning s'affiche pas avec un utilisateur spécifique

### ISSUE THREAD

**Issue by boule46** [libertempo/Libertempo-web#663]
**Décrivez le bug**
Bonjour,
Quand j'ajoute un utilisateur (que un seul les autres fonctionne, mais pas de différence sur l'AD) depuis ldap, le planning ne s'affiche pas. Pour cette utilisateur, le token est renseigner dans la table conges_user, pour les autres utilisateur il est vide. Quand je debug, le retour $plannings dans hr_liste_planning.php est juste le string token sans autre infos, quand cette utilisateur est effacer, le planning s'affiche nickel. Vous avez un idée d'ou ça vient? ou est générer le token avant de rentrer dans la base?
![libertempo-api ok](https://user-images.githubusercontent.com/10669927/40620196-3a82f784-6298-11e8-861b-347202a76214.PNG)
![libertempo api pas ok](https://user-images.githubusercontent.com/10669927/40620217-4b389d7c-6298-11e8-91d7-a4c74403baeb.PNG)

**Pour reproduire**
Étapes de la reproduction du comportement :
1. Prérequis (rôle connecté, options de configuration, méthode de connexion, …) :
2. Cliquer sur : 
3. Constater l'erreur : 

**Comportement attendu**
Une description claire et concise de l'attendu.

**Copies d'écran**
Si applicable, ajoutez des captures d'écran pour aider à expliquer le problème.

**Poste (veuillez remplir les informations suivantes):**
 - Système: [i.e. iOS] :
 - Navigateur et version : 
 - Erreur dans la console : 

**Serveur (veuillez remplir les informations suivantes):**
 - Système: [i.e. iOS8.1]
 - Version MySQL et PHP :
 - Erreur dans le log du serveur : 

**Contexte additionnel**
Ajoutez tout ce qui vous paraît utile pour la bonne résolution du défaut.

**Comment by Prytoegrian** [comment]
Bonjour et merci de remonter le défaut (et surtout de commencer à déboguer),

tout d'abord, je t'invite à mettre la prochaine fois la version du logiciel installée. Les autres informations sont utiles (et plus il y a en a, plus vite on trouvera la cause), mais s'il y en a bien une à ne pas oublier, c'est cette dernière. Elle nous permet de localiser le défaut dans le temps. Mais pour la suite, je vais partir du principe que tu es sur la 1.11 `beta`.

Le fait que tu dises que les autres utilisateurs n'aient pas de token en base me met la puce à l'oreille. Il y avait un tel bug, que j'ai corrigé par #649.
Le token sert à la communication à l'API, il est normalement généré par cette dernière lors de la connexion via la fonction `includes\fonction::storeTokenApi`.
Mais ça n'explique pas pourquoi pour cet utilisateur précis, au lieu de demander la liste des plannings, il cherche à se connecter. Je te laisse regarder de ton côté avec ta stack, tes données, etc ; je vais faire pareil de mon côté.
