### ISSUE TITLE
extraction des congès  de tous les utilisateurs 

### ISSUE THREAD

**Issue by en3rgizz** [libertempo/Libertempo-web#668]
Bonjour, 

Actuellement, Libertempo permet  l’édition de congés pour un utilisateur unique.
Par soucis de gain de temps y'a t'il une possibilité de générer toutes les pages d'un seul  coup ? en plus de la 1ere possibilité  
Merci par avance

**Comment by wouldsmina** [comment]
Bonjour,

Non ce n'est pas encore possible, mais c'est une fonctionnalité que l'on souhaite offrir (#415). Je ferme pour ne pas faire doublons.
