### ISSUE TITLE
Impression du calendrier 

### ISSUE THREAD

**Issue by ocinlas** [libertempo/Libertempo-web#672]
Bonjour, 

Je suis en derniere version de libertempo. 

est il possible d'imprimer le calendrier pour un groupe ou tous le monde ? 

de l'exporter sur excel ? 

Merci

**Comment by wouldsmina** [comment]
bonjour,

Non, ce n'est pas possible, nous prévoyons de permettre au RH d'imprimer ou exporter des informations mais le calendrier n'a pas vocation à etre imprimé. Nous conseillons de le consulter directement depuis l'application pour avoir les informations les plus fraiches.

Cordialement.

**Comment by ocinlas** [comment]
Bonjour, 
ceci est embetant d'autant que nous avons une obligation d'affichage des periodes de conges ...
