### ISSUE TITLE
PB export .ics

### ISSUE THREAD

**Issue by ocinlas** [libertempo/Libertempo-web#673]
bonjour, 

Je suis en dernier version et lors de l'export le fichier est ouvert par outlook mais n'affiche pas le calendrier.

merci

**Comment by wouldsmina** [comment]
bonjour,

Je ne connais pas outlook, mais je pense que tu dois copier/coller l'adresse de l'export ics lors de la procédure de création d'un calendrier dans outlook.

Cette demande n'étant pas liée à LT mais a outlook, je ferme. Si besoin, demande de l'aide sur un forum dédié à outlook tu aura plus de chance d'obtenir une réponse.
