### ISSUE TITLE
Error 500 "calendrier.php"

### ISSUE THREAD

**Issue by HugoMARMORAT** [libertempo/Libertempo-web#674]
**Décrivez le bug**
Bonjour,
A l'issue d'une mise à jour PHP 5.1 vers PHP 5.6 la page calendrier de s'affiche plus.
HTTP ERROR 500

**Poste (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS] : W8.1
 - Navigateur et version : Chrome Version 67.0.3396.87
 - Erreur dans la console : A priori pas

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : VM Debian 7
 - Version de Libertempo : 1.10
 - Version MySQL et PHP : PHP 5.6 Mysql 5.5
 - Erreur dans le log du serveur : A priori pas

Je vous remercie de votre aide.
bien cordialement

**Comment by prytoegrian** [comment]
Bonjour,

une erreur de ce type devrait apparaître dans l'erreur log `/var/log/apache2/error.log`. Tu n'as vraiment pas de sortie ?

**Comment by HugoMARMORAT** [comment]
Bonjour,
Je te remercie pour ta réponse rapide.
Je viens d'extraire les logs de ma propre connexion que tu trouveras ci-dessous.
Précision, serveur Apache 2.2.22
L'heure n'est pas si matinale que ça mais je ne vois rien.
Je te remercie de ton aide.
Bien cordialement.

192.168.32.126 - - [21/Jun/2018:10:20:02 +0200] "GET /libertempo/ HTTP/1.1" 200 1904 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
192.168.32.126 - - [21/Jun/2018:10:20:05 +0200] "POST /libertempo/index.php HTTP/1.1" 302 739 "http://urbfrmtp0901/libertempo/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
192.168.32.126 - - [21/Jun/2018:10:20:05 +0200] "GET /libertempo/admin/admin_index.php HTTP/1.1" 200 6693 "http://urbfrmtp0901/libertempo/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
192.168.32.126 - - [21/Jun/2018:10:20:09 +0200] "GET /libertempo/calendrier.php HTTP/1.1" 500 524 "http://urbfrmtp0901/libertempo/admin/admin_index.php" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"

**Comment by HugoMARMORAT** [comment]
Bonjour,
merci de m'avoir mis sur la piste.
Le fichier d'erreur était explicite. Le "timezone" s'était mis par défaut.
Je l'ai réglé dans les paramètres PHP et le calendrier apparaît.
Merci infiniment pour votre réactivité.
Bonne journée.

**Comment by prytoegrian** [comment]
:+1:
