### ISSUE TITLE
conception : multi-device / responsive design 

### ISSUE THREAD

**Issue by coz787** [Libertempo/Libertempo-web#98]
Dans la reconception en cours - Libertempo - (ou refactoring) y-a-t-il une intention de rendre
l'application utilisable au travers un smartphone ? 
est-ce que la logique de "responsive design" , afaik supporté par bootstrap est mise en oeuvre ? 

j'ai essayé d'utiliser libertempo depuis un smartphone, cela ne saute pas aux yeux . 
merci.

**Comment by Prytoegrian** [comment]
Il n'y a pas d'intention officielle d'en faire une application utilisable pour smartphone mais compte tenu des changements dans le code, il pourrait être facile de mettre en œuvre cette idée à l'avenir . 

Je m'axe principalement sur l'architecture du code pour moment, l'apparence n'ayant pas pour but de changer pour le moment. Lorsque viendra la question de l'UX, il est possible que ce sujet arrive sur le tapis, même si l'accent devrait être mis sur les tablettes et les pc pour des raisons évidentes. La porte n'est pas fermée donc, s'il y a un besoin dans ce sens. 

Pour ta seconde question, il y quelques changements CSS selon l'écran mais ça n'est pas très poussé en effet. Du coup non. 

Si t'es sensible à la cause, je t'invite à ouvrir un ticket pour y évoquer les changements UX auxquels tu penses pour amorcer une discussion de travail :-)

**Comment by coz787** [comment]
Merci. Ma boite utilise php_conges (et ceci pour qq temps encore). Disposer d'une appli multi-device (reprenant toutes les fonctionalités de la version de php_conges que ns utilisons) peut être un objectif séduisant.  J'essaierai de contribuer autant que je peux.

**Comment by Prytoegrian** [comment]
Il ne s'agissait que d'une question, et nous n'avons pas fais davantage d'étude depuis plus d'un an, je ferme donc. S'il y a un vrai besoin, ça reviendra sur le tapis.
